/**
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @un/icon-build-helpers. DO NOT EDIT.
 * @un/icon-build-helpers is a fork of @carbon/icon-build-helpers
 */
'use strict';

var Icon = require('../Icon-17378097.js');
var React = require('react');
require('@carbon/icon-helpers');
require('prop-types');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var React__default = /*#__PURE__*/_interopDefaultLegacy(React);

var _path, _mask, _g, _path2;

var _excluded = ["children"];
var P4pNegative = /*#__PURE__*/React__default['default'].forwardRef(function P4pNegative(_ref, ref) {
  var children = _ref.children,
      rest = Icon._objectWithoutProperties(_ref, _excluded);

  return /*#__PURE__*/React__default['default'].createElement(Icon.Icon, Icon._extends({
    width: 56,
    height: 56,
    viewBox: "0 0 56 56",
    xmlns: "http://www.w3.org/2000/svg",
    fill: "currentColor",
    ref: ref
  }, rest), _path || (_path = /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M42.3026 24.1998C41.9194 24.0466 41.5432 23.9621 41.1787 23.9464C40.8142 23.9307 40.3259 23.9218 39.7197 23.9218H39.0841V28.1975H40.1402C40.769 28.1975 41.2867 28.1601 41.6935 28.0825C42.0973 28.0059 42.4401 27.8526 42.7182 27.6237C42.952 27.4164 43.122 27.1708 43.23 26.8878C43.3381 26.6049 43.3872 26.2591 43.3872 25.8494C43.3872 25.4456 43.2782 25.0998 43.063 24.809C42.8449 24.5182 42.5885 24.3158 42.3026 24.1998Z",
    clipRule: "evenodd"
  })), _mask || (_mask = /*#__PURE__*/React__default['default'].createElement("mask", {
    id: "a",
    width: "56",
    height: "56",
    x: "0",
    y: "0",
    maskUnits: "userSpaceOnUse"
  })), _g || (_g = /*#__PURE__*/React__default['default'].createElement("g", {
    mask: "url(#a)"
  })), _path2 || (_path2 = /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M15.4727 24.1998C15.0895 24.0466 14.7113 23.9621 14.3448 23.9464C13.9843 23.9307 13.496 23.9218 12.8898 23.9218H12.2532V28.1975H13.3093C13.9352 28.1975 14.4549 28.1601 14.8636 28.0825C15.2674 28.0059 15.6093 27.8526 15.8853 27.6237C16.1221 27.4164 16.2921 27.1708 16.3992 26.8878C16.5013 26.6049 16.5563 26.2591 16.5563 25.8494C16.5563 25.4456 16.4483 25.0998 16.2321 24.809C16.0111 24.5182 15.7606 24.3158 15.4727 24.1998Z",
    clipRule: "evenodd"
  })), children);
});

module.exports = P4pNegative;
