/**
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @un/icon-build-helpers. DO NOT EDIT.
 * @un/icon-build-helpers is a fork of @carbon/icon-build-helpers
 */
'use strict';

var Icon = require('../Icon-17378097.js');
var React = require('react');
require('@carbon/icon-helpers');
require('prop-types');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var React__default = /*#__PURE__*/_interopDefaultLegacy(React);

var _path, _mask, _g, _path2;

var _excluded = ["children"];
var VoucherNegative = /*#__PURE__*/React__default['default'].forwardRef(function VoucherNegative(_ref, ref) {
  var children = _ref.children,
      rest = Icon._objectWithoutProperties(_ref, _excluded);

  return /*#__PURE__*/React__default['default'].createElement(Icon.Icon, Icon._extends({
    width: 56,
    height: 56,
    viewBox: "0 0 56 56",
    xmlns: "http://www.w3.org/2000/svg",
    fill: "currentColor",
    ref: ref
  }, rest), _path || (_path = /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M38.7038 32.818H27.0352C26.5587 32.818 26.1707 33.2051 26.1707 33.6826 26.1707 34.16 26.5587 34.5471 27.0352 34.5471H38.7038C39.1803 34.5471 39.5684 34.16 39.5684 33.6826 39.5684 33.2051 39.1803 32.818 38.7038 32.818zM38.7038 27.2003H27.0352C26.5587 27.2003 26.1707 27.5873 26.1707 28.0648 26.1707 28.5423 26.5587 28.9284 27.0352 28.9284H38.7038C39.1803 28.9284 39.5684 28.5423 39.5684 28.0648 39.5684 27.5873 39.1803 27.2003 38.7038 27.2003z",
    clipRule: "evenodd"
  })), _mask || (_mask = /*#__PURE__*/React__default['default'].createElement("mask", {
    id: "a",
    width: "56",
    height: "56",
    x: "0",
    y: "0",
    maskUnits: "userSpaceOnUse"
  })), _g || (_g = /*#__PURE__*/React__default['default'].createElement("g", {
    mask: "url(#a)"
  })), _path2 || (_path2 = /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M38.7038 21.1494H27.0352C26.5587 21.1494 26.1707 21.5374 26.1707 22.0139C26.1707 22.4914 26.5587 22.8785 27.0352 22.8785H38.7038C39.1803 22.8785 39.5684 22.4914 39.5684 22.0139C39.5684 21.5374 39.1803 21.1494 38.7038 21.1494Z",
    clipRule: "evenodd"
  })), children);
});

module.exports = VoucherNegative;
