/**
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @un/icon-build-helpers. DO NOT EDIT.
 * @un/icon-build-helpers is a fork of @carbon/icon-build-helpers
 */
'use strict';

var Icon = require('../Icon-17378097.js');
var React = require('react');
require('@carbon/icon-helpers');
require('prop-types');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var React__default = /*#__PURE__*/_interopDefaultLegacy(React);

var _path;

var _excluded = ["children"];
var WfpHumEvacuationPos = /*#__PURE__*/React__default['default'].forwardRef(function WfpHumEvacuationPos(_ref, ref) {
  var children = _ref.children,
      rest = Icon._objectWithoutProperties(_ref, _excluded);

  return /*#__PURE__*/React__default['default'].createElement(Icon.Icon, Icon._extends({
    width: 41,
    height: 38,
    viewBox: "0 0 41 38",
    xmlns: "http://www.w3.org/2000/svg",
    fill: "currentColor",
    ref: ref
  }, rest), _path || (_path = /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M21.8,36.2 C21.6,36.6 21.2,36.9 20.8,37.1 C20.4,37.2 19.9,37.2 19.5,37 C18.6,36.6 18.3,35.5 18.7,34.6 C20.8,30.5 19.3,25.4 15.2,23.2 L11.4,21.3 L3.8,36.2 C3.5,36.8 2.9,37.2 2.2,37.2 C1.9,37.2 1.7,37.1 1.4,37 C0.5,36.6 0.2,35.5 0.6,34.6 L13.2,10 C9.8,9.6 6.3,11.3 4.6,14.5 C4.2,15.4 3.1,15.7 2.3,15.3 C1.4,14.9 1,13.8 1.5,13 C4.4,7.3 11.2,5 16.9,7.5 C17,7.5 17.1,7.6 17.3,7.6 L19.5,8.7 C21.5,9.7 22.3,12.2 21.3,14.2 L18,20.8 C22.8,24.2 24.6,30.8 21.8,36.2 Z M23.4,7.5 C21.6,8.1 19.7,7.1 19.1,5.4 C18.5,3.6 19.5,1.7 21.2,1.1 C23,0.5 24.9,1.5 25.5,3.2 C26.1,5 25.2,6.9 23.4,7.5 Z M27.4,26.2 C27.1,26.2 26.7,26.1 26.5,25.8 C26,25.3 26,24.5 26.5,23.9 L30.2,20.2 L31.4,18.9 L30.2,17.6 L26.5,13.9 C26,13.4 26,12.6 26.5,12 C27,11.5 27.8,11.5 28.4,12 L34.3,17.9 C34.5,18.1 34.7,18.5 34.7,18.8 C34.7,19.1 34.6,19.5 34.3,19.7 L28.4,25.6 C28.1,26.1 27.8,26.2 27.4,26.2 Z M40.5,20 L34.6,25.9 C34.3,26.2 34,26.3 33.7,26.3 C33.4,26.3 33,26.2 32.8,25.9 C32.3,25.4 32.3,24.6 32.8,24 L36.5,20.3 L37.7,19 L36.5,17.7 L32.8,14 C32.3,13.5 32.3,12.7 32.8,12.1 C33.3,11.6 34.1,11.6 34.7,12.1 L40.6,18 C40.8,18.2 41,18.6 41,18.9 C40.9,19.4 40.8,19.7 40.5,20 Z"
  })), children);
});

module.exports = WfpHumEvacuationPos;
