/**
 *
 * Code generated by @un/icon-build-helpers. DO NOT EDIT.
 * @un/icon-build-helpers is a fork of @carbon/icon-build-helpers
 * 
 */
'use strict';

var index = {
  "elem": "svg",
  "attrs": {
    "xmlns": "http://www.w3.org/2000/svg",
    "fill": "currentColor",
    "viewBox": "0 0 26 34",
    "width": "26",
    "height": "34"
  },
  "content": [{
    "elem": "mask",
    "attrs": {
      "id": "a",
      "width": "26",
      "height": "34",
      "x": "0",
      "y": "0",
      "maskUnits": "userSpaceOnUse"
    },
    "content": [{
      "elem": "path",
      "attrs": {
        "fill-rule": "evenodd",
        "d": "M0.0600586 0.377991H25.6271V34H0.0600586V0.377991Z",
        "clip-rule": "evenodd"
      }
    }]
  }, {
    "elem": "g",
    "attrs": {
      "mask": "url(#a)"
    },
    "content": [{
      "elem": "path",
      "attrs": {
        "d": "M18.164 17.414L17.603 17.967L13.102 22.668C12.942 22.828 12.686 22.828 12.525 22.668L8.025 17.967L7.464 17.414C6.111 16.069 6.014 13.779 7.416 12.473C8.057 11.872 8.897 11.568 9.73 11.568C10.595 11.568 11.461 11.896 12.125 12.545L12.814 13.178L13.503 12.545C14.167 11.896 15.032 11.568 15.897 11.568C16.73 11.568 17.571 11.872 18.212 12.473C19.613 13.779 19.517 16.069 18.164 17.414ZM24.978 2.75899L12.965 0.395991C12.87 0.371991 12.757 0.371991 12.662 0.395991L0.649 2.75899C0.272 2.83099 0 3.15899 0 3.54299V19.704C0 27.601 5.846 34 12.814 34C19.781 34 25.628 27.601 25.628 19.704V3.54299C25.628 3.15899 25.355 2.83099 24.978 2.75899Z",
        "clip-rule": "evenodd"
      }
    }]
  }],
  "name": "security (positive)"
};

module.exports = index;
