#-------------------------------------------------------------------------------
# WFP UI Sass Linter Configuration
#-------------------------------------------------------------------------------
# Linter Options
options:
  formatter: stylish
  merge-default-rules: true
# Rule Configuration
rules:
  # Extends
  extends-before-mixins: 1
  extends-before-declarations: 1
  placeholder-in-extend: 0

  # Mixins
  mixins-before-declarations:
    - 1
    -
      exclude: ['media-query']

  # Line Spacing
  one-declaration-per-line: 1
  empty-line-between-blocks: 1
  single-line-per-selector: 0

  # Disallows
  no-color-keywords: 1
  no-color-literals:
    - 1
    -
      allow-rgba: true
  no-css-comments: 1
  no-debug: 1
  no-duplicate-properties:
    - 1
    -
      exclude: ['display']

  no-empty-rulesets: 1
  no-extends: 0
  no-ids: 1
  no-important: 2
  no-invalid-hex: 1
  no-mergeable-selectors: 0
  no-misspelled-properties:
  - 1
  -
    extra-properties:
      - 'tap-highlight-color'
      - 'touch-callout'
      - 'overflow-scrolling'
      - 'flex-order'
      - 'flex-positive'
      - 'flex-negative'
      - 'flex-preferred-size'
      - 'flex-pack'
      - 'flex-align'
      - 'flex-item-align'
      - 'flex-line-pack'

  no-qualifying-elements:
    - 1
    -
      allow-element-with-attribute: true

  no-trailing-zero: 0
  no-transition-all: 1
  no-url-protocols: 1
  no-vendor-prefixes: 0
  no-warn: 1
  property-units: 0

  # Nesting
  force-attribute-nesting: 0
  force-element-nesting: 1
  force-pseudo-nesting: 0

  # Name Formats
  function-name-format: 1
  id-name-format: 0
  mixin-name-format: 1
  placeholder-name-format: 1
  variable-name-format: 1

  # Style Guide
  bem-depth: 0
  border-zero: 1
  brace-style: 1
  clean-import-paths: 0
  empty-args: 1
  hex-length: 0
  hex-notation: 1
  leading-zero: 0
  nesting-depth:
    - 1
    -
      max-depth: 3
  property-sort-order:
    - 0
    -
      ignore-custom-properties: true
  quotes:
    - 1
    - style: 'double'

  shorthand-values: 1
  url-quotes: 1
  variable-for-property: 1
  zero-unit: 1

  # Inner Spacing
  space-after-comma: 1
  space-before-colon: 1
  space-after-colon: 1
  space-before-brace: 1
  space-before-bang: 1
  space-after-bang: 1
  space-between-parens: 1

  # Final Items
  trailing-semicolon: 1
  final-newline: 1
  indentation:
    - 0
    -
      size: 2
