language: node_js
node_js:
  - '8'
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.5.1
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
script:
  - yarn ci-check
after_script: greenkeeper-lockfile-upload
after_success:
  - yarn semantic-release
before_deploy:
  - yarn build-storybook
deploy:
  provider: npm
  email: robert.guehne@wfp.org
  api_key:
    secure: L6T6qs4XfzPlrg4+WUaVN7NyVYzINRuRvqBv/BiGDlbVRruJD4Fnn7ePmhDq0/FEZsP98uvzugo8QpzVCxN3cZwmEpITGovzsw3qMouRiu8eq1enH0Ck25cS8+Nd0MCeUgnvNJpoEm13ZnNNjakKy1IP8HLwB2/Xmm5PjMiyu4QXbHi2o/KJgGr2qDVDCsSRqJxYMu56Prq4U/J17nTa4JwW+GVDfZwgn0I9SzObTtBPGnHwtEjRf5d9ONzXdp81srhK8YWPY0JN6tSm8kt89SkJ3ZPWn2rxTuSfVjxiEx/x8F6paGr9mq70II5Ogf1zqdn4By24uGV9VKOBEoIUC0v7zsMT2Hp3bZScVLj0IvnyNBtDjZxupy84xEcmyK5IfCIxnkqKwHgGlsWviUyzVCJYQmuuit6f9+0HXKUFFSEpb7KRI8Qocob3v0YT0NPuImbPkfvHDYjtv7DKB3CzWRLItBSOIYJDAJttn39MHO27K8RgkYBxbnufl6n/d4QV/1W8KDeo81k5z+ohSLKfmM8lh4TnQ2ARoGkY7Suz9YaSfO3Afj3bOvm9aJaBlOX5/I8i14Ez3kVnXqjiS85IBZTfWhodvanTLKcA9+8m1WIU8Qr3UJa8vOAA/V8b3bGtXj2nUCdaKI1BRbKNUS7VnMlS6OayQMv8LMBTTHPiv9c=
  on:
    tags: true
    repo: wfp/ui
    branch: master
