/**
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @un/icon-build-helpers. DO NOT EDIT.
 * @un/icon-build-helpers is a fork of @carbon/icon-build-helpers
 */
'use strict';

var Icon = require('../Icon-17378097.js');
var React = require('react');
require('@carbon/icon-helpers');
require('prop-types');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var React__default = /*#__PURE__*/_interopDefaultLegacy(React);

var _mask, _g, _path;

var _excluded = ["children"];
var CashNegative = /*#__PURE__*/React__default['default'].forwardRef(function CashNegative(_ref, ref) {
  var children = _ref.children,
      rest = Icon._objectWithoutProperties(_ref, _excluded);

  return /*#__PURE__*/React__default['default'].createElement(Icon.Icon, Icon._extends({
    width: 56,
    height: 56,
    viewBox: "0 0 56 56",
    xmlns: "http://www.w3.org/2000/svg",
    fill: "currentColor",
    ref: ref
  }, rest), _mask || (_mask = /*#__PURE__*/React__default['default'].createElement("mask", {
    id: "a",
    width: "56",
    height: "56",
    x: "0",
    y: "0",
    maskUnits: "userSpaceOnUse"
  })), _g || (_g = /*#__PURE__*/React__default['default'].createElement("g", {
    mask: "url(#a)"
  })), _path || (_path = /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M38.6498 29.6653C37.2753 29.6653 36.1652 30.7745 36.1652 32.1499 36.1652 32.6058 36.2899 33.0272 36.4962 33.3917 36.9266 34.1374 37.7312 34.6345 38.6498 34.6345 39.5694 34.6345 40.372 34.1374 40.8033 33.3917 41.0106 33.0272 41.1344 32.6058 41.1344 32.1499 41.1344 30.7745 40.0252 29.6653 38.6498 29.6653zM25.8131 26.766C25.5399 26.766 25.2747 26.7827 25.0094 26.8328 22.4167 27.214 20.4302 29.4501 20.4302 32.1499 20.4302 32.5802 20.4793 32.9948 20.5785 33.3917 21.1326 35.7693 23.2695 37.5328 25.8131 37.5328 28.3556 37.5328 30.4925 35.7693 31.0466 33.3917 31.1468 32.9948 31.1959 32.5802 31.1959 32.1499 31.1959 31.3875 31.0387 30.6674 30.7568 30.0131 29.9286 28.1002 28.0236 26.766 25.8131 26.766zM12.9763 30.0789C12.6855 30.0789 12.4045 30.129 12.1471 30.2282 11.1784 30.5603 10.4907 31.4789 10.4907 32.5645 10.4907 33.9389 11.6008 35.0481 12.9763 35.0481 14.0609 35.0481 14.9805 34.3614 15.3116 33.3917 15.4098 33.1353 15.4599 32.8543 15.4599 32.5645 15.4599 31.189 14.3497 30.0789 12.9763 30.0789z",
    clipRule: "evenodd"
  })), children);
});

module.exports = CashNegative;
