/**
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @un/icon-build-helpers. DO NOT EDIT.
 * @un/icon-build-helpers is a fork of @carbon/icon-build-helpers
 */
'use strict';

var Icon = require('../Icon-17378097.js');
var React = require('react');
require('@carbon/icon-helpers');
require('prop-types');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var React__default = /*#__PURE__*/_interopDefaultLegacy(React);

var _mask, _g, _path;

var _excluded = ["children"];
var CashBasedTransfersPositive = /*#__PURE__*/React__default['default'].forwardRef(function CashBasedTransfersPositive(_ref, ref) {
  var children = _ref.children,
      rest = Icon._objectWithoutProperties(_ref, _excluded);

  return /*#__PURE__*/React__default['default'].createElement(Icon.Icon, Icon._extends({
    width: 41,
    height: 41,
    viewBox: "0 0 41 41",
    xmlns: "http://www.w3.org/2000/svg",
    fill: "currentColor",
    ref: ref
  }, rest), _mask || (_mask = /*#__PURE__*/React__default['default'].createElement("mask", {
    id: "a",
    width: "41",
    height: "41",
    x: "0",
    y: "0",
    maskUnits: "userSpaceOnUse"
  })), _g || (_g = /*#__PURE__*/React__default['default'].createElement("g", {
    mask: "url(#a)"
  })), _path || (_path = /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M33.72 23.297C32.32 23.297 31.191 22.167 31.191 20.768C31.191 19.369 32.32 18.239 33.72 18.239C35.119 18.239 36.249 19.369 36.249 20.768C36.249 22.167 35.119 23.297 33.72 23.297ZM20.232 26.669C16.969 26.669 14.331 24.031 14.331 20.768C14.331 17.506 16.969 14.867 20.232 14.867C23.494 14.867 26.133 17.506 26.133 20.768C26.133 24.031 23.494 26.669 20.232 26.669ZM6.74402 23.297C5.34502 23.297 4.21502 22.167 4.21502 20.768C4.21502 19.369 5.34502 18.239 6.74402 18.239C8.14302 18.239 9.27302 19.369 9.27302 20.768C9.27302 22.167 8.14302 23.297 6.74402 23.297ZM38.803 12.338H1.66102C1.20602 12.338 0.843018 12.701 0.843018 13.156V28.38C0.843018 28.836 1.20602 29.198 1.66102 29.198H38.803C39.259 29.198 39.621 28.836 39.621 28.38V13.156C39.621 12.701 39.259 12.338 38.803 12.338Z",
    clipRule: "evenodd"
  })), children);
});

module.exports = CashBasedTransfersPositive;
