/**
 *
 * Code generated by @un/icon-build-helpers. DO NOT EDIT.
 * @un/icon-build-helpers is a fork of @carbon/icon-build-helpers
 * 
 */
'use strict';

var index = {
  "elem": "svg",
  "attrs": {
    "xmlns": "http://www.w3.org/2000/svg",
    "fill": "currentColor",
    "viewBox": "0 0 56 56",
    "width": "56",
    "height": "56"
  },
  "content": [{
    "elem": "mask",
    "attrs": {
      "id": "a",
      "width": "56",
      "height": "56",
      "x": "0",
      "y": "0",
      "maskUnits": "userSpaceOnUse"
    },
    "content": [{
      "elem": "path",
      "attrs": {
        "fill-rule": "evenodd",
        "d": "M0 0H56V56H0V0Z",
        "clip-rule": "evenodd"
      }
    }]
  }, {
    "elem": "g",
    "attrs": {
      "mask": "url(#a)"
    },
    "content": [{
      "elem": "path",
      "attrs": {
        "d": "M40.9202 35.052L40.2395 32.4295H35.7436L35.0422 35.052H30.936L35.4496 21.0039H40.4387L45.0095 35.052H40.9202ZM30.5858 29.799H26.4382V35.052H22.7583V21.0617H30.936V24.0962H26.4382V26.7646H30.5858V29.799ZM20.4862 24.0962H15.9904V26.7646H20.137V29.799H15.9904V35.052H12.3095V21.0617H20.4862V24.0962ZM53.6667 0H2.33325C1.04972 0 0 1.06137 0 2.35914V53.6409C0 54.9386 1.04972 56 2.33325 56H53.6667C54.9503 56 56 54.9386 56 53.6409V2.35914C56 1.06137 54.9503 0 53.6667 0Z",
        "clip-rule": "evenodd"
      }
    }]
  }, {
    "elem": "path",
    "attrs": {
      "d": "M38.1999 25.5203C38.0024 24.7215 37.8707 24.1507 37.8098 23.8039C37.7529 24.1242 37.6409 24.6518 37.4748 25.3876C37.3078 26.1225 36.9384 27.5716 36.3666 29.7321H39.2992L38.7049 27.4705C38.5653 26.9674 38.3993 26.318 38.1999 25.5203Z",
      "clip-rule": "evenodd"
    }
  }],
  "name": "food assistance for assets (negative)"
};

module.exports = index;
