/* eslint-disable */
/* Updated at Mon, 06 Sep 2021 13:14:23 GMT*/
module.exports = {
    /** WFP brand color */
    'primary-/ brand-01': '#007dbc',
    /** Primary interactive colour (e.g. buttons, links) */
    'primary/interactive-01': '#0b77c2',
    /** Secondary interactive color (e.g. hover and active states) */
    'primary-/ interactive-02': '#085387',
    'others/accent-01-(legacy)': '#f7b825',
    'extended-primary / brand-01-20': '#c2dbec',
    'extended-primary / brand-01-30': '#85b7da',
    'extended-primary / brand-01-40': '#4792c7',
    'extended-primary / brand-01-60': '#085387',
    'extended-primary / brand-01-70': '#05375a',
    'extended-primary / brand-01-80': '#031c2d',
    /** Primary color for text */
    'text/text-01': '#031c2d',
    /** Secondary color for text, e.g. subtitle */
    'text-/ text-02': '#5a6872',
    'text-/ text-03': '#818d94',
    'text-/ text-04': '#010100',
    'neutrals-/ ui-01': '#010100',
    /** Use this color as page background if there are modules on top of it (e.g. cards), to increase the contrast of the modules and make them visually stand out.  */
    'neutrals-/ ui-02': '#eff2f5',
    /** Tertiary background color, subtle border */
    'neutrals-/ ui-03': '#f0f3f6',
    /** Medium contrast border */
    'neutrals-/ ui-04': '#dfe3e6',
    /** High contrast border */
    'neutrals-/ ui-05': '#8c9ba5',
    'neutrals/ui-06': '#0b1923',
    'neutrals/inverse-01': '#010100',
    'neutrals/field-01': '#010100',
    'neutrals/field-border-01': '#d4d7d9',
    'semantic-/ support-01': '#c5192d',
    'semantic-/ support-02': '#689e18',
    'semantic-/ support-03': '#f7b825',
    'semantic-/ support-light-01': '#f1c6cb',
    'semantic/support-light-02': '#ccdbcd',
    'semantic-/ support-light-03': '#fdedc9',
    'semantic-/ support-light-04': '#c2dbec',
    'datavis-/ sequential / default / sequential-default-01': '#9deb00',
    'datavis-/ sequential / default / sequential-default-02': '#73c3fe',
    'datavis-/ sequential / default / sequential-default-03': '#4aa1e2',
    'datavis-/ sequential / default / sequential-default-04': '#0780c0',
    'datavis-/ sequential / default / sequential-default-05': '#005f9b',
    'datavis-/ sequential / default / sequential-default-06': '#003f76',
    'datavis-/ sequential / default / sequential-default-07': '#002153',
    'datavis-/ sequential / secondary / sequential-secondary-01': '#bdf9c4',
    'datavis-/ sequential / secondary / sequential-secondary-02': '#89eaa8',
    'datavis-/ sequential / secondary / sequential-secondary-03': '#5fd79a',
    'datavis-/ sequential / secondary / sequential-secondary-04': '#41c196',
    'datavis-/ sequential / secondary / sequential-secondary-05': '#33aa96',
    'datavis-/ sequential / secondary / sequential-secondary-06': '#319298',
    'datavis-/ sequential / secondary / sequential-secondary-07': '#367a96',
    'datavis-/ categorical / categorical-01': '#007dbc',
    'datavis-/ categorical / categorical-02': '#36b5c5',
    'datavis-/ categorical / categorical-03': '#00b485',
    'datavis-/ categorical / categorical-04': '#008868',
    'datavis-/ categorical / categorical-05': '#1a4262',
    'datavis-/ categorical / categorical-06': '#982b56',
    'datavis-/ categorical / categorical-07': '#ef404c',
    'datavis-/ categorical / categorical-08': '#f47847',
    'datavis-/ categorical / categorical-09': '#b79f8d',
    'datavis-/ categorical / categorical-10': '#ecdfbb',
    'datavis-/ diverging / diverging-01': '#73c5d0',
    'datavis-/ diverging / diverging-02': '#ecdfbb',
    'datavis-/ alert / alert-01': '#5fd79a',
    'datavis-/ alert / alert-02': '#a0db90',
    'datavis-/ alert / alert-03': '#d0de85',
    'datavis-/ alert / alert-04': '#fbe07a',
    'datavis-/ alert / alert-05': '#fbb16a',
    'datavis-/ alert / alert-06': '#f77f5b',
    'datavis-/ alert / alert-07': '#ef404c',
    /** WFP brand color */
    'primary-/ brand-01': '#007dbc',
}