/**
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @un/icon-build-helpers. DO NOT EDIT.
 * @un/icon-build-helpers is a fork of @carbon/icon-build-helpers
 */
'use strict';

var Icon = require('../Icon-17378097.js');
var React = require('react');
require('@carbon/icon-helpers');
require('prop-types');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var React__default = /*#__PURE__*/_interopDefaultLegacy(React);

var _path, _mask, _g;

var _excluded = ["children"];
var ResourcingPositive = /*#__PURE__*/React__default['default'].forwardRef(function ResourcingPositive(_ref, ref) {
  var children = _ref.children,
      rest = Icon._objectWithoutProperties(_ref, _excluded);

  return /*#__PURE__*/React__default['default'].createElement(Icon.Icon, Icon._extends({
    width: 29,
    height: 39,
    viewBox: "0 0 29 39",
    xmlns: "http://www.w3.org/2000/svg",
    fill: "currentColor",
    ref: ref
  }, rest), _path || (_path = /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M13.6079 9.36901L12.2889 3.41601C12.1259 2.68201 11.4759 2.16101 10.7239 2.16101H6.40094C5.88894 2.16101 5.50794 2.63501 5.61894 3.13501L7.20194 9.36901H13.6079Z",
    clipRule: "evenodd"
  })), _mask || (_mask = /*#__PURE__*/React__default['default'].createElement("mask", {
    id: "a",
    width: "29",
    height: "39",
    x: "0",
    y: "0",
    maskUnits: "userSpaceOnUse"
  })), _g || (_g = /*#__PURE__*/React__default['default'].createElement("g", {
    mask: "url(#a)"
  })), children);
});

module.exports = ResourcingPositive;
