/**
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @un/icon-build-helpers. DO NOT EDIT.
 * @un/icon-build-helpers is a fork of @carbon/icon-build-helpers
 */
'use strict';

var Icon = require('../Icon-17378097.js');
var React = require('react');
require('@carbon/icon-helpers');
require('prop-types');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var React__default = /*#__PURE__*/_interopDefaultLegacy(React);

var _path, _mask, _g;

var _excluded = ["children"];
var EmergencyResponseNegative = /*#__PURE__*/React__default['default'].forwardRef(function EmergencyResponseNegative(_ref, ref) {
  var children = _ref.children,
      rest = Icon._objectWithoutProperties(_ref, _excluded);

  return /*#__PURE__*/React__default['default'].createElement(Icon.Icon, Icon._extends({
    width: 56,
    height: 56,
    viewBox: "0 0 56 56",
    xmlns: "http://www.w3.org/2000/svg",
    fill: "currentColor",
    ref: ref
  }, rest), _path || (_path = /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M34.5549 42.3311C34.4174 42.4608 34.2327 42.5276 33.9979 42.5276H33.7159V41.2072H34.1177C34.548 41.2072 34.7612 41.4017 34.7612 41.7888 34.7612 42.0197 34.6925 42.1994 34.5549 42.3311zM34.1531 39.9536H32.1656V45.698H33.7159V43.792H34.1531C34.8487 43.792 35.3871 43.6171 35.7643 43.2684 36.1445 42.9186 36.3322 42.4225 36.3322 41.7809 36.3322 41.1964 36.1514 40.7464 35.7869 40.4291 35.4224 40.1127 34.8791 39.9536 34.1531 39.9536zM28.2309 45.698H29.7596V43.5405H31.4789V42.2957H29.7596V41.1993H31.6233V39.9536H28.2309V45.698z",
    clipRule: "evenodd"
  })), _mask || (_mask = /*#__PURE__*/React__default['default'].createElement("mask", {
    id: "a",
    width: "56",
    height: "56",
    x: "0",
    y: "0",
    maskUnits: "userSpaceOnUse"
  })), _g || (_g = /*#__PURE__*/React__default['default'].createElement("g", {
    mask: "url(#a)"
  })), children);
});

module.exports = EmergencyResponseNegative;
