/**
 * Copyright IBM Corp. 2016, 2021
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @carbon/icon-build-helpers. DO NOT EDIT.
 */
'use strict';

var iconPropTypes = require('./iconPropTypes-ca0c5320.js');
var React = require('react');
require('@carbon/icon-helpers');
require('prop-types');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var React__default = /*#__PURE__*/_interopDefaultLegacy(React);

var _path;

var _excluded = ["children", "size"];
var Apps = /*#__PURE__*/React__default['default'].forwardRef(function Apps(_ref, ref) {
  var children = _ref.children,
      _ref$size = _ref.size,
      size = _ref$size === void 0 ? 16 : _ref$size,
      rest = iconPropTypes._objectWithoutProperties(_ref, _excluded);

  return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
    width: size,
    height: size,
    ref: ref,
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 23 23",
    fill: "currentColor"
  }, rest), _path || (_path = /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M5.8 1.2L5.8 5.9 1.2 5.9 1.2 1.2 5.8 1.2 5.8 1.2zM7 0L0 0 0 7 7 7 7 0 7 0 7 0zM13.8 1.2L13.8 5.9 9.2 5.9 9.2 1.2 13.8 1.2 13.8 1.2zM15 0L8 0 8 7 15 7 15 0 15 0 15 0zM21.8 1.2L21.8 5.9 17.1 5.9 17.1 1.2 21.8 1.2 21.8 1.2zM23 0L16 0 16 7 23 7 23 0 23 0 23 0zM5.8 9.2L5.8 13.9 1.2 13.9 1.2 9.2 5.8 9.2 5.8 9.2zM7 8L0 8 0 15 7 15 7 8 7 8 7 8zM13.8 9.2L13.8 13.9 9.2 13.9 9.2 9.2 13.8 9.2 13.8 9.2zM15 8L8 8 8 15 15 15 15 8 15 8 15 8zM21.8 9.2L21.8 13.9 17.1 13.9 17.1 9.2 21.8 9.2 21.8 9.2zM23 8L16 8 16 15 23 15 23 8 23 8 23 8zM5.8 17.2L5.8 21.9 1.2 21.9 1.2 17.2 5.8 17.2 5.8 17.2zM7 16L0 16 0 23 7 23 7 16 7 16 7 16zM13.8 17.2L13.8 21.9 9.2 21.9 9.2 17.2 13.8 17.2 13.8 17.2zM15 16L8 16 8 23 15 23 15 16 15 16 15 16zM21.8 17.2L21.8 21.9 17.1 21.9 17.1 17.2 21.8 17.2 21.8 17.2zM23 16L16 16 16 23 23 23 23 16 23 16 23 16z"
  })), children);
});
Apps.propTypes = iconPropTypes.iconPropTypes;

module.exports = Apps;
