/**
 * Copyright IBM Corp. 2016, 2021
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @carbon/icon-build-helpers. DO NOT EDIT.
 */
'use strict';

var iconPropTypes = require('./iconPropTypes-ca0c5320.js');
var React = require('react');
require('@carbon/icon-helpers');
require('prop-types');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var React__default = /*#__PURE__*/_interopDefaultLegacy(React);

var _path;

var _excluded = ["children", "size"];
var Arrows = /*#__PURE__*/React__default['default'].forwardRef(function Arrows(_ref, ref) {
  var children = _ref.children,
      _ref$size = _ref.size,
      size = _ref$size === void 0 ? 16 : _ref$size,
      rest = iconPropTypes._objectWithoutProperties(_ref, _excluded);

  return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
    width: size,
    height: size,
    ref: ref,
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 16 16",
    fill: "currentColor"
  }, rest), _path || (_path = /*#__PURE__*/React__default['default'].createElement("path", {
    fill: "none",
    d: "M12 14.1860664L14.7243242 11.7088816 15.4101839 12.4354056 11.5351839 15.9588816 7.66018388 12.4354056 8.34604353 11.7088816 11 14.1220821 11 0 12 0 12 14.1860664zM5.0375858 1.80480732L5.0375858 16 4.0375858 16 4.0375858 1.80480732 1.34844544 4.25.662585796 3.52347605 4.5375858 0 8.4125858 3.52347605 7.72672615 4.25 5.0375858 1.80480732z"
  })), children);
});
Arrows.propTypes = iconPropTypes.iconPropTypes;

module.exports = Arrows;
