/**
 * Copyright IBM Corp. 2016, 2021
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @carbon/icon-build-helpers. DO NOT EDIT.
 */
'use strict';

var iconPropTypes = require('./iconPropTypes-ca0c5320.js');
var React = require('react');
require('@carbon/icon-helpers');
require('prop-types');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var React__default = /*#__PURE__*/_interopDefaultLegacy(React);

var _path;

var _excluded = ["children", "size"];
var AsleepGlyph = /*#__PURE__*/React__default['default'].forwardRef(function AsleepGlyph(_ref, ref) {
  var children = _ref.children,
      _ref$size = _ref.size,
      size = _ref$size === void 0 ? 16 : _ref$size,
      rest = iconPropTypes._objectWithoutProperties(_ref, _excluded);

  return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
    width: size,
    height: size,
    ref: ref,
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 14 17",
    fill: "currentColor"
  }, rest), _path || (_path = /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M12.0428965,3.50537551 C10.5427127,1.20537551 7.9423942,-0.0946244947 5.24206344,0.00537550532 C4.94202669,0.00537550532 4.74200219,0.105375505 4.64198994,0.405375505 C4.54197769,0.605375505 4.64198994,0.805375505 4.84201444,1.00537551 C5.14205119,1.30537551 5.34207569,1.60537551 5.54210019,1.90537551 C6.74224719,3.80537551 7.04228394,6.20537551 6.34219819,8.30537551 C5.34207569,10.8053755 3.14180619,12.6053755 0.541487681,13.0053755 C0.341463181,13.0053755 0.141438681,13.2053755 0.0414264304,13.4053755 C-0.0585858198,13.6053755 0.0414264304,13.8053755 0.141438681,14.0053755 C1.64162243,15.3053755 3.54185519,16.0053755 5.44208794,16.0053755 C6.04216144,16.0053755 6.74224719,15.9053755 7.3423207,15.8053755 C9.9426392,15.1053755 11.9428842,13.3053755 12.9430067,10.8053755 C13.9431292,8.30537551 13.6430925,5.60537551 12.0428965,3.50537551 L12.0428965,3.50537551 L12.0428965,3.50537551 Z"
  })), children);
});
AsleepGlyph.propTypes = iconPropTypes.iconPropTypes;

module.exports = AsleepGlyph;
