/**
 * Copyright IBM Corp. 2016, 2021
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @carbon/icon-build-helpers. DO NOT EDIT.
 */
'use strict';

var iconPropTypes = require('./iconPropTypes-ca0c5320.js');
var React = require('react');
require('@carbon/icon-helpers');
require('prop-types');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var React__default = /*#__PURE__*/_interopDefaultLegacy(React);

var _g;

var _excluded = ["children", "size"];
var Awake = /*#__PURE__*/React__default['default'].forwardRef(function Awake(_ref, ref) {
  var children = _ref.children,
      _ref$size = _ref.size,
      size = _ref$size === void 0 ? 16 : _ref$size,
      rest = iconPropTypes._objectWithoutProperties(_ref, _excluded);

  return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
    width: size,
    height: size,
    ref: ref,
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 16 16",
    fill: "currentColor"
  }, rest), _g || (_g = /*#__PURE__*/React__default['default'].createElement("g", {
    fill: "none",
    "fill-rule": "evenodd"
  }, /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M7.5 6.31088724e-30L8.5 6.31088724e-30 8.5 3 7.5 3zM7.5 13L8.5 13 8.5 16 7.5 16z"
  }), /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M14 6.5L15 6.5 15 9.5 14 9.5z",
    transform: "rotate(90 14.5 8)"
  }), /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M1 6.5L2 6.5 2 9.5 1 9.5z",
    transform: "rotate(90 1.5 8)"
  }), /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M2.90380592 1.90380592L3.90380592 1.90380592 3.90380592 4.90380592 2.90380592 4.90380592z",
    transform: "rotate(-45 3.404 3.404)"
  }), /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M12.0961941 11.0961941L13.0961941 11.0961941 13.0961941 14.0961941 12.0961941 14.0961941z",
    transform: "rotate(-45 12.596 12.596)"
  }), /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M12.0961941 1.90380592L13.0961941 1.90380592 13.0961941 4.90380592 12.0961941 4.90380592z",
    transform: "rotate(45 12.596 3.404)"
  }), /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M2.90380592 11.0961941L3.90380592 11.0961941 3.90380592 14.0961941 2.90380592 14.0961941z",
    transform: "rotate(45 3.404 12.596)"
  }), /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M8,10.5 C9.38071187,10.5 10.5,9.38071187 10.5,8 C10.5,6.61928813 9.38071187,5.5 8,5.5 C6.61928813,5.5 5.5,6.61928813 5.5,8 C5.5,9.38071187 6.61928813,10.5 8,10.5 Z M8,11.5 C6.06700338,11.5 4.5,9.93299662 4.5,8 C4.5,6.06700338 6.06700338,4.5 8,4.5 C9.93299662,4.5 11.5,6.06700338 11.5,8 C11.5,9.93299662 9.93299662,11.5 8,11.5 Z"
  }))), children);
});
Awake.propTypes = iconPropTypes.iconPropTypes;

module.exports = Awake;
