/**
 * Copyright IBM Corp. 2016, 2021
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @carbon/icon-build-helpers. DO NOT EDIT.
 */
'use strict';

var iconPropTypes = require('./iconPropTypes-ca0c5320.js');
var React = require('react');
require('@carbon/icon-helpers');
require('prop-types');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var React__default = /*#__PURE__*/_interopDefaultLegacy(React);

var _path;

var _excluded = ["children", "size"];
var Calendar = /*#__PURE__*/React__default['default'].forwardRef(function Calendar(_ref, ref) {
  var children = _ref.children,
      _ref$size = _ref.size,
      size = _ref$size === void 0 ? 16 : _ref$size,
      rest = iconPropTypes._objectWithoutProperties(_ref, _excluded);

  return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
    width: size,
    height: size,
    ref: ref,
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 14 16",
    fill: "currentColor"
  }, rest), _path || (_path = /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M0,5 L14,5 L14,6 L0,6 L0,5 Z M3,0 L4,0 L4,4 L3,4 L3,0 Z M10,0 L11,0 L11,4 L10,4 L10,0 Z M0,2.5 C-8.32667268e-17,1.67157288 0.671572875,1 1.5,1 L12.5,1 C13.3284271,1 14,1.67157288 14,2.5 L14,14.5 C14,15.3284271 13.3284271,16 12.5,16 L1.5,16 C0.671572875,16 1.66533454e-16,15.3284271 0,14.5 L0,2.5 Z M1,2.5 L1,14.5 C1,14.7761424 1.22385763,15 1.5,15 L12.5,15 C12.7761424,15 13,14.7761424 13,14.5 L13,2.5 C13,2.22385763 12.7761424,2 12.5,2 L1.5,2 C1.22385763,2 1,2.22385763 1,2.5 Z"
  })), children);
});
Calendar.propTypes = iconPropTypes.iconPropTypes;

module.exports = Calendar;
