/**
 * Copyright IBM Corp. 2016, 2021
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @carbon/icon-build-helpers. DO NOT EDIT.
 */
'use strict';

var iconPropTypes = require('./iconPropTypes-ca0c5320.js');
var React = require('react');
require('@carbon/icon-helpers');
require('prop-types');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var React__default = /*#__PURE__*/_interopDefaultLegacy(React);

var _path, _path2;

var _excluded = ["children", "size"];
var Chat = /*#__PURE__*/React__default['default'].forwardRef(function Chat(_ref, ref) {
  var children = _ref.children,
      _ref$size = _ref.size,
      size = _ref$size === void 0 ? 16 : _ref$size,
      rest = iconPropTypes._objectWithoutProperties(_ref, _excluded);

  return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
    width: size,
    height: size,
    ref: ref,
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 16 16",
    fill: "currentColor"
  }, rest), _path || (_path = /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M3 8L3 7 9 7 9 8zM3 5L3 4 13 4 13 5z"
  })), _path2 || (_path2 = /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M11.7,12l-3.9,4l-0.7-0.7l4.1-4.3H14c0.6,0,1-0.4,1-1V2c0-0.6-0.4-1-1-1H2C1.4,1,1,1.4,1,2v8c0,0.6,0.4,1,1,1 h5.5v1H2c-1.1,0-2-0.9-2-2V2c0-1.1,0.9-2,2-2h12c1.1,0,2,0.9,2,2v8c0,1.1-0.9,2-2,2H11.7z"
  })), children);
});
Chat.propTypes = iconPropTypes.iconPropTypes;

module.exports = Chat;
