/**
 * Copyright IBM Corp. 2016, 2021
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @carbon/icon-build-helpers. DO NOT EDIT.
 */
'use strict';

var iconPropTypes = require('./iconPropTypes-ca0c5320.js');
var React = require('react');
require('@carbon/icon-helpers');
require('prop-types');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var React__default = /*#__PURE__*/_interopDefaultLegacy(React);

var _g;

var _excluded = ["children", "size"];
var Code = /*#__PURE__*/React__default['default'].forwardRef(function Code(_ref, ref) {
  var children = _ref.children,
      _ref$size = _ref.size,
      size = _ref$size === void 0 ? 16 : _ref$size,
      rest = iconPropTypes._objectWithoutProperties(_ref, _excluded);

  return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
    width: size,
    height: size,
    ref: ref,
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 16 10",
    fill: "currentColor"
  }, rest), _g || (_g = /*#__PURE__*/React__default['default'].createElement("g", {
    fill: "none",
    "fill-rule": "evenodd"
  }, /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M2.1455592 4.3157206L-1.01462468 7.24361101 -1.69425692 6.510058 2.1455592 2.95249261 5.98537532 6.510058 5.30574308 7.24361101z",
    transform: "rotate(-90 2.146 5.098)"
  }), /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M13.8544408 4.3157206L10.6942569 7.24361101 10.0146247 6.510058 13.8544408 2.95249261 17.6942569 6.510058 17.0146247 7.24361101z",
    transform: "rotate(90 13.854 5.098)"
  }), /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M6.46631395 10L5.53875202 9.6118735 9.56071834 8.43769499e-14 10.4882803 0.388126504z"
  }))), children);
});
Code.propTypes = iconPropTypes.iconPropTypes;

module.exports = Code;
