/**
 * Copyright IBM Corp. 2016, 2021
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @carbon/icon-build-helpers. DO NOT EDIT.
 */
'use strict';

var iconPropTypes = require('./iconPropTypes-ca0c5320.js');
var React = require('react');
require('@carbon/icon-helpers');
require('prop-types');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var React__default = /*#__PURE__*/_interopDefaultLegacy(React);

var _path;

var _excluded = ["children", "size"];
var Ellipsis = /*#__PURE__*/React__default['default'].forwardRef(function Ellipsis(_ref, ref) {
  var children = _ref.children,
      _ref$size = _ref.size,
      size = _ref$size === void 0 ? 16 : _ref$size,
      rest = iconPropTypes._objectWithoutProperties(_ref, _excluded);

  return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
    width: size,
    height: size,
    ref: ref,
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 16 16",
    fill: "currentColor"
  }, rest), _path || (_path = /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M9.5,8.5 C9.5,9.328125 8.828125,10 8,10 C7.171875,10 6.5,9.328125 6.5,8.5 C6.5,7.671875 7.171875,7 8,7 C8.828125,7 9.5,7.671875 9.5,8.5 Z M14.5,7 C13.671875,7 13,7.671875 13,8.5 C13,9.328125 13.671875,10 14.5,10 C15.328125,10 16,9.328125 16,8.5 C16,7.671875 15.328125,7 14.5,7 Z M1.5,7 C0.671875,7 0,7.671875 0,8.5 C0,9.328125 0.671875,10 1.5,10 C2.328125,10 3,9.328125 3,8.5 C3,7.671875 2.328125,7 1.5,7 Z"
  })), children);
});
Ellipsis.propTypes = iconPropTypes.iconPropTypes;

module.exports = Ellipsis;
