/**
 * Copyright IBM Corp. 2016, 2021
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @carbon/icon-build-helpers. DO NOT EDIT.
 */
'use strict';

var iconPropTypes = require('./iconPropTypes-ca0c5320.js');
var React = require('react');
require('@carbon/icon-helpers');
require('prop-types');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var React__default = /*#__PURE__*/_interopDefaultLegacy(React);

var _path;

var _excluded = ["children", "size"];
var Email = /*#__PURE__*/React__default['default'].forwardRef(function Email(_ref, ref) {
  var children = _ref.children,
      _ref$size = _ref.size,
      size = _ref$size === void 0 ? 16 : _ref$size,
      rest = iconPropTypes._objectWithoutProperties(_ref, _excluded);

  return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
    width: size,
    height: size,
    ref: ref,
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 16 11",
    fill: "currentColor"
  }, rest), _path || (_path = /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M2.02815,1 L8.00484537,5.37996413 L13.9735067,1 L2.02815,1 Z M15,1.48709525 L8.30085543,6.4031076 C8.12490135,6.53222743 7.88552855,6.53230421 7.70949168,6.40329727 L1,1.48631036 L1,10 L15,10 L15,1.48709525 Z M1,5.68434189e-14 L15,5.68434189e-14 C15.5522847,5.67419658e-14 16,0.44771525 16,1 L16,10 C16,10.5522847 15.5522847,11 15,11 L1,11 C0.44771525,11 9.09562337e-13,10.5522847 9.09494702e-13,10 L9.09494702e-13,1 C9.09427066e-13,0.44771525 0.44771525,5.69448719e-14 1,5.68434189e-14 Z"
  })), children);
});
Email.propTypes = iconPropTypes.iconPropTypes;

module.exports = Email;
