/**
 * Copyright IBM Corp. 2016, 2021
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @carbon/icon-build-helpers. DO NOT EDIT.
 */
'use strict';

var iconPropTypes = require('./iconPropTypes-ca0c5320.js');
var React = require('react');
require('@carbon/icon-helpers');
require('prop-types');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var React__default = /*#__PURE__*/_interopDefaultLegacy(React);

var _path;

var _excluded = ["children", "size"];
var EmergencyL2Large = /*#__PURE__*/React__default['default'].forwardRef(function EmergencyL2Large(_ref, ref) {
  var children = _ref.children,
      _ref$size = _ref.size,
      size = _ref$size === void 0 ? 16 : _ref$size,
      rest = iconPropTypes._objectWithoutProperties(_ref, _excluded);

  return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
    width: size,
    height: size,
    ref: ref,
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 63 58",
    fill: "currentColor"
  }, rest), _path || (_path = /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M63,0 L63,58 L0,58 L0,0 L63,0 Z M20.4423828,17.0146484 L15.1445312,17.0146484 L15.1445312,42 L30.5766602,42 L30.5766602,37.625 L20.4423828,37.625 L20.4423828,17.0146484 Z M42.0268555,16.6557617 C40.8419537,16.6557617 39.7710009,16.7725411 38.8139648,17.0061035 C37.8569288,17.2396659 36.9739624,17.5729145 36.1650391,18.0058594 C35.3561157,18.4388042 34.3364319,19.1793567 33.105957,20.2275391 L33.105957,20.2275391 L35.9770508,23.628418 C36.9682667,22.8081014 37.9195918,22.1757835 38.8310547,21.7314453 C39.7425176,21.2871072 40.6824496,21.0649414 41.6508789,21.0649414 C42.5737351,21.0649414 43.3114393,21.3098934 43.8640137,21.7998047 C44.416588,22.289716 44.6928711,23.035965 44.6928711,24.0385742 C44.6928711,24.7107781 44.5675468,25.3601857 44.3168945,25.9868164 C44.0662422,26.6134471 43.6560901,27.2941858 43.0864258,28.0290527 C42.6306943,28.6169463 41.7629933,29.578527 40.4833041,30.9138151 L40.4833041,30.9138151 L39.4462891,31.9853516 L33.1743164,38.3256836 L33.1743164,42 L50.6401367,42 L50.6401367,37.5566406 L39.7539062,37.5566406 L39.7539062,37.3173828 L42.9667969,34.2924805 C45.1087347,32.3328353 46.604081,30.8232475 47.4528809,29.7636719 C48.3016807,28.7040963 48.928302,27.6701711 49.3327637,26.6618652 C49.7372253,25.6535594 49.9394531,24.5740617 49.9394531,23.4233398 C49.9394531,22.1017187 49.6090528,20.9282278 48.9482422,19.902832 C48.2874316,18.8774363 47.3588927,18.0799182 46.1625977,17.5102539 C44.9663026,16.9405896 43.5877357,16.6557617 42.0268555,16.6557617 Z"
  })), children);
});
EmergencyL2Large.propTypes = iconPropTypes.iconPropTypes;

module.exports = EmergencyL2Large;
