/**
 * Copyright IBM Corp. 2016, 2021
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @carbon/icon-build-helpers. DO NOT EDIT.
 */
'use strict';

var iconPropTypes = require('./iconPropTypes-ca0c5320.js');
var React = require('react');
require('@carbon/icon-helpers');
require('prop-types');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var React__default = /*#__PURE__*/_interopDefaultLegacy(React);

var _path;

var _excluded = ["children", "size"];
var EmergencyMSmall = /*#__PURE__*/React__default['default'].forwardRef(function EmergencyMSmall(_ref, ref) {
  var children = _ref.children,
      _ref$size = _ref.size,
      size = _ref$size === void 0 ? 16 : _ref$size,
      rest = iconPropTypes._objectWithoutProperties(_ref, _excluded);

  return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
    width: size,
    height: size,
    ref: ref,
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 53 28",
    fill: "currentColor"
  }, rest), _path || (_path = /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M39,0 C46.7319865,-1.42034288e-15 53,6.2680135 53,14 C53,21.7319865 46.7319865,28 39,28 L14,28 C6.2680135,28 9.46895252e-16,21.7319865 0,14 C-9.46895252e-16,6.2680135 6.2680135,1.42034288e-15 14,0 L39,0 Z M24.734375,8.578125 L21.4375,8.578125 L21.4375,20 L23.6015625,20 L23.6015625,14.6875 C23.6015625,14.3447266 23.5859071,13.8099699 23.5545962,13.0832252 L23.5545962,13.0832252 L23.453125,11.0390625 L23.5234375,11.0390625 L26.2734375,20 L28.4921875,20 L31.4375,11.0546875 L31.5078125,11.0546875 C31.4536456,12.3005271 31.4200173,13.1316787 31.4069271,13.5481596 L31.4069271,13.5481596 L31.3913574,14.3950192 L31.390625,20 L33.6484375,20 L33.6484375,8.578125 L30.3515625,8.578125 L27.484375,17.3125 L27.4375,17.3125 L24.734375,8.578125 Z"
  })), children);
});
EmergencyMSmall.propTypes = iconPropTypes.iconPropTypes;

module.exports = EmergencyMSmall;
