/**
 * Copyright IBM Corp. 2016, 2021
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @carbon/icon-build-helpers. DO NOT EDIT.
 */
'use strict';

var iconPropTypes = require('./iconPropTypes-ca0c5320.js');
var React = require('react');
require('@carbon/icon-helpers');
require('prop-types');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var React__default = /*#__PURE__*/_interopDefaultLegacy(React);

var _path;

var _excluded = ["children", "size"];
var FavoriteOutline = /*#__PURE__*/React__default['default'].forwardRef(function FavoriteOutline(_ref, ref) {
  var children = _ref.children,
      _ref$size = _ref.size,
      size = _ref$size === void 0 ? 16 : _ref$size,
      rest = iconPropTypes._objectWithoutProperties(_ref, _excluded);

  return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
    width: size,
    height: size,
    ref: ref,
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 16 14",
    fill: "currentColor"
  }, rest), _path || (_path = /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M11.58,1a3.41,3.41,0,0,1,2.21,6l0,0,0,0L8,12.49,2.15,7a3.42,3.42,0,1,1,5-4.55L8,3.54l.81-1.12A3.43,3.43,0,0,1,11.58,1m0-1A4.39,4.39,0,0,0,8,1.84,4.41,4.41,0,1,0,1.49,7.72L8,13.87l6.46-6.08A4.42,4.42,0,0,0,11.58,0Z"
  })), children);
});
FavoriteOutline.propTypes = iconPropTypes.iconPropTypes;

module.exports = FavoriteOutline;
