/**
 * Copyright IBM Corp. 2016, 2021
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @carbon/icon-build-helpers. DO NOT EDIT.
 */
'use strict';

var iconPropTypes = require('./iconPropTypes-ca0c5320.js');
var React = require('react');
require('@carbon/icon-helpers');
require('prop-types');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var React__default = /*#__PURE__*/_interopDefaultLegacy(React);

var _path;

var _excluded = ["children", "size"];
var Filter = /*#__PURE__*/React__default['default'].forwardRef(function Filter(_ref, ref) {
  var children = _ref.children,
      _ref$size = _ref.size,
      size = _ref$size === void 0 ? 16 : _ref$size,
      rest = iconPropTypes._objectWithoutProperties(_ref, _excluded);

  return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
    width: size,
    height: size,
    ref: ref,
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 16 12",
    fill: "currentColor"
  }, rest), _path || (_path = /*#__PURE__*/React__default['default'].createElement("path", {
    fill: "none",
    d: "M8.05000906 2C8.28164422.858879839 9.29052104 0 10.5 0 11.709479 0 12.7183558.858879839 12.9499909 2L16 2 16 3 12.9499909 3C12.7183558 4.14112016 11.709479 5 10.5 5 9.29052104 5 8.28164422 4.14112016 8.05000906 3L0 3 0 2 8.05000906 2zM10.5 4C11.3284271 4 12 3.32842712 12 2.5 12 1.67157288 11.3284271 1 10.5 1 9.67157288 1 9 1.67157288 9 2.5 9 3.32842712 9.67157288 4 10.5 4zM3.05000906 9C3.28164422 7.85887984 4.29052104 7 5.5 7 6.70947896 7 7.71835578 7.85887984 7.94999094 9L16 9 16 10 7.94999094 10C7.71835578 11.1411202 6.70947896 12 5.5 12 4.29052104 12 3.28164422 11.1411202 3.05000906 10L0 10 0 9 3.05000906 9zM5.5 11C6.32842712 11 7 10.3284271 7 9.5 7 8.67157288 6.32842712 8 5.5 8 4.67157288 8 4 8.67157288 4 9.5 4 10.3284271 4.67157288 11 5.5 11z"
  })), children);
});
Filter.propTypes = iconPropTypes.iconPropTypes;

module.exports = Filter;
