/**
 * Copyright IBM Corp. 2016, 2021
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @carbon/icon-build-helpers. DO NOT EDIT.
 */
'use strict';

var iconPropTypes = require('./iconPropTypes-ca0c5320.js');
var React = require('react');
require('@carbon/icon-helpers');
require('prop-types');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var React__default = /*#__PURE__*/_interopDefaultLegacy(React);

var _path, _path2;

var _excluded = ["children", "size"];
var FilterGlyph = /*#__PURE__*/React__default['default'].forwardRef(function FilterGlyph(_ref, ref) {
  var children = _ref.children,
      _ref$size = _ref.size,
      size = _ref$size === void 0 ? 16 : _ref$size,
      rest = iconPropTypes._objectWithoutProperties(_ref, _excluded);

  return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
    width: size,
    height: size,
    ref: ref,
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 16 16",
    fill: "currentColor"
  }, rest), _path || (_path = /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M5 0C3.7 0 2.6.8 2.2 2L0 2 0 4 2.2 4C2.6 5.2 3.7 6 5 6 6.3 6 7.4 5.2 7.8 4L16 4 16 2 7.8 2C7.4.8 6.3 0 5 0L5 0 5 0zM5 4C4.4 4 4 3.6 4 3 4 2.4 4.4 2 5 2 5.6 2 6 2.4 6 3 6 3.6 5.6 4 5 4L5 4 5 4zM5 10C3.7 10 2.6 10.8 2.2 12L0 12 0 14 2.2 14C2.6 15.2 3.7 16 5 16 6.3 16 7.4 15.2 7.8 14L16 14 16 12 7.8 12C7.4 10.8 6.3 10 5 10L5 10 5 10zM5 14C4.4 14 4 13.6 4 13 4 12.4 4.4 12 5 12 5.6 12 6 12.4 6 13 6 13.6 5.6 14 5 14L5 14 5 14z"
  })), _path2 || (_path2 = /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M11,5 C9.7,5 8.6,5.8 8.2,7 L0,7 L0,9 L8.2,9 C8.6,10.2 9.7,11 11,11 C12.3,11 13.4,10.2 13.8,9 L16,9 L16,7 L13.8,7 C13.4,5.8 12.3,5 11,5 L11,5 L11,5 Z M11,9 C10.4,9 10,8.6 10,8 C10,7.4 10.4,7 11,7 C11.6,7 12,7.4 12,8 C12,8.6 11.6,9 11,9 L11,9 L11,9 Z"
  })), children);
});
FilterGlyph.propTypes = iconPropTypes.iconPropTypes;

module.exports = FilterGlyph;
