/**
 * Copyright IBM Corp. 2016, 2021
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @carbon/icon-build-helpers. DO NOT EDIT.
 */
'use strict';

var iconPropTypes = require('./iconPropTypes-ca0c5320.js');
var React = require('react');
require('@carbon/icon-helpers');
require('prop-types');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var React__default = /*#__PURE__*/_interopDefaultLegacy(React);

var _path;

var _excluded = ["children", "size"];
var Folder = /*#__PURE__*/React__default['default'].forwardRef(function Folder(_ref, ref) {
  var children = _ref.children,
      _ref$size = _ref.size,
      size = _ref$size === void 0 ? 16 : _ref$size,
      rest = iconPropTypes._objectWithoutProperties(_ref, _excluded);

  return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
    width: size,
    height: size,
    ref: ref,
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 14 12",
    fill: "currentColor"
  }, rest), _path || (_path = /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M13,12 L1,12 C0.44771525,12 -1.88737914e-15,11.5522847 0,11 L1.11022302e-16,1.00101221 C0.00111897013,0.446706218 0.449738751,-0.000102669643 1.00202237,0.00101425549 L3.29494134,0.00565139976 C3.55893031,0.00618528472 3.81199865,0.111084241 3.99895077,0.297469235 L5.70666199,2 L13,2 C13.5522847,2 14,2.44771525 14,3 L14,11 C14,11.5522847 13.5522847,12 13,12 Z M13,3 L5.70666199,3 C5.44197186,3 5.18807847,2.89505977 5.00063018,2.70818012 L3.29291896,1.00564935 L1,1.00101221 L1,11 L13,11 L13,3 Z"
  })), children);
});
Folder.propTypes = iconPropTypes.iconPropTypes;

module.exports = Folder;
