/**
 * Copyright IBM Corp. 2016, 2021
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @carbon/icon-build-helpers. DO NOT EDIT.
 */
'use strict';

var iconPropTypes = require('./iconPropTypes-ca0c5320.js');
var React = require('react');
require('@carbon/icon-helpers');
require('prop-types');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var React__default = /*#__PURE__*/_interopDefaultLegacy(React);

var _path, _path2;

var _excluded = ["children", "size"];
var Forum = /*#__PURE__*/React__default['default'].forwardRef(function Forum(_ref, ref) {
  var children = _ref.children,
      _ref$size = _ref.size,
      size = _ref$size === void 0 ? 16 : _ref$size,
      rest = iconPropTypes._objectWithoutProperties(_ref, _excluded);

  return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
    width: size,
    height: size,
    ref: ref,
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 16 15",
    fill: "currentColor"
  }, rest), _path || (_path = /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M11.7,12l-3,3L8,14.3l3.3-3.3h3.2c0.3,0,0.5-0.2,0.5-0.5v-6C15,4.2,14.8,4,14.5,4h-10C4.2,4,4,4.2,4,4.5v6 C4,10.8,4.2,11,4.5,11L8,11l0,1l-3.5,0C3.7,12,3,11.3,3,10.5l0-6C3,3.7,3.7,3,4.5,3h10C15.3,3,16,3.7,16,4.5v6 c0,0.8-0.7,1.5-1.5,1.5H11.7z"
  })), _path2 || (_path2 = /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M1,8L0,8l0-6.5C0,0.7,0.7,0,1.5,0H8l0,1L1.5,1C1.2,1,1,1.2,1,1.5L1,8z"
  })), children);
});
Forum.propTypes = iconPropTypes.iconPropTypes;

module.exports = Forum;
