/**
 * Copyright IBM Corp. 2016, 2021
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @carbon/icon-build-helpers. DO NOT EDIT.
 */
'use strict';

var iconPropTypes = require('./iconPropTypes-ca0c5320.js');
var React = require('react');
require('@carbon/icon-helpers');
require('prop-types');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var React__default = /*#__PURE__*/_interopDefaultLegacy(React);

var _g;

var _excluded = ["children", "size"];
var HeaderDocs = /*#__PURE__*/React__default['default'].forwardRef(function HeaderDocs(_ref, ref) {
  var children = _ref.children,
      _ref$size = _ref.size,
      size = _ref$size === void 0 ? 16 : _ref$size,
      rest = iconPropTypes._objectWithoutProperties(_ref, _excluded);

  return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
    width: size,
    height: size,
    ref: ref,
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 20 20",
    fill: "currentColor"
  }, rest), _g || (_g = /*#__PURE__*/React__default['default'].createElement("g", {
    fill: "none",
    "fill-rule": "evenodd"
  }, /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M5,2 L12,2 L16,6 L16,17 C16,17.5522847 15.5522847,18 15,18 L5,18 C4.44771525,18 4,17.5522847 4,17 L4,3 C4,2.44771525 4.44771525,2 5,2 Z M11.5857864,3 L5,3 L5,17 L15,17 L15,6.41421356 L11.5857864,3 Z M14.9968895,5.99688951 L16,7 L12.037055,6.98773046 C11.4899019,6.98603644 11.0457035,6.5449187 11.0402016,5.99779069 L11,2 L12.0102092,3.01020917 L12.040151,5.98773525 L14.9968895,5.99688951 Z M16,7 L12.037055,6.98773046 C11.4899019,6.98603644 11.0457035,6.5449187 11.0402016,5.99779069 L11,2 L12.0102092,3.01020917 L12.040151,5.98773525 L14.9968895,5.99688951 L16,7 Z"
  }), /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M7 11H13V12H7zM7 14H13V15H7z"
  }))), children);
});
HeaderDocs.propTypes = iconPropTypes.iconPropTypes;

module.exports = HeaderDocs;
