/**
 * Copyright IBM Corp. 2016, 2021
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @carbon/icon-build-helpers. DO NOT EDIT.
 */
'use strict';

var iconPropTypes = require('./iconPropTypes-ca0c5320.js');
var React = require('react');
require('@carbon/icon-helpers');
require('prop-types');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var React__default = /*#__PURE__*/_interopDefaultLegacy(React);

var _path, _path2;

var _excluded = ["children", "size"];
var HeaderAvatar = /*#__PURE__*/React__default['default'].forwardRef(function HeaderAvatar(_ref, ref) {
  var children = _ref.children,
      _ref$size = _ref.size,
      size = _ref$size === void 0 ? 16 : _ref$size,
      rest = iconPropTypes._objectWithoutProperties(_ref, _excluded);

  return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
    width: size,
    height: size,
    ref: ref,
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 20 20",
    fill: "currentColor"
  }, rest), _path || (_path = /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M6,15.7453107 C7.13383348,16.5361852 8.51275186,17 10,17 C11.4872481,17 12.8661665,16.5361852 14,15.7453107 L14,15.5 C14,14.1192881 12.8807119,13 11.5,13 L8.5,13 C7.11928813,13 6,14.1192881 6,15.5 L6,15.7453107 Z M5.0440001,14.9434872 C5.3105825,13.2749777 6.75639775,12 8.5,12 L11.5,12 C13.2436022,12 14.6894175,13.2749777 14.9559999,14.9434872 C16.219076,13.6772341 17,11.9298143 17,10 C17,6.13400675 13.8659932,3 10,3 C6.13400675,3 3,6.13400675 3,10 C3,11.9298143 3.78092405,13.6772341 5.0440001,14.9434872 Z M10,18 C5.581722,18 2,14.418278 2,10 C2,5.581722 5.581722,2 10,2 C14.418278,2 18,5.581722 18,10 C18,14.418278 14.418278,18 10,18 Z"
  })), _path2 || (_path2 = /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M10,10 C11.1045695,10 12,9.1045695 12,8 C12,6.8954305 11.1045695,6 10,6 C8.8954305,6 8,6.8954305 8,8 C8,9.1045695 8.8954305,10 10,10 Z M10,11 C8.34314575,11 7,9.65685425 7,8 C7,6.34314575 8.34314575,5 10,5 C11.6568542,5 13,6.34314575 13,8 C13,9.65685425 11.6568542,11 10,11 Z"
  })), children);
});
HeaderAvatar.propTypes = iconPropTypes.iconPropTypes;

module.exports = HeaderAvatar;
