/**
 * Copyright IBM Corp. 2016, 2021
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @carbon/icon-build-helpers. DO NOT EDIT.
 */
'use strict';

var iconPropTypes = require('./iconPropTypes-ca0c5320.js');
var React = require('react');
require('@carbon/icon-helpers');
require('prop-types');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var React__default = /*#__PURE__*/_interopDefaultLegacy(React);

var _g;

var _excluded = ["children", "size"];
var HelpOutline = /*#__PURE__*/React__default['default'].forwardRef(function HelpOutline(_ref, ref) {
  var children = _ref.children,
      _ref$size = _ref.size,
      size = _ref$size === void 0 ? 16 : _ref$size,
      rest = iconPropTypes._objectWithoutProperties(_ref, _excluded);

  return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
    width: size,
    height: size,
    ref: ref,
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 16 16",
    fill: "currentColor"
  }, rest), _g || (_g = /*#__PURE__*/React__default['default'].createElement("g", {
    fill: "none",
    "fill-rule": "evenodd"
  }, /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M8,14.5 C11.5898509,14.5 14.5,11.5898509 14.5,8 C14.5,4.41014913 11.5898509,1.5 8,1.5 C4.41014913,1.5 1.5,4.41014913 1.5,8 C1.5,11.5898509 4.41014913,14.5 8,14.5 Z M8,16 C3.581722,16 0,12.418278 0,8 C0,3.581722 3.581722,0 8,0 C12.418278,0 16,3.581722 16,8 C16,12.418278 12.418278,16 8,16 Z"
  }), /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M8.75,9.36397276 L8.75,10.5 L7.25,10.5 L7.25,7.86322021 L8.75,7.86322021 C9.64557754,7.82533775 10.3600001,7.08729501 10.3600001,6.18238993 C10.3600001,5.25323163 9.60676851,4.5 8.67761021,4.5 L7.68238993,4.5 C6.75323163,4.5 6,5.25323163 6,6.18238993 L4.5,6.18238993 C4.5,4.4248045 5.9248045,3 7.68238993,3 L8.67761021,3 C10.4351956,3 11.8600001,4.4248045 11.8600001,6.18238993 C11.8600001,7.91578141 10.4741518,9.32549067 8.75,9.36397276 Z"
  }), /*#__PURE__*/React__default['default'].createElement("circle", {
    cx: "8",
    cy: "13",
    r: "1"
  }))), children);
});
HelpOutline.propTypes = iconPropTypes.iconPropTypes;

module.exports = HelpOutline;
