/**
 * Copyright IBM Corp. 2016, 2021
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @carbon/icon-build-helpers. DO NOT EDIT.
 */
'use strict';

var iconPropTypes = require('./iconPropTypes-ca0c5320.js');
var React = require('react');
require('@carbon/icon-helpers');
require('prop-types');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var React__default = /*#__PURE__*/_interopDefaultLegacy(React);

var _path;

var _excluded = ["children", "size"];
var Home = /*#__PURE__*/React__default['default'].forwardRef(function Home(_ref, ref) {
  var children = _ref.children,
      _ref$size = _ref.size,
      size = _ref$size === void 0 ? 16 : _ref$size,
      rest = iconPropTypes._objectWithoutProperties(_ref, _excluded);

  return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
    width: size,
    height: size,
    ref: ref,
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 16 16",
    fill: "currentColor"
  }, rest), _path || (_path = /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M13.555297,7.51524629 L13.555297,11.3566402 C13.555297,11.7131688 13.2580443,12 12.8885621,12 L9.66600975,12 C9.48265764,12 9.33264227,11.8552441 9.33264227,11.6783201 L9.33264227,8.67597453 C9.33264227,8.4990506 9.18262691,8.35429465 8.99927479,8.35429465 L6.99906992,8.35429465 C6.81571781,8.35429465 6.66570244,8.4990506 6.66570244,8.67597453 L6.66570244,11.6783201 C6.66570244,11.8552441 6.51568708,12 6.33233496,12 L3.10978266,12 C2.74030038,12 2.44304771,11.7131688 2.44304771,11.3566402 L2.44304771,7.51524629 C2.44304771,7.41874232 2.4874967,7.32759969 2.56528245,7.26594438 L7.78803962,3.11627387 C7.91027436,3.01976991 8.08807035,3.01976991 8.21308316,3.11627387 L13.4358403,7.26594438 C13.510848,7.32759969 13.555297,7.41874232 13.555297,7.51524629 Z M15.8777571,5.88272088 L13.555297,4.03574221 L13.555297,0.323020217 C13.555297,0.146096281 13.4052816,0.00134033285 13.2219295,0.00134033285 L11.6662146,0.00134033285 C11.4828625,0.00134033285 11.3328471,0.146096281 11.3328471,0.323020217 L11.3328471,2.26918351 L8.84648137,0.293532894 C8.35476434,-0.097844298 7.64358038,-0.097844298 7.15186335,0.293532894 L0.120587602,5.88272088 C-0.0210935766,5.99530884 -0.0405400128,6.19903943 0.0761386048,6.33575338 L0.784544498,7.16675975 C0.901223116,7.3034737 1.11235585,7.32223836 1.25403703,7.2096504 L7.78803962,2.01720094 C7.91027436,1.92069697 8.08807035,1.92069697 8.21308316,2.01720094 L14.7470857,7.2096504 C14.8887669,7.32223836 15.0998997,7.3034737 15.2165783,7.16675975 L15.9249842,6.33575338 C16.0416628,6.19635876 16.0194383,5.99530884 15.8777571,5.88272088 Z",
    transform: "translate(0 2)"
  })), children);
});
Home.propTypes = iconPropTypes.iconPropTypes;

module.exports = Home;
