/**
 * Copyright IBM Corp. 2016, 2021
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @carbon/icon-build-helpers. DO NOT EDIT.
 */
'use strict';

var iconPropTypes = require('./iconPropTypes-ca0c5320.js');
var React = require('react');
require('@carbon/icon-helpers');
require('prop-types');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var React__default = /*#__PURE__*/_interopDefaultLegacy(React);

var _path;

var _excluded = ["children", "size"];
var Maximize = /*#__PURE__*/React__default['default'].forwardRef(function Maximize(_ref, ref) {
  var children = _ref.children,
      _ref$size = _ref.size,
      size = _ref$size === void 0 ? 16 : _ref$size,
      rest = iconPropTypes._objectWithoutProperties(_ref, _excluded);

  return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
    width: size,
    height: size,
    ref: ref,
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 16 16",
    fill: "currentColor"
  }, rest), _path || (_path = /*#__PURE__*/React__default['default'].createElement("path", {
    fill: "none",
    d: "M1.70927162 15L3.99999988 15 3.99999988 16 .00273318979 16 8.8817842e-16 12.0003417.999999767 11.9996583 1.00156727 14.2934904 5.29788753 9.99717014 6.00499451 10.7042771 1.70927162 15zM14.9984062 1.66788979L10.7268088 5.98533834 10.0159374 5.28201635 14.2524789 1 12 1 12-2.10942375e-15 15.9972667-2.10942375e-15 15.9999999 3.99965832 15.0000001 4.00034168 14.9984062 1.66788979z"
  })), children);
});
Maximize.propTypes = iconPropTypes.iconPropTypes;

module.exports = Maximize;
