/**
 * Copyright IBM Corp. 2016, 2021
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @carbon/icon-build-helpers. DO NOT EDIT.
 */
'use strict';

var iconPropTypes = require('./iconPropTypes-ca0c5320.js');
var React = require('react');
require('@carbon/icon-helpers');
require('prop-types');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var React__default = /*#__PURE__*/_interopDefaultLegacy(React);

var _path;

var _excluded = ["children", "size"];
var Network = /*#__PURE__*/React__default['default'].forwardRef(function Network(_ref, ref) {
  var children = _ref.children,
      _ref$size = _ref.size,
      size = _ref$size === void 0 ? 16 : _ref$size,
      rest = iconPropTypes._objectWithoutProperties(_ref, _excluded);

  return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
    width: size,
    height: size,
    ref: ref,
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 23 24",
    fill: "currentColor"
  }, rest), _path || (_path = /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M20.5,18 L20.5,12 L11.5,12 L11.5,5.9 C12.9,5.7 14,4.5 14,3 C14,1.3 12.7,0 11,0 C9.3,0 8,1.3 8,3 C8,4.5 9.1,5.7 10.5,5.9 L10.5,12 L2.5,12 L2.5,18.1 C1.1,18.4 0,19.6 0,21 C0,22.7 1.3,24 3,24 C4.7,24 6,22.7 6,21 C6,19.5 4.9,18.3 3.5,18.1 L3.5,13 L19.5,13 L19.5,18.1 C18.1,18.3 17,19.6 17,21 C17,22.7 18.3,24 20,24 C21.7,24 23,22.7 23,21 C23,19.5 22,18.2 20.5,18 L20.5,18 Z M9,3 C9,1.9 9.9,1 11,1 C12.1,1 13,1.9 13,3 C13,4.1 12.1,5 11,5 C9.9,5 9,4.1 9,3 L9,3 Z M5,21 C5,22.1 4.1,23 3,23 C1.9,23 1,22.1 1,21 C1,19.9 1.9,19 3,19 C4.1,19 5,19.9 5,21 L5,21 Z M20,23 C18.9,23 18,22.1 18,21 C18,19.9 18.9,19 20,19 C21.1,19 22,19.9 22,21 C22,22.1 21.1,23 20,23 L20,23 Z"
  })), children);
});
Network.propTypes = iconPropTypes.iconPropTypes;

module.exports = Network;
