/**
 * Copyright IBM Corp. 2016, 2021
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @carbon/icon-build-helpers. DO NOT EDIT.
 */
'use strict';

var iconPropTypes = require('./iconPropTypes-ca0c5320.js');
var React = require('react');
require('@carbon/icon-helpers');
require('prop-types');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var React__default = /*#__PURE__*/_interopDefaultLegacy(React);

var _g;

var _excluded = ["children", "size"];
var Power = /*#__PURE__*/React__default['default'].forwardRef(function Power(_ref, ref) {
  var children = _ref.children,
      _ref$size = _ref.size,
      size = _ref$size === void 0 ? 16 : _ref$size,
      rest = iconPropTypes._objectWithoutProperties(_ref, _excluded);

  return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
    width: size,
    height: size,
    ref: ref,
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 15 16",
    fill: "currentColor"
  }, rest), _g || (_g = /*#__PURE__*/React__default['default'].createElement("g", {
    fill: "none",
    "fill-rule": "evenodd"
  }, /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M7 0H8V8H7z"
  }), /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M0.469115276,11.1182797 C0.165782692,10.303584 0,9.42193492 0,8.50156518 C0,4.35942955 3.35786438,1.00156518 7.5,1.00156518 C11.6421356,1.00156518 15,4.35942955 15,8.50156518 C15,12.6437008 11.6421356,16.0015652 7.5,16.0015652 C6.62874378,16.0015652 5.51050043,15.7301333 5.0277752,15.5582881 L5.36314786,14.6162026 C5.90052942,14.8075048 6.8754263,15.0015652 7.5,15.0015652 C11.0898509,15.0015652 14,12.091416 14,8.50156518 C14,4.9117143 11.0898509,2.00156518 7.5,2.00156518 C3.91014913,2.00156518 1,4.9117143 1,8.50156518 C1,9.28644506 1.13870817,10.0507437 1.40626567,10.7693541 L0.469115276,11.1182797 Z",
    transform: "rotate(136 7.5 8.502)"
  }))), children);
});
Power.propTypes = iconPropTypes.iconPropTypes;

module.exports = Power;
