/**
 * Copyright IBM Corp. 2016, 2021
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @carbon/icon-build-helpers. DO NOT EDIT.
 */
'use strict';

var iconPropTypes = require('./iconPropTypes-ca0c5320.js');
var React = require('react');
require('@carbon/icon-helpers');
require('prop-types');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var React__default = /*#__PURE__*/_interopDefaultLegacy(React);

var _path;

var _excluded = ["children", "size"];
var Restart = /*#__PURE__*/React__default['default'].forwardRef(function Restart(_ref, ref) {
  var children = _ref.children,
      _ref$size = _ref.size,
      size = _ref$size === void 0 ? 16 : _ref$size,
      rest = iconPropTypes._objectWithoutProperties(_ref, _excluded);

  return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
    width: size,
    height: size,
    ref: ref,
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 13 16",
    fill: "currentColor"
  }, rest), _path || (_path = /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M10.9476177,3 L8.54213345,0.726810516 L9.22897148,5.4904749e-14 L13,3.56363279 L9.22800918,7.10779198 L8.5432543,6.37901853 L11.0752049,4 L6.5,4 C3.46243388,4 1,6.46243388 1,9.5 C1,12.5375661 3.46243388,15 6.5,15 C9.53756612,15 12,12.5375661 12,9.5 L13,9.5 C13,13.0898509 10.0898509,16 6.5,16 C2.91014913,16 0,13.0898509 0,9.5 C-1.77635684e-15,5.91014913 2.91014913,3 6.5,3 L10.9476177,3 Z"
  })), children);
});
Restart.propTypes = iconPropTypes.iconPropTypes;

module.exports = Restart;
