/**
 * Copyright IBM Corp. 2016, 2021
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @carbon/icon-build-helpers. DO NOT EDIT.
 */
'use strict';

var iconPropTypes = require('./iconPropTypes-ca0c5320.js');
var React = require('react');
require('@carbon/icon-helpers');
require('prop-types');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var React__default = /*#__PURE__*/_interopDefaultLegacy(React);

var _path;

var _excluded = ["children", "size"];
var Unlock = /*#__PURE__*/React__default['default'].forwardRef(function Unlock(_ref, ref) {
  var children = _ref.children,
      _ref$size = _ref.size,
      size = _ref$size === void 0 ? 16 : _ref$size,
      rest = iconPropTypes._objectWithoutProperties(_ref, _excluded);

  return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
    width: size,
    height: size,
    ref: ref,
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 12 16",
    fill: "currentColor"
  }, rest), _path || (_path = /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M2.5,7 L2.5,3.5 C2.5,1.56700338 4.06700338,3.88578059e-16 6,0 C7.93299662,-3.23815049e-16 9.5,1.56700338 9.5,3.5 L9.5,4 L8.5,4 L8.5,3.5 C8.5,2.11928813 7.38071187,1 6,1 C4.61928813,1 3.5,2.11928813 3.5,3.5 L3.5,7 L10.5,7 C11.3284271,7 12,7.67157288 12,8.5 L12,14.5 C12,15.3284271 11.3284271,16 10.5,16 L1.5,16 C0.671572875,16 0,15.3284271 0,14.5 L0,8.5 C0,7.67157288 0.671572875,7 1.5,7 L2.5,7 Z M1.5,8 C1.22385763,8 1,8.22385763 1,8.5 L1,14.5 C1,14.7761424 1.22385763,15 1.5,15 L10.5,15 C10.7761424,15 11,14.7761424 11,14.5 L11,8.5 C11,8.22385763 10.7761424,8 10.5,8 L1.5,8 Z"
  })), children);
});
Unlock.propTypes = iconPropTypes.iconPropTypes;

module.exports = Unlock;
