/**
 * Copyright IBM Corp. 2016, 2021
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @carbon/icon-build-helpers. DO NOT EDIT.
 */
'use strict';

var iconPropTypes = require('./iconPropTypes-ca0c5320.js');
var React = require('react');
require('@carbon/icon-helpers');
require('prop-types');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var React__default = /*#__PURE__*/_interopDefaultLegacy(React);

var _g;

var _excluded = ["children", "size"];
var WarningOutline = /*#__PURE__*/React__default['default'].forwardRef(function WarningOutline(_ref, ref) {
  var children = _ref.children,
      _ref$size = _ref.size,
      size = _ref$size === void 0 ? 16 : _ref$size,
      rest = iconPropTypes._objectWithoutProperties(_ref, _excluded);

  return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
    width: size,
    height: size,
    ref: ref,
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 16 16",
    fill: "currentColor"
  }, rest), _g || (_g = /*#__PURE__*/React__default['default'].createElement("g", {
    fill: "none",
    "fill-rule": "evenodd"
  }, /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M7.25 6H8.75V11H7.25z"
  }), /*#__PURE__*/React__default['default'].createElement("circle", {
    cx: "8",
    cy: "12.75",
    r: "1"
  }), /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M0.75,16 C0.192463484,16 -0.170158303,15.4132656 0.0791796068,14.9145898 L7.32917961,0.414589803 C7.60557281,-0.138196601 8.39442719,-0.138196601 8.67082039,0.414589803 L15.9208204,14.9145898 C16.1701583,15.4132656 15.8075365,16 15.25,16 L0.75,16 Z M1.96352549,14.5 L14.0364745,14.5 L8,2.42705098 L1.96352549,14.5 Z"
  }))), children);
});
WarningOutline.propTypes = iconPropTypes.iconPropTypes;

module.exports = WarningOutline;
