/**
 * Copyright IBM Corp. 2016, 2021
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @carbon/icon-build-helpers. DO NOT EDIT.
 */
'use strict';

var iconPropTypes = require('./iconPropTypes-ca0c5320.js');
var React = require('react');
require('@carbon/icon-helpers');
require('prop-types');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var React__default = /*#__PURE__*/_interopDefaultLegacy(React);

var _path, _path2, _circle;

var _excluded = ["children", "size"];
var Warning = /*#__PURE__*/React__default['default'].forwardRef(function Warning(_ref, ref) {
  var children = _ref.children,
      _ref$size = _ref.size,
      size = _ref$size === void 0 ? 16 : _ref$size,
      rest = iconPropTypes._objectWithoutProperties(_ref, _excluded);

  return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
    width: size,
    height: size,
    ref: ref,
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 24 21",
    fill: "currentColor"
  }, rest), _path || (_path = /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M12,0 L0,21 L24,21 L12,0 L12,0 Z M12,3 L21,19 L3,19 L12,3 L12,3 Z"
  })), _path2 || (_path2 = /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M11.2 8.4L11.2 10 11.6 14 12.4 14 12.8 10 12.8 8.4z"
  })), _circle || (_circle = /*#__PURE__*/React__default['default'].createElement("circle", {
    cx: "12",
    cy: "16",
    r: ".8"
  })), children);
});
Warning.propTypes = iconPropTypes.iconPropTypes;

module.exports = Warning;
