/**
 * Copyright IBM Corp. 2016, 2021
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @carbon/icon-build-helpers. DO NOT EDIT.
 */
'use strict';

var iconPropTypes = require('./iconPropTypes-ca0c5320.js');
var React = require('react');
require('@carbon/icon-helpers');
require('prop-types');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var React__default = /*#__PURE__*/_interopDefaultLegacy(React);

var _g;

var _excluded = ["children", "size"];
var WfpHumFoodAssistanceForAssetsNeg = /*#__PURE__*/React__default['default'].forwardRef(function WfpHumFoodAssistanceForAssetsNeg(_ref, ref) {
  var children = _ref.children,
      _ref$size = _ref.size,
      size = _ref$size === void 0 ? 16 : _ref$size,
      rest = iconPropTypes._objectWithoutProperties(_ref, _excluded);

  return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
    width: size,
    height: size,
    ref: ref,
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 57 57",
    fill: "currentColor"
  }, rest), _g || (_g = /*#__PURE__*/React__default['default'].createElement("g", {
    "fill-rule": "evenodd"
  }, /*#__PURE__*/React__default['default'].createElement("path", {
    "fill-rule": "nonzero",
    d: "M54.4,0 L2.4,0 C1.1,0 0,1.1 0,2.4 L0,4.1 L0,52 L0,53.7 C0,55 1.1,56.1 2.4,56.1 L54.4,56.1 C55.7,56.1 56.8,55 56.8,53.7 L56.8,52 L56.8,4.1 L56.8,2.4 C56.8,1.1 55.7,0 54.4,0 Z M20.8,24.2 L16.2,24.2 L16.2,26.9 L20.4,26.9 L20.4,29.9 L16.2,29.9 L16.2,35.2 L12.5,35.2 L12.5,21.2 L20.8,21.2 L20.8,24.2 Z M31,29.9 L26.8,29.9 L26.8,35.2 L23.1,35.2 L23.1,21.2 L31.4,21.2 L31.4,24.2 L26.8,24.2 L26.8,26.9 L31,26.9 L31,29.9 Z M41.5,35.1 L40.8,32.5 L36.2,32.5 L35.5,35.1 L31.3,35.1 L35.9,21 L41,21 L45.6,35.1 L41.5,35.1 Z"
  }), /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M38.9,25.1 C38.7,24.3 38.6,23.7 38.5,23.4 C38.4,23.7 38.3,24.3 38.2,25 C38,25.7 37.7,27.2 37.1,29.4 L40.1,29.4 L39.5,27.1 C39.3,26.6 39.1,25.9 38.9,25.1 Z"
  }))), children);
});
WfpHumFoodAssistanceForAssetsNeg.propTypes = iconPropTypes.iconPropTypes;

module.exports = WfpHumFoodAssistanceForAssetsNeg;
