/**
 * Copyright IBM Corp. 2016, 2021
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @carbon/icon-build-helpers. DO NOT EDIT.
 */
'use strict';

var iconPropTypes = require('./iconPropTypes-ca0c5320.js');
var React = require('react');
require('@carbon/icon-helpers');
require('prop-types');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var React__default = /*#__PURE__*/_interopDefaultLegacy(React);

var _g;

var _excluded = ["children", "size"];
var WfpHumEmergencyResponseNeg = /*#__PURE__*/React__default['default'].forwardRef(function WfpHumEmergencyResponseNeg(_ref, ref) {
  var children = _ref.children,
      _ref$size = _ref.size,
      size = _ref$size === void 0 ? 16 : _ref$size,
      rest = iconPropTypes._objectWithoutProperties(_ref, _excluded);

  return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
    width: size,
    height: size,
    ref: ref,
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 57 57",
    fill: "currentColor"
  }, rest), _g || (_g = /*#__PURE__*/React__default['default'].createElement("g", {
    "fill-rule": "evenodd"
  }, /*#__PURE__*/React__default['default'].createElement("path", {
    "fill-rule": "nonzero",
    d: "M34.8,39.8 L32.8,39.8 L32.8,45.6 L34.4,45.6 L34.4,43.7 L34.8,43.7 C35.5,43.7 36.1,43.5 36.4,43.2 C36.8,42.8 37,42.3 37,41.7 C37,41.1 36.8,40.6 36.4,40.3 C36.1,40 35.5,39.8 34.8,39.8 Z M35.2,42.2 C35.1,42.3 34.9,42.4 34.6,42.4 L34.3,42.4 L34.3,41.1 L34.7,41.1 C35.1,41.1 35.4,41.3 35.4,41.7 C35.4,41.9 35.3,42.1 35.2,42.2 Z"
  }), /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M28.7 45.7L30.3 45.7 30.3 43.5 32 43.5 32 42.2 30.3 42.2 30.3 41.1 32.2 41.1 32.2 39.8 28.7 39.8zM25.9 42.7C25.7 43.4 25.6 43.9 25.6 44.2 25.6 44 25.5 43.6 25.4 43.2 25.3 42.7 25.2 42.3 25.1 42L24.6 39.8 23.1 39.8 22.7 42C22.6 42.3 22.5 42.7 22.4 43.2 22.3 43.7 22.2 44 22.2 44.3 22.1 43.9 22 43.4 21.9 42.8L21.3 39.9 19.8 39.9 21.2 45.7 23.1 45.7C23.4 44.2 23.6 43.3 23.7 43.1 23.7 42.9 23.8 42.6 23.8 42.4 23.8 42.1 23.9 41.9 23.9 41.8 23.9 42 24 42.3 24 42.6 24.1 42.9 24.1 43.1 24.1 43.2L24.7 45.7 26.6 45.7 28 39.9 26.5 39.9 25.9 42.7z"
  }), /*#__PURE__*/React__default['default'].createElement("path", {
    "fill-rule": "nonzero",
    d: "M54.4,0 L2.4,0 C1.1,0 0,1.1 0,2.4 L0,4.1 L0,52 L0,53.7 C0,55 1.1,56.1 2.4,56.1 L54.4,56.1 C55.7,56.1 56.8,55 56.8,53.7 L56.8,52 L56.8,4.1 L56.8,2.4 C56.8,1.1 55.7,0 54.4,0 Z M39.6,48.6 C39.6,49.1 39.2,49.4 38.8,49.4 L18,49.4 C17.5,49.4 17.2,49 17.2,48.6 L17.2,36.8 C17.2,36.3 17.6,36 18,36 L38.8,36 C39.3,36 39.6,36.4 39.6,36.8 L39.6,48.6 Z M39.8,23.8 L29.3,33.9 C29.3,33.9 29.3,33.9 29.3,33.9 C29.2,34 29.1,34.1 28.9,34.1 C28.9,34.1 28.9,34.1 28.9,34.1 C28.8,34.2 28.6,34.2 28.5,34.2 C28.3,34.2 28.2,34.2 28.1,34.1 C28.1,34.1 28.1,34.1 28.1,34.1 C28,34 27.8,34 27.7,33.9 C27.7,33.9 27.7,33.9 27.7,33.9 L17,23.8 C16.5,23.3 16.5,22.5 17,22 C17.5,21.5 18.3,21.5 18.8,22 L28.5,31.3 L38,22 C38.5,21.5 39.3,21.5 39.8,22 C40.3,22.5 40.3,23.3 39.8,23.8 Z M14,20 C14,12 20.5,5.6 28.4,5.6 C36.3,5.6 42.7,12 42.7,19.9 L14,19.9 L14,20 Z"
  }))), children);
});
WfpHumEmergencyResponseNeg.propTypes = iconPropTypes.iconPropTypes;

module.exports = WfpHumEmergencyResponseNeg;
