/**
 * Copyright IBM Corp. 2016, 2021
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @carbon/icon-build-helpers. DO NOT EDIT.
 */
'use strict';

var iconPropTypes = require('./iconPropTypes-ca0c5320.js');
var React = require('react');
require('@carbon/icon-helpers');
require('prop-types');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var React__default = /*#__PURE__*/_interopDefaultLegacy(React);

var _path;

var _excluded = ["children", "size"];
var WfpHumReliefGoodsPos = /*#__PURE__*/React__default['default'].forwardRef(function WfpHumReliefGoodsPos(_ref, ref) {
  var children = _ref.children,
      _ref$size = _ref.size,
      size = _ref$size === void 0 ? 16 : _ref$size,
      rest = iconPropTypes._objectWithoutProperties(_ref, _excluded);

  return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
    width: size,
    height: size,
    ref: ref,
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 29 42",
    fill: "currentColor"
  }, rest), _path || (_path = /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M19.4,40.5 C19.4,41 19,41.3 18.6,41.3 L10.2,41.3 C9.7,41.3 9.4,40.9 9.4,40.5 L9.4,32 C9.4,31.5 9.8,31.2 10.2,31.2 L18.6,31.2 C19.1,31.2 19.4,31.6 19.4,32 L19.4,40.5 Z M25.8,19 L15.3,29.1 C15.3,29.1 15.3,29.1 15.3,29.1 C15.2,29.2 15.1,29.3 14.9,29.3 C14.9,29.3 14.9,29.3 14.9,29.3 C14.8,29.4 14.6,29.4 14.5,29.4 C14.3,29.4 14.2,29.4 14.1,29.3 C14.1,29.3 14.1,29.3 14.1,29.3 C14,29.2 13.8,29.2 13.7,29.1 C13.7,29.1 13.7,29.1 13.7,29.1 L3,19 C2.5,18.5 2.5,17.7 3,17.2 C3.5,16.7 4.3,16.7 4.8,17.2 L14.5,26.5 L24.2,17.2 C24.7,16.7 25.5,16.7 26,17.2 C26.3,17.7 26.3,18.5 25.8,19 Z M0,15.2 C0,7.3 6.4,0.9 14.3,0.9 C22.2,0.9 28.6,7.3 28.6,15.2 L0,15.2 Z"
  })), children);
});
WfpHumReliefGoodsPos.propTypes = iconPropTypes.iconPropTypes;

module.exports = WfpHumReliefGoodsPos;
