/**
 * Copyright IBM Corp. 2016, 2021
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @carbon/icon-build-helpers. DO NOT EDIT.
 */
'use strict';

var iconPropTypes = require('./iconPropTypes-ca0c5320.js');
var React = require('react');
require('@carbon/icon-helpers');
require('prop-types');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var React__default = /*#__PURE__*/_interopDefaultLegacy(React);

var _g;

var _excluded = ["children", "size"];
var WfpHumSecurityNeg = /*#__PURE__*/React__default['default'].forwardRef(function WfpHumSecurityNeg(_ref, ref) {
  var children = _ref.children,
      _ref$size = _ref.size,
      size = _ref$size === void 0 ? 16 : _ref$size,
      rest = iconPropTypes._objectWithoutProperties(_ref, _excluded);

  return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
    width: size,
    height: size,
    ref: ref,
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 57 57",
    fill: "currentColor"
  }, rest), _g || (_g = /*#__PURE__*/React__default['default'].createElement("g", {
    "fill-rule": "evenodd"
  }, /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M31.3,22.4 C30.4,22.4 29.6,22.7 28.9,23.4 L28.2,24 L27.5,23.4 C26.8,22.8 26,22.4 25.1,22.4 C24.3,22.4 23.4,22.7 22.8,23.3 C21.4,24.6 21.5,26.9 22.8,28.2 L23.4,28.8 L27.9,33.5 C28.1,33.7 28.3,33.7 28.5,33.5 L33,28.8 L33.6,28.2 C35,26.9 35,24.6 33.6,23.3 C33,22.8 32.1,22.4 31.3,22.4 Z"
  }), /*#__PURE__*/React__default['default'].createElement("path", {
    "fill-rule": "nonzero",
    d: "M54.4,0 L2.4,0 C1.1,0 0,1.1 0,2.4 L0,4.1 L0,52 L0,53.7 C0,55 1.1,56.1 2.4,56.1 L54.4,56.1 C55.7,56.1 56.8,55 56.8,53.7 L56.8,52 L56.8,4.1 L56.8,2.4 C56.8,1.1 55.7,0 54.4,0 Z M41,30.6 C41,38.5 35.2,44.9 28.2,44.9 C21.2,44.9 15.4,38.5 15.4,30.6 L15.4,14.4 C15.4,14 15.7,13.7 16,13.6 L28,11.2 C28.1,11.2 28.2,11.2 28.3,11.2 L40.3,13.6 C40.7,13.7 40.9,14 40.9,14.4 L40.9,30.6 L41,30.6 Z"
  }))), children);
});
WfpHumSecurityNeg.propTypes = iconPropTypes.iconPropTypes;

module.exports = WfpHumSecurityNeg;
