/**
 * Copyright IBM Corp. 2016, 2021
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @carbon/icon-build-helpers. DO NOT EDIT.
 */
'use strict';

var iconPropTypes = require('./iconPropTypes-ca0c5320.js');
var React = require('react');
require('@carbon/icon-helpers');
require('prop-types');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var React__default = /*#__PURE__*/_interopDefaultLegacy(React);

var _g;

var _excluded = ["children", "size"];
var WfpHumVamPos = /*#__PURE__*/React__default['default'].forwardRef(function WfpHumVamPos(_ref, ref) {
  var children = _ref.children,
      _ref$size = _ref.size,
      size = _ref$size === void 0 ? 16 : _ref$size,
      rest = iconPropTypes._objectWithoutProperties(_ref, _excluded);

  return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
    width: size,
    height: size,
    ref: ref,
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 47 15",
    fill: "currentColor"
  }, rest), _g || (_g = /*#__PURE__*/React__default['default'].createElement("g", {
    "fill-rule": "evenodd"
  }, /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M41.3.1L38.4 10.1 38.3 10.1 35.4.1 30.3.1 30.3 14.2 33.7 14.2 33.7 8C33.7 7 33.6 5.7 33.5 4L33.6 4 36.5 14.1 40.1 14.1 42.9 4 43 4C42.9 5.5 42.9 6.5 42.9 6.9 42.9 7.3 42.9 7.6 42.9 8L42.9 14.2 46.4 14.2 46.4.1 41.3.1zM9.8.1L7.8 7.3C7.7 7.7 7.6 8.2 7.4 8.9 7.3 9.6 7.2 10.1 7.1 10.6 7.1 10 6.8 8.9 6.4 7.3L4.5.2.3.2 4.9 14.3 9.4 14.3 14 .1 9.8.1z"
  }), /*#__PURE__*/React__default['default'].createElement("path", {
    "fill-rule": "nonzero",
    d: "M17.9,0 L13.3,14.1 L17.5,14.1 L18.2,11.5 L22.8,11.5 L23.5,14.1 L27.7,14.1 L23,0 L17.9,0 Z M19,8.4 C19.6,6.2 20,4.7 20.1,4 C20.3,3.2 20.4,2.7 20.4,2.4 C20.5,2.8 20.6,3.3 20.8,4.2 C21,5 21.2,5.7 21.3,6.2 L21.9,8.5 L19,8.5 L19,8.4 Z"
  }))), children);
});
WfpHumVamPos.propTypes = iconPropTypes.iconPropTypes;

module.exports = WfpHumVamPos;
