/**
 * Copyright IBM Corp. 2016, 2021
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @carbon/icon-build-helpers. DO NOT EDIT.
 */
'use strict';

var iconPropTypes = require('./iconPropTypes-ca0c5320.js');
var React = require('react');
require('@carbon/icon-helpers');
require('prop-types');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var React__default = /*#__PURE__*/_interopDefaultLegacy(React);

var _g;

var _excluded = ["children", "size"];
var WfpHumProcurementPos = /*#__PURE__*/React__default['default'].forwardRef(function WfpHumProcurementPos(_ref, ref) {
  var children = _ref.children,
      _ref$size = _ref.size,
      size = _ref$size === void 0 ? 16 : _ref$size,
      rest = iconPropTypes._objectWithoutProperties(_ref, _excluded);

  return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
    width: size,
    height: size,
    ref: ref,
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 29 40",
    fill: "currentColor"
  }, rest), _g || (_g = /*#__PURE__*/React__default['default'].createElement("g", {
    "fill-rule": "evenodd"
  }, /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M13.7 9.7L12.4 3.7C12.2 3 11.6 2.4 10.8 2.4L6.5 2.4C6 2.4 5.6 2.9 5.7 3.4L7.3 9.6 13.7 9.6 13.7 9.7zM23.7 23.5L23.1 23.5 23.1 25.3 23.5 25.3C23.8 25.3 24.1 25.2 24.3 25 24.5 24.8 24.6 24.6 24.6 24.2 24.6 23.8 24.3 23.5 23.7 23.5z"
  }), /*#__PURE__*/React__default['default'].createElement("path", {
    "fill-rule": "nonzero",
    d: "M28,23.7 L21.7,11.3 L7.3,11.3 L1,23.7 C-0.9,28.1 0.3,32.9 3.3,35.9 C5.3,38 8.1,39.3 11.3,39.3 L17.7,39.3 C20.9,39.3 23.7,38 25.7,35.9 C28.7,32.8 29.9,28.1 28,23.7 Z M12.5,29.8 L10,29.8 L9.2,26.3 C9.2,26.2 9.1,25.9 9,25.4 C8.9,25 8.9,24.6 8.8,24.3 C8.8,24.5 8.7,24.8 8.7,25.2 C8.6,25.6 8.6,25.9 8.5,26.2 C8.4,26.5 8.2,27.7 7.7,29.8 L5.1,29.8 L3.1,21.8 L5.2,21.8 L6.1,25.8 C6.3,26.7 6.4,27.4 6.5,27.9 C6.5,27.5 6.6,27 6.8,26.4 C6.9,25.8 7,25.2 7.1,24.8 L7.8,21.8 L9.8,21.8 L10.5,24.8 C10.6,25.3 10.7,25.9 10.9,26.5 C11,27.1 11.1,27.6 11.1,27.9 C11.1,27.5 11.3,26.8 11.5,25.8 L12.4,21.8 L14.5,21.8 L12.5,29.8 Z M20.2,23.5 L17.6,23.5 L17.6,25 L20,25 L20,26.7 L17.6,26.7 L17.6,29.7 L15.5,29.7 L15.5,21.7 L20.3,21.7 L20.3,23.5 L20.2,23.5 Z M26,26.4 C25.5,26.9 24.7,27.1 23.7,27.1 L23.1,27.1 L23.1,29.8 L21,29.8 L21,21.8 L23.8,21.8 C24.8,21.8 25.6,22 26.1,22.5 C26.6,22.9 26.9,23.6 26.9,24.4 C26.8,25.2 26.5,25.9 26,26.4 Z"
  }), /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M18.5,9.7 L21.7,9.7 L23.3,1.8 C23.4,1.3 23,0.9 22.5,0.9 L20.1,0.9 C19.2,0.9 18.5,1.6 18.5,2.5 C18.5,1.6 17.8,0.9 16.9,0.9 L14.5,0.9 C14,0.9 13.6,1.4 13.7,1.8 L15.3,9.7 L18.5,9.7 Z"
  }))), children);
});
WfpHumProcurementPos.propTypes = iconPropTypes.iconPropTypes;

module.exports = WfpHumProcurementPos;
