/**
 * Copyright IBM Corp. 2016, 2021
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @carbon/icon-build-helpers. DO NOT EDIT.
 */
'use strict';

var iconPropTypes = require('./iconPropTypes-ca0c5320.js');
var React = require('react');
require('@carbon/icon-helpers');
require('prop-types');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var React__default = /*#__PURE__*/_interopDefaultLegacy(React);

var _path;

var _excluded = ["children", "size"];
var WfpHumFoodPos = /*#__PURE__*/React__default['default'].forwardRef(function WfpHumFoodPos(_ref, ref) {
  var children = _ref.children,
      _ref$size = _ref.size,
      size = _ref$size === void 0 ? 16 : _ref$size,
      rest = iconPropTypes._objectWithoutProperties(_ref, _excluded);

  return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
    width: size,
    height: size,
    ref: ref,
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 41 29",
    fill: "currentColor"
  }, rest), _path || (_path = /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M6.9,8.9 C6.9,8.9 6.9,8.9 6.9,8.9 C7.1,6.1 9.5,3.8 12.4,3.8 C13.3,3.8 14.1,4 14.8,4.4 C15.6,2.1 17.8,0.4 20.4,0.4 C23,0.4 25.2,2.1 26,4.4 C26.7,4 27.6,3.8 28.4,3.8 C31.3,3.8 33.6,6 33.9,8.9 C33.9,8.9 33.9,8.9 33.9,8.9 C37.2,8.9 39.8,11.5 39.8,14.8 L30.6,14.8 L28,14.8 L12.8,14.8 L10.2,14.8 L1,14.8 C1,11.6 3.6,8.9 6.9,8.9 Z M37.4,25.1 C35.4,27.1 32.7,28.3 29.7,28.3 L11.1,28.3 C5,28.3 0.1,23.4 0.1,17.3 L40.6,17.3 C40.6,20.4 39.4,23.1 37.4,25.1 Z"
  })), children);
});
WfpHumFoodPos.propTypes = iconPropTypes.iconPropTypes;

module.exports = WfpHumFoodPos;
