/**
 * Copyright IBM Corp. 2016, 2021
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @carbon/icon-build-helpers. DO NOT EDIT.
 */
'use strict';

var iconPropTypes = require('./iconPropTypes-ca0c5320.js');
var React = require('react');
require('@carbon/icon-helpers');
require('prop-types');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var React__default = /*#__PURE__*/_interopDefaultLegacy(React);

var _g;

var _excluded = ["children", "size"];
var WfpHumCashPos = /*#__PURE__*/React__default['default'].forwardRef(function WfpHumCashPos(_ref, ref) {
  var children = _ref.children,
      _ref$size = _ref.size,
      size = _ref$size === void 0 ? 16 : _ref$size,
      rest = iconPropTypes._objectWithoutProperties(_ref, _excluded);

  return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
    width: size,
    height: size,
    ref: ref,
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 41 26",
    fill: "currentColor"
  }, rest), _g || (_g = /*#__PURE__*/React__default['default'].createElement("g", {
    "fill-rule": "evenodd"
  }, /*#__PURE__*/React__default['default'].createElement("path", {
    "fill-rule": "nonzero",
    d: "M35.6,8 L27.9,8 L17.2,8 L4.4,8 L1,8 C0.5,8 0.2,8.4 0.2,8.8 L0.2,24.8 C0.2,25.3 0.6,25.6 1,25.6 L35.6,25.6 C36.1,25.6 36.4,25.2 36.4,24.8 L36.4,18.1 L36.4,8.8 C36.4,8.4 36,8 35.6,8 Z M7.6,18.1 C7.3,19.1 6.3,19.8 5.2,19.8 C3.8,19.8 2.7,18.7 2.7,17.3 C2.7,16.2 3.4,15.3 4.4,14.9 C4.7,14.8 4.9,14.7 5.2,14.7 C6.6,14.7 7.7,15.8 7.7,17.2 C7.7,17.6 7.7,17.9 7.6,18.1 Z M23.6,18.1 C23,20.5 20.9,22.3 18.3,22.3 C15.7,22.3 13.5,20.5 13,18.1 C12.9,17.7 12.8,17.3 12.8,16.8 C12.8,14.1 14.8,11.8 17.5,11.4 C17.8,11.3 18,11.3 18.3,11.3 C20.6,11.3 22.5,12.7 23.3,14.6 C23.6,15.3 23.7,16 23.7,16.8 C23.8,17.3 23.7,17.7 23.6,18.1 Z M33.5,18.1 C33.1,18.9 32.2,19.4 31.3,19.4 C30.4,19.4 29.5,18.9 29.1,18.1 C28.9,17.7 28.8,17.3 28.8,16.8 C28.8,15.4 29.9,14.3 31.3,14.3 C32.7,14.3 33.8,15.4 33.8,16.8 C33.9,17.3 33.7,17.8 33.5,18.1 Z"
  }), /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M39.8,0.4 L5.2,0.4 C4.7,0.4 4.4,0.8 4.4,1.2 L4.4,6.3 L17.9,6.3 C18.9,4.8 20.6,3.8 22.5,3.8 C24.4,3.8 26.1,4.8 27.1,6.3 L35.5,6.3 C36.9,6.3 38,7.4 38,8.8 L38,18.1 L39.7,18.1 C40.2,18.1 40.5,17.7 40.5,17.3 L40.5,1.3 C40.6,0.8 40.2,0.4 39.8,0.4 Z"
  }))), children);
});
WfpHumCashPos.propTypes = iconPropTypes.iconPropTypes;

module.exports = WfpHumCashPos;
