/**
 * Copyright IBM Corp. 2016, 2021
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @carbon/icon-build-helpers. DO NOT EDIT.
 */
'use strict';

var iconPropTypes = require('./iconPropTypes-ca0c5320.js');
var React = require('react');
require('@carbon/icon-helpers');
require('prop-types');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var React__default = /*#__PURE__*/_interopDefaultLegacy(React);

var _path;

var _excluded = ["children", "size"];
var WfpHumP4pPos = /*#__PURE__*/React__default['default'].forwardRef(function WfpHumP4pPos(_ref, ref) {
  var children = _ref.children,
      _ref$size = _ref.size,
      size = _ref$size === void 0 ? 16 : _ref$size,
      rest = iconPropTypes._objectWithoutProperties(_ref, _excluded);

  return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
    width: size,
    height: size,
    ref: ref,
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 40 16",
    fill: "currentColor"
  }, rest), _path || (_path = /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M10.9 1.7C10.4 1.4 9.8 1.1 9.2 1 8.6.8 7.8.8 6.9.8L.7.8.7 15.4 4.5 15.4 4.5 10.7 6.8 10.7C7.9 10.7 8.7 10.6 9.5 10.3 10.2 10 10.9 9.6 11.4 9 11.8 8.6 12.1 8.1 12.4 7.4 12.6 6.8 12.7 6.1 12.7 5.5 12.7 4.7 12.5 3.9 12.2 3.3 12 2.6 11.5 2.1 10.9 1.7zM8.7 6.5C8.6 6.8 8.4 7 8.2 7.2 7.9 7.4 7.6 7.6 7.2 7.7 6.8 7.8 6.3 7.8 5.6 7.8L4.5 7.8 4.5 3.4 5.1 3.4C5.7 3.4 6.2 3.4 6.6 3.4 7 3.4 7.4 3.5 7.7 3.7 8 3.8 8.2 4 8.5 4.3 8.7 4.6 8.8 4.9 8.8 5.4 8.9 5.9 8.8 6.2 8.7 6.5zM24.2.8L20.4.8 13.6 9.2 13.6 12 20.7 12 20.7 15.4 24.3 15.4 24.3 12 26.3 12 26.3 9.3 24.3 9.3 24.3.8 24.2.8zM20.6 9.3L16.4 9.3 20.6 4 20.6 9.3zM39.6 3.2C39.3 2.6 38.8 2.1 38.3 1.7 37.8 1.4 37.2 1.1 36.6 1 36 .8 35.2.8 34.3.8L28 .8 28 15.4 31.8 15.4 31.8 10.7 34.1 10.7C35.2 10.7 36.1 10.6 36.8 10.3 37.5 10 38.2 9.6 38.7 9 39.1 8.6 39.5 8.1 39.7 7.4 39.9 6.8 40 6.1 40 5.5 40 4.5 39.9 3.8 39.6 3.2zM36 6.5C35.9 6.8 35.7 7 35.5 7.2 35.2 7.4 34.9 7.6 34.5 7.7 34.1 7.8 33.6 7.8 32.9 7.8L31.8 7.8 31.8 3.4 32.4 3.4C33 3.4 33.5 3.4 33.9 3.4 34.3 3.4 34.7 3.5 35 3.7 35.3 3.8 35.6 4 35.8 4.3 36 4.6 36.1 4.9 36.1 5.4 36.2 5.9 36.1 6.2 36 6.5z"
  })), children);
});
WfpHumP4pPos.propTypes = iconPropTypes.iconPropTypes;

module.exports = WfpHumP4pPos;
