/**
 * Copyright IBM Corp. 2016, 2021
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @carbon/icon-build-helpers. DO NOT EDIT.
 */
'use strict';

var iconPropTypes = require('./iconPropTypes-ca0c5320.js');
var React = require('react');
require('@carbon/icon-helpers');
require('prop-types');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var React__default = /*#__PURE__*/_interopDefaultLegacy(React);

var _path;

var _excluded = ["children", "size"];
var WfpHumReliefGoodsNeg = /*#__PURE__*/React__default['default'].forwardRef(function WfpHumReliefGoodsNeg(_ref, ref) {
  var children = _ref.children,
      _ref$size = _ref.size,
      size = _ref$size === void 0 ? 16 : _ref$size,
      rest = iconPropTypes._objectWithoutProperties(_ref, _excluded);

  return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
    width: size,
    height: size,
    ref: ref,
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 57 57",
    fill: "currentColor"
  }, rest), _path || (_path = /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M54.4,0 L2.4,0 C1.1,0 0,1.1 0,2.4 L0,4.1 L0,52 L0,53.7 C0,55 1.1,56.1 2.4,56.1 L54.4,56.1 C55.7,56.1 56.8,55 56.8,53.7 L56.8,52 L56.8,4.1 L56.8,2.4 C56.8,1.1 55.7,0 54.4,0 Z M33.4,47.5 C33.4,48 33,48.3 32.6,48.3 L24.2,48.3 C23.7,48.3 23.4,47.9 23.4,47.5 L23.4,39 C23.4,38.5 23.8,38.2 24.2,38.2 L32.6,38.2 C33.1,38.2 33.4,38.6 33.4,39 L33.4,47.5 Z M39.8,26 L29.3,36.1 C29.3,36.1 29.3,36.1 29.3,36.1 C29.2,36.2 29.1,36.3 28.9,36.3 C28.9,36.3 28.9,36.3 28.9,36.3 C28.8,36.4 28.6,36.4 28.5,36.4 C28.3,36.4 28.2,36.4 28.1,36.3 C28.1,36.3 28.1,36.3 28.1,36.3 C28,36.2 27.8,36.2 27.7,36.1 C27.7,36.1 27.7,36.1 27.7,36.1 L17,26 C16.5,25.5 16.5,24.7 17,24.2 C17.5,23.7 18.3,23.7 18.8,24.2 L28.5,33.5 L38.2,24.2 C38.7,23.7 39.5,23.7 40,24.2 C40.3,24.7 40.3,25.5 39.8,26 Z M14,22.2 C14,14.3 20.4,7.9 28.3,7.9 C36.2,7.9 42.6,14.3 42.6,22.2 L14,22.2 Z"
  })), children);
});
WfpHumReliefGoodsNeg.propTypes = iconPropTypes.iconPropTypes;

module.exports = WfpHumReliefGoodsNeg;
