/**
 * Copyright IBM Corp. 2016, 2021
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @carbon/icon-build-helpers. DO NOT EDIT.
 */
'use strict';

var iconPropTypes = require('./iconPropTypes-ca0c5320.js');
var React = require('react');
require('@carbon/icon-helpers');
require('prop-types');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var React__default = /*#__PURE__*/_interopDefaultLegacy(React);

var _g;

var _excluded = ["children", "size"];
var WfpHumPowerplantNeg = /*#__PURE__*/React__default['default'].forwardRef(function WfpHumPowerplantNeg(_ref, ref) {
  var children = _ref.children,
      _ref$size = _ref.size,
      size = _ref$size === void 0 ? 16 : _ref$size,
      rest = iconPropTypes._objectWithoutProperties(_ref, _excluded);

  return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
    width: size,
    height: size,
    ref: ref,
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 57 57",
    fill: "currentColor"
  }, rest), _g || (_g = /*#__PURE__*/React__default['default'].createElement("g", {
    "fill-rule": "evenodd"
  }, /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M32.2,36.1 L25.6,36.1 L29.3,30.1 C29.8,29.4 29.5,28.4 28.8,27.9 C28.1,27.4 27.1,27.7 26.6,28.4 L21.4,36.8 C21.1,37.3 21.1,37.9 21.4,38.4 C21.7,38.9 22.2,39.2 22.8,39.2 L29.4,39.2 L25.7,45.2 C25.2,45.9 25.5,46.9 26.2,47.4 C26.5,47.6 26.7,47.6 27,47.6 C27.5,47.6 28,47.3 28.3,46.9 L33.5,38.5 C33.8,38 33.8,37.4 33.5,36.9 C33.3,36.4 32.7,36.1 32.2,36.1 Z"
  }), /*#__PURE__*/React__default['default'].createElement("path", {
    "fill-rule": "nonzero",
    d: "M54.4,0 L2.4,0 C1.1,0 0,1.1 0,2.4 L0,4.1 L0,52 L0,53.7 C0,55 1.1,56.1 2.4,56.1 L54.4,56.1 C55.7,56.1 56.8,55 56.8,53.7 L56.8,52 L56.8,4.1 L56.8,2.4 C56.8,1.1 55.7,0 54.4,0 Z M21.2,15.7 L27,15.7 C28.3,15.8 29.6,15.3 30.5,14.4 C31.5,13.5 32,12.3 32.1,11 C32.1,10 31.8,9.1 31.1,8.3 C30.4,7.6 29.5,7.1 28.5,7.1 C27.8,7.1 27.1,7.3 26.5,7.8 C26,8.3 25.6,9 25.6,9.7 C25.5,10.8 26.4,11.7 27.4,11.7 C28.1,11.7 28.6,12.3 28.5,13 C28.5,13.7 27.9,14.2 27.2,14.1 C24.8,14 23,12 23.1,9.6 C23.4,8.3 24,7 25,6.1 C26,5.2 27.3,4.7 28.7,4.8 C32.1,5 34.7,7.8 34.5,11.2 C34.4,13.2 33.6,15 32.1,16.3 C30.7,17.6 28.8,18.3 26.9,18.2 L21.1,18.2 C20.4,18.2 19.9,17.7 19.9,17 C20,16.3 20.5,15.7 21.2,15.7 Z M14,50.4 L17.9,26.5 C17.9,25.6 18.7,24.8 19.6,24.8 L35.3,24.8 C36.2,24.8 37,25.6 37,26.5 L40.9,50.4 L14,50.4 Z M41.7,19.8 C41.4,20.4 41.1,20.9 40.6,21.4 C39.6,22.3 38.4,22.7 37.1,22.7 L20.5,22.8 C19.8,22.8 19.3,22.3 19.3,21.6 C19.3,20.9 19.8,20.4 20.5,20.4 L37.1,20.3 C37.8,20.3 38.4,20.1 38.9,19.6 C39.4,19.1 39.7,18.5 39.7,17.8 C39.7,16.8 39,16 38,15.9 C37.7,15.9 37.4,16 37.2,16.2 C37,16.4 36.8,16.7 36.7,17 C36.6,17.4 36.3,18 35.6,18 C34.9,18 34.4,17.6 34.4,16.9 C34.4,15.9 34.9,15.1 35.6,14.4 C36.3,13.7 37.2,13.4 38.1,13.5 C40.4,13.6 42.2,15.5 42.1,17.9 C42.2,18.6 42,19.2 41.7,19.8 Z"
  }))), children);
});
WfpHumPowerplantNeg.propTypes = iconPropTypes.iconPropTypes;

module.exports = WfpHumPowerplantNeg;
