/**
 * Copyright IBM Corp. 2016, 2021
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @carbon/icon-build-helpers. DO NOT EDIT.
 */
'use strict';

var iconPropTypes = require('./iconPropTypes-ca0c5320.js');
var React = require('react');
require('@carbon/icon-helpers');
require('prop-types');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var React__default = /*#__PURE__*/_interopDefaultLegacy(React);

var _path;

var _excluded = ["children", "size"];
var WfpLogoAcronym = /*#__PURE__*/React__default['default'].forwardRef(function WfpLogoAcronym(_ref, ref) {
  var children = _ref.children,
      _ref$size = _ref.size,
      size = _ref$size === void 0 ? 16 : _ref$size,
      rest = iconPropTypes._objectWithoutProperties(_ref, _excluded);

  return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
    width: size,
    height: size,
    ref: ref,
    xmlns: "http://www.w3.org/2000/svg",
    viewBox: "0 0 57 20",
    fill: "currentColor"
  }, rest), _path || (_path = /*#__PURE__*/React__default['default'].createElement("path", {
    "fill-rule": "evenodd",
    d: "M398.303,115.618 L399.671,115.618 C400.949,115.618 401.906,115.365 402.542,114.858 C403.176,114.353 403.494,113.617 403.494,112.652 C403.494,111.677 403.227,110.958 402.696,110.493 C402.163,110.028 401.33,109.793 400.194,109.793 L398.303,109.793 L398.303,115.618 Z M407.693,112.504 C407.693,114.615 407.033,116.23 405.714,117.346 C404.395,118.466 402.519,119.024 400.087,119.024 L398.303,119.024 L398.303,126 L394.144,126 L394.144,106.386 L400.408,106.386 C402.787,106.386 404.595,106.898 405.834,107.924 C407.074,108.948 407.693,110.474 407.693,112.504 Z M384.185,126 L380.095,126 L380.095,106.386 L391.336,106.386 L391.336,109.793 L384.185,109.793 L384.185,114.853 L390.84,114.853 L390.84,118.247 L384.185,118.247 L384.185,126 Z M372.572,126 L367.836,126 L365.18,115.697 C365.081,115.33 364.914,114.573 364.677,113.423 C364.44,112.273 364.303,111.502 364.268,111.11 C364.214,111.593 364.08,112.369 363.866,113.437 C363.651,114.505 363.485,115.269 363.369,115.725 L360.726,126 L356.005,126 L351,106.386 L355.092,106.386 L357.601,117.092 C358.039,119.069 358.356,120.782 358.553,122.231 C358.607,121.721 358.729,120.931 358.922,119.864 C359.114,118.794 359.295,117.963 359.466,117.375 L362.322,106.386 L366.253,106.386 L369.111,117.375 C369.236,117.866 369.393,118.618 369.581,119.628 C369.768,120.639 369.911,121.506 370.01,122.231 C370.098,121.532 370.242,120.663 370.438,119.621 C370.636,118.581 370.815,117.737 370.976,117.092 L373.47,106.386 L377.562,106.386 L372.572,126 Z",
    transform: "translate(-351 -106)"
  })), children);
});
WfpLogoAcronym.propTypes = iconPropTypes.iconPropTypes;

module.exports = WfpLogoAcronym;
