/**
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @un/icon-build-helpers. DO NOT EDIT.
 * @un/icon-build-helpers is a fork of @carbon/icon-build-helpers
 */
'use strict';

var Icon = require('../Icon-17378097.js');
var React = require('react');
require('@carbon/icon-helpers');
require('prop-types');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var React__default = /*#__PURE__*/_interopDefaultLegacy(React);

var _mask, _g, _path;

var _excluded = ["children"];
var PregnantNegative = /*#__PURE__*/React__default['default'].forwardRef(function PregnantNegative(_ref, ref) {
  var children = _ref.children,
      rest = Icon._objectWithoutProperties(_ref, _excluded);

  return /*#__PURE__*/React__default['default'].createElement(Icon.Icon, Icon._extends({
    width: 56,
    height: 56,
    viewBox: "0 0 56 56",
    xmlns: "http://www.w3.org/2000/svg",
    fill: "currentColor",
    ref: ref
  }, rest), _mask || (_mask = /*#__PURE__*/React__default['default'].createElement("mask", {
    id: "a",
    width: "56",
    height: "56",
    x: "0",
    y: "0",
    maskUnits: "userSpaceOnUse"
  })), _g || (_g = /*#__PURE__*/React__default['default'].createElement("g", {
    mask: "url(#a)"
  })), _path || (_path = /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M34.6168 26.8663C34.3358 26.9576 34.0696 27.1227 33.8466 27.3545L33.6815 27.5206L33.5155 27.3545C32.8111 26.6256 31.6606 26.5519 30.9395 27.2553C30.1948 27.9843 30.1771 29.2016 30.8982 29.9472L32.0418 31.1311L33.2502 32.3818C33.3671 32.4977 33.5155 32.5557 33.6638 32.5645C33.821 32.5645 33.9871 32.5065 34.1118 32.3818L35.1297 31.3296L36.2487 30.1703L36.4638 29.9472C37.184 29.2016 37.1683 27.9843 36.4226 27.2553C35.9255 26.7749 35.2387 26.659 34.6168 26.8663Z",
    clipRule: "evenodd"
  })), children);
});

module.exports = PregnantNegative;
