/**
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @un/icon-build-helpers. DO NOT EDIT.
 * @un/icon-build-helpers is a fork of @carbon/icon-build-helpers
 */
'use strict';

var Icon = require('../Icon-17378097.js');
var React = require('react');
require('@carbon/icon-helpers');
require('prop-types');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var React__default = /*#__PURE__*/_interopDefaultLegacy(React);

var _path, _mask, _g;

var _excluded = ["children"];
var NutritionClusterNegative = /*#__PURE__*/React__default['default'].forwardRef(function NutritionClusterNegative(_ref, ref) {
  var children = _ref.children,
      rest = Icon._objectWithoutProperties(_ref, _excluded);

  return /*#__PURE__*/React__default['default'].createElement(Icon.Icon, Icon._extends({
    width: 56,
    height: 56,
    viewBox: "0 0 56 56",
    xmlns: "http://www.w3.org/2000/svg",
    fill: "currentColor",
    ref: ref
  }, rest), _path || (_path = /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M35.0766 26.6924C34.1895 27.553 32.6499 27.553 31.7638 26.6924C31.3826 26.319 30.7695 26.319 30.3883 26.6924C30.016 27.0568 30.016 27.6611 30.3883 28.0255C31.1998 28.8204 32.2766 29.2517 33.4192 29.2517C34.5628 29.2517 35.6396 28.8204 36.4511 28.0255C36.8234 27.6611 36.8234 27.0568 36.4511 26.6924C36.0699 26.319 35.4568 26.319 35.0766 26.6924Z",
    clipRule: "evenodd"
  })), _mask || (_mask = /*#__PURE__*/React__default['default'].createElement("mask", {
    id: "a",
    width: "56",
    height: "56",
    x: "0",
    y: "0",
    maskUnits: "userSpaceOnUse"
  })), _g || (_g = /*#__PURE__*/React__default['default'].createElement("g", {
    mask: "url(#a)"
  })), children);
});

module.exports = NutritionClusterNegative;
