/**
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @un/icon-build-helpers. DO NOT EDIT.
 * @un/icon-build-helpers is a fork of @carbon/icon-build-helpers
 */
'use strict';

var Icon = require('../Icon-17378097.js');
var React = require('react');
require('@carbon/icon-helpers');
require('prop-types');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var React__default = /*#__PURE__*/_interopDefaultLegacy(React);

var _mask, _g, _path, _path2, _path3;

var _excluded = ["children"];
var AidsPositive = /*#__PURE__*/React__default['default'].forwardRef(function AidsPositive(_ref, ref) {
  var children = _ref.children,
      rest = Icon._objectWithoutProperties(_ref, _excluded);

  return /*#__PURE__*/React__default['default'].createElement(Icon.Icon, Icon._extends({
    width: 38,
    height: 47,
    viewBox: "0 0 38 47",
    xmlns: "http://www.w3.org/2000/svg",
    fill: "currentColor",
    ref: ref
  }, rest), _mask || (_mask = /*#__PURE__*/React__default['default'].createElement("mask", {
    id: "a",
    width: "38",
    height: "47",
    x: "0",
    y: "0",
    maskUnits: "userSpaceOnUse"
  })), _g || (_g = /*#__PURE__*/React__default['default'].createElement("g", {
    mask: "url(#a)"
  })), _path || (_path = /*#__PURE__*/React__default['default'].createElement("path", {
    fill: "#D8232A",
    fillRule: "evenodd",
    d: "M15.541 7.63C16.534 6.932 17.772 6.568 19.025 6.568C19.678 6.568 20.337 6.667 20.965 6.871C21.775 7.132 23.049 7.795 23.783 9.178C24.371 6.562 24.312 4.219 24.154 2.726C23.733 2.456 23.339 2.295 22.876 2.146C19.935 1.192 16.67 1.413 13.927 2.648C13.817 3.356 13.384 6.008 13.982 9.372C14.314 8.729 14.844 8.119 15.541 7.63Z",
    clipRule: "evenodd"
  })), _path2 || (_path2 = /*#__PURE__*/React__default['default'].createElement("path", {
    fill: "#D8232A",
    fillRule: "evenodd",
    d: "M14.671 24.308C15.84 22.839 17.001 21.346 18.105 19.841 17.728 19.316 16.957 18.26 16.95 18.251 11.909 12.063 12.347 5.821 12.684 3.303 12.478 3.428 12.266 3.54 12.071 3.678 9.96803 5.152 8.56703 7.165 8.12703 9.343 7.74903 11.204 8.06303 13.255 9.06003 15.44 10.524 18.648 12.545 21.541 14.671 24.308zM35.861 41.575C31.664 36.956 27.636 32.153 23.891 27.299 23.643 26.979 23.391 26.662 23.141 26.343 22.697 26.906 22.256 27.473 21.813 28.03 21.105 28.918 20.408 29.795 19.741 30.659 19.73 30.673 19.718 30.688 19.706 30.702 23.414 35.475 27.37 40.199 31.501 44.745 32.056 45.355 32.866 45.672 33.682 45.672 34.306 45.672 34.932 45.488 35.454 45.109 36.657 44.234 36.841 42.652 35.861 41.575z",
    clipRule: "evenodd"
  })), _path3 || (_path3 = /*#__PURE__*/React__default['default'].createElement("path", {
    fill: "#D8232A",
    fillRule: "evenodd",
    d: "M29.063 14.636C29.597 13.311 29.847 12.101 29.871 10.963C29.873 10.891 29.878 10.818 29.879 10.748C29.875 10.201 29.833 9.667 29.711 9.145C29.119 6.679 27.576 4.633 25.353 3.276C25.369 3.564 25.401 3.967 25.406 4.068C25.424 4.37 25.435 4.672 25.44 4.974C25.451 5.655 25.427 6.337 25.358 7.016C25.189 8.679 24.681 10.215 24.158 11.792C23.101 14.977 21.27 17.781 19.279 20.461C18.232 21.87 17.139 23.244 16.045 24.617C15.321 25.523 14.609 26.418 13.929 27.3C10.184 32.153 6.156 36.956 1.959 41.575C0.978999 42.652 1.163 44.234 2.366 45.109C2.706 45.356 3.095 45.49 3.519 45.579C3.725 45.62 3.93 45.672 4.138 45.672C4.954 45.672 5.766 45.355 6.319 44.745C10.61 40.024 14.726 35.114 18.555 30.153C19.22 29.292 19.917 28.417 20.622 27.531C23.853 23.475 27.193 19.279 29.063 14.636Z",
    clipRule: "evenodd"
  })), children);
});

module.exports = AidsPositive;
