/**
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @un/icon-build-helpers. DO NOT EDIT.
 * @un/icon-build-helpers is a fork of @carbon/icon-build-helpers
 */
'use strict';

var Icon = require('../Icon-17378097.js');
var React = require('react');
require('@carbon/icon-helpers');
require('prop-types');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var React__default = /*#__PURE__*/_interopDefaultLegacy(React);

var _mask, _g, _path;

var _excluded = ["children"];
var MedicalEvacuationsNegative = /*#__PURE__*/React__default['default'].forwardRef(function MedicalEvacuationsNegative(_ref, ref) {
  var children = _ref.children,
      rest = Icon._objectWithoutProperties(_ref, _excluded);

  return /*#__PURE__*/React__default['default'].createElement(Icon.Icon, Icon._extends({
    width: 56,
    height: 56,
    viewBox: "0 0 56 56",
    xmlns: "http://www.w3.org/2000/svg",
    fill: "currentColor",
    ref: ref
  }, rest), _mask || (_mask = /*#__PURE__*/React__default['default'].createElement("mask", {
    id: "a",
    width: "56",
    height: "56",
    x: "0",
    y: "0",
    maskUnits: "userSpaceOnUse"
  })), _g || (_g = /*#__PURE__*/React__default['default'].createElement("g", {
    mask: "url(#a)"
  })), _path || (_path = /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M47.8533 12.5375H46.1365V14.2533C46.1365 14.6105 45.9916 14.932 45.7599 15.1627C45.5282 15.3954 45.2057 15.5413 44.8505 15.5413C44.1371 15.5413 43.5635 14.9657 43.5635 14.2533V12.5375H41.8467C41.4895 12.5375 41.168 12.3916 40.9363 12.1599C40.7046 11.9282 40.5587 11.6067 40.5587 11.2505C40.5587 10.5381 41.1343 9.96244 41.8467 9.96244H43.5635V8.24672C43.5635 7.89051 43.7084 7.569 43.9401 7.33732C44.1728 7.10563 44.4943 6.95865 44.8505 6.95865C45.5619 6.95865 46.1365 7.5343 46.1365 8.24672V9.96244H47.8533C48.2095 9.96244 48.531 10.1084 48.7627 10.3401C48.9944 10.5728 49.1413 10.8933 49.1413 11.2505C49.1413 11.9619 48.5657 12.5375 47.8533 12.5375ZM44.8495 4.89999C41.3486 4.89999 38.5 7.74864 38.5 11.2505C38.5 14.7513 41.3486 17.6 44.8495 17.6C48.3514 17.6 51.2 14.7513 51.2 11.2505C51.2 7.74864 48.3514 4.89999 44.8495 4.89999Z",
    clipRule: "evenodd"
  })), children);
});

module.exports = MedicalEvacuationsNegative;
