/**
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @un/icon-build-helpers. DO NOT EDIT.
 * @un/icon-build-helpers is a fork of @carbon/icon-build-helpers
 */
'use strict';

var Icon = require('../Icon-17378097.js');
var React = require('react');
require('@carbon/icon-helpers');
require('prop-types');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var React__default = /*#__PURE__*/_interopDefaultLegacy(React);

var _mask, _g, _path;

var _excluded = ["children"];
var CivilMilitaryCoordinationPositive = /*#__PURE__*/React__default['default'].forwardRef(function CivilMilitaryCoordinationPositive(_ref, ref) {
  var children = _ref.children,
      rest = Icon._objectWithoutProperties(_ref, _excluded);

  return /*#__PURE__*/React__default['default'].createElement(Icon.Icon, Icon._extends({
    width: 41,
    height: 41,
    viewBox: "0 0 41 41",
    xmlns: "http://www.w3.org/2000/svg",
    fill: "currentColor",
    ref: ref
  }, rest), _mask || (_mask = /*#__PURE__*/React__default['default'].createElement("mask", {
    id: "a",
    width: "41",
    height: "37",
    x: "0",
    y: "4",
    maskUnits: "userSpaceOnUse"
  })), _g || (_g = /*#__PURE__*/React__default['default'].createElement("g", {
    mask: "url(#a)"
  })), _path || (_path = /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M15.191 13.265L14.221 14.234 13.109 15.348 6.019 22.437H14.331V16.258C15.646 17.497 16.472 19.259 16.472 21.206 16.472 23.153 15.646 24.916 14.331 26.155V24.966H5.058V26.189C3.726 24.94 2.883 23.17 2.883 21.206 2.883 19.242 3.726 17.472 5.058 16.224V19.824L11.667 13.215 12.822 12.06C11.835 11.714 10.774 11.528 9.677 11.528 4.341 11.528 0 15.87 0 21.206 0 24.873 2.048 28.068 5.058 29.704 5.064 29.707 5.071 29.71 5.077 29.713 5.121 29.899 5.28 30.041 5.479 30.041H13.91C14.116 30.041 14.28 29.89 14.316 29.694 14.321 29.691 14.326 29.69 14.331 29.687 17.324 28.043 19.355 24.857 19.355 21.206 19.355 17.919 17.703 15.01 15.191 13.265zM30.769 9.809C32.865 9.809 34.563 8.11 34.563 6.016 34.563 3.92 32.865 2.222 30.769 2.222 28.674 2.222 26.976 3.92 26.976 6.016 26.976 8.11 28.674 9.809 30.769 9.809zM26.099 16.224C26.11 16.214 26.123 16.205 26.133 16.195V26.15C26.123 26.14 26.11 26.131 26.099 26.121 24.784 24.882 23.958 23.12 23.958 21.172 23.958 19.225 24.784 17.463 26.099 16.224zM35.406 16.225C36.717 17.471 37.547 19.226 37.547 21.172 37.547 23.119 36.717 24.874 35.406 26.12V16.225zM26.099 29.653C26.114 29.661 26.129 29.667 26.144 29.675 26.172 29.88 26.341 30.041 26.554 30.041H34.985C35.205 30.041 35.38 29.87 35.399 29.654 38.394 28.015 40.43 24.829 40.43 21.172 40.43 15.836 36.088 11.495 30.752 11.495 25.417 11.495 21.075 15.836 21.075 21.172 21.075 24.823 23.107 28.009 26.099 29.653zM6.744 3.065H12.645C13.109 3.065 13.488 2.67 13.488 2.188V1.417C13.488.891003 13.049.488004 12.552.541004L6.651 1.224C6.221 1.277 5.901 1.654 5.901 2.101V2.188C5.901 2.67 6.28 3.065 6.744 3.065z",
    clipRule: "evenodd"
  })), children);
});

module.exports = CivilMilitaryCoordinationPositive;
