/**
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @un/icon-build-helpers. DO NOT EDIT.
 * @un/icon-build-helpers is a fork of @carbon/icon-build-helpers
 */
'use strict';

var Icon = require('../../Icon-17378097.js');
var React = require('react');
require('@carbon/icon-helpers');
require('prop-types');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var React__default = /*#__PURE__*/_interopDefaultLegacy(React);

var _path, _path2, _path3, _path4, _path5, _path6, _path7, _path8, _path9, _path10, _g, _defs;

var _excluded = ["children"];
var IllustrationsMilk = /*#__PURE__*/React__default['default'].forwardRef(function IllustrationsMilk(_ref, ref) {
  var children = _ref.children,
      rest = Icon._objectWithoutProperties(_ref, _excluded);

  return /*#__PURE__*/React__default['default'].createElement(Icon.Icon, Icon._extends({
    width: 513,
    height: 941,
    viewBox: "0 0 513 941",
    xmlns: "http://www.w3.org/2000/svg",
    fill: "currentColor",
    ref: ref
  }, rest), _path || (_path = /*#__PURE__*/React__default['default'].createElement("path", {
    fill: "#fff",
    stroke: "#07074E",
    strokeLinecap: "round",
    strokeLinejoin: "round",
    strokeWidth: "18",
    d: "M9 180.091H366.574V932L9 909.336V180.091Z"
  })), _path2 || (_path2 = /*#__PURE__*/React__default['default'].createElement("path", {
    fill: "#0A6EB4",
    stroke: "#07074E",
    strokeLinecap: "round",
    strokeLinejoin: "round",
    strokeWidth: "18",
    d: "M9 304.52H366.574V816.458L9 793.794V304.52Z"
  })), _path3 || (_path3 = /*#__PURE__*/React__default['default'].createElement("path", {
    stroke: "#07074E",
    strokeLinecap: "round",
    strokeLinejoin: "round",
    strokeWidth: "18",
    d: "M9 180.091H366.574L420.388 79.6582H92.6119L9 180.091Z"
  })), _path4 || (_path4 = /*#__PURE__*/React__default['default'].createElement("path", {
    stroke: "#07074E",
    strokeLinecap: "round",
    strokeLinejoin: "round",
    strokeWidth: "18",
    d: "M501.776 133.43L366.574 180.091L420.388 79.6582L501.776 133.43Z"
  })), _path5 || (_path5 = /*#__PURE__*/React__default['default'].createElement("path", {
    fill: "#fff",
    d: "M90.8328 9H418.609V75.6587L90.8328 82.7689V9Z"
  })), _path6 || (_path6 = /*#__PURE__*/React__default['default'].createElement("path", {
    fill: "#fff",
    d: "M90.8328 9H418.609V75.6587L90.8328 82.7689V9Z"
  })), _path7 || (_path7 = /*#__PURE__*/React__default['default'].createElement("path", {
    stroke: "#07074E",
    strokeLinecap: "round",
    strokeLinejoin: "round",
    strokeWidth: "18",
    d: "M90.8328 9H418.609V75.6587L90.8328 82.7689V9Z"
  })), _path8 || (_path8 = /*#__PURE__*/React__default['default'].createElement("path", {
    stroke: "#07074E",
    strokeLinecap: "round",
    strokeLinejoin: "round",
    strokeWidth: "18",
    d: "M90.8328 9H418.609V75.6587L90.8328 82.7689V9Z"
  })), _path9 || (_path9 = /*#__PURE__*/React__default['default'].createElement("path", {
    fill: "#DEDEDE",
    stroke: "#07074E",
    strokeLinecap: "round",
    strokeLinejoin: "round",
    strokeWidth: "18",
    d: "M504 134.763L366.574 180.091V932L504 831.568V134.763Z"
  })), _path10 || (_path10 = /*#__PURE__*/React__default['default'].createElement("path", {
    fill: "#034F85",
    stroke: "#07074E",
    strokeLinecap: "round",
    strokeLinejoin: "round",
    strokeWidth: "18",
    d: "M504 259.192L366.574 304.52V816.459L504 716.026V259.192Z"
  })), _g || (_g = /*#__PURE__*/React__default['default'].createElement("g", {
    clipPath: "url(#clip0)"
  })), _defs || (_defs = /*#__PURE__*/React__default['default'].createElement("defs", null)), children);
});

module.exports = IllustrationsMilk;
