/**
 * Copyright IBM Corp. 2019, 2019
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

'use strict';

const { default: template } = require('@babel/template');

const banner = `/**
 *
 * Code generated by @wfp/icon-build-helpers. DO NOT EDIT.
 * @wfp/icon-build-helpers is a fork of @carbon/icon-build-helpers
 */`;

const jsx = template.expression(
  `
    React.createElement(
      Icon,
      %%props%%,
      %%children%%,
      children
    )
  `,
  {
    plugins: ['jsx'],
  }
);

const component = template(
  `
    const %%moduleName%% = React.forwardRef(
      function %%moduleName%%({ children, size = %%defaultSize%%, ...rest }, ref) {
        %%statements%%
      }
    );

    %%moduleName%%.propTypes = iconPropTypes;
  `,
  {
    plugins: ['jsx'],
  }
);

const deprecatedBlock = template(
  `
    if (__DEV__) {
      if (!%%check%%) {
        %%check%% = true;
        console.warn(%%warning%%);
      }
    }
  `
);

module.exports = {
  banner,
  component,
  deprecatedBlock,
  jsx,
};
