/**
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @un/icon-build-helpers. DO NOT EDIT.
 * @un/icon-build-helpers is a fork of @carbon/icon-build-helpers
 */
'use strict';

var Icon = require('../Icon-17378097.js');
var React = require('react');
require('@carbon/icon-helpers');
require('prop-types');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var React__default = /*#__PURE__*/_interopDefaultLegacy(React);

var _path, _mask, _g, _path2;

var _excluded = ["children"];
var TruckNegative = /*#__PURE__*/React__default['default'].forwardRef(function TruckNegative(_ref, ref) {
  var children = _ref.children,
      rest = Icon._objectWithoutProperties(_ref, _excluded);

  return /*#__PURE__*/React__default['default'].createElement(Icon.Icon, Icon._extends({
    width: 56,
    height: 56,
    viewBox: "0 0 56 56",
    xmlns: "http://www.w3.org/2000/svg",
    fill: "currentColor",
    ref: ref
  }, rest), _path || (_path = /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M23.1575 32.6156C22.8745 32.3238 22.4806 32.1519 22.0483 32.1519 21.278 32.1519 20.6394 32.7109 20.4989 33.4418 20.4822 33.5361 20.4744 33.6305 20.4744 33.7248V37.6595C20.4744 38.525 21.1827 39.2324 22.0483 39.2324 22.9138 39.2324 23.6222 38.525 23.6222 37.6595V33.7248C23.6222 33.6305 23.6143 33.5361 23.5986 33.4418 23.5357 33.1196 23.3854 32.8356 23.1575 32.6156zM28.6651 32.6156C28.3822 32.3238 27.9892 32.1519 27.5559 32.1519 26.7847 32.1519 26.1481 32.7109 26.0056 33.4418 25.9909 33.5361 25.983 33.6305 25.983 33.7248V37.6595C25.983 38.525 26.6914 39.2324 27.5559 39.2324 28.4215 39.2324 29.1298 38.525 29.1298 37.6595V33.7248C29.1298 33.6305 29.122 33.5361 29.1053 33.4418 29.0434 33.1196 28.894 32.8356 28.6651 32.6156zM16.1476 32.9378C15.062 32.9378 14.1808 33.8191 14.1808 34.9047 14.1808 35.9913 15.062 36.8725 16.1476 36.8725 17.2333 36.8725 18.1145 35.9913 18.1145 34.9047 18.1145 33.8191 17.2333 32.9378 16.1476 32.9378z",
    clipRule: "evenodd"
  })), _mask || (_mask = /*#__PURE__*/React__default['default'].createElement("mask", {
    id: "a",
    width: "56",
    height: "56",
    x: "0",
    y: "0",
    maskUnits: "userSpaceOnUse"
  })), _g || (_g = /*#__PURE__*/React__default['default'].createElement("g", {
    mask: "url(#a)"
  })), _path2 || (_path2 = /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M38.9652 32.9378C37.8786 32.9378 36.9973 33.8191 36.9973 34.9047 36.9973 35.9913 37.8786 36.8725 38.9652 36.8725 40.0498 36.8725 40.9321 35.9913 40.9321 34.9047 40.9321 33.8191 40.0498 32.9378 38.9652 32.9378zM33.8505 22.7104H21.2613C19.9635 22.7104 18.9015 23.7725 18.9015 25.0703V29.0041H36.2104V25.0703C36.2104 23.7725 35.1484 22.7104 33.8505 22.7104z",
    clipRule: "evenodd"
  })), children);
});

module.exports = TruckNegative;
