/**
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @un/icon-build-helpers. DO NOT EDIT.
 * @un/icon-build-helpers is a fork of @carbon/icon-build-helpers
 */
'use strict';

var Icon = require('../Icon-17378097.js');
var React = require('react');
require('@carbon/icon-helpers');
require('prop-types');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var React__default = /*#__PURE__*/_interopDefaultLegacy(React);

var _path, _mask, _g;

var _excluded = ["children"];
var CashBasedTransfersNegative = /*#__PURE__*/React__default['default'].forwardRef(function CashBasedTransfersNegative(_ref, ref) {
  var children = _ref.children,
      rest = Icon._objectWithoutProperties(_ref, _excluded);

  return /*#__PURE__*/React__default['default'].createElement(Icon.Icon, Icon._extends({
    width: 56,
    height: 56,
    viewBox: "0 0 56 56",
    xmlns: "http://www.w3.org/2000/svg",
    fill: "currentColor",
    ref: ref
  }, rest), _path || (_path = /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M41.1345 25.9388C39.759 25.9388 38.6498 27.048 38.6498 28.4234 38.6498 29.7979 39.759 30.9081 41.1345 30.9081 42.5089 30.9081 43.6191 29.7979 43.6191 28.4234 43.6191 27.048 42.5089 25.9388 41.1345 25.9388zM14.6317 25.9388C13.2573 25.9388 12.1471 27.048 12.1471 28.4234 12.1471 29.7979 13.2573 30.9081 14.6317 30.9081 16.0062 30.9081 17.1164 29.7979 17.1164 28.4234 17.1164 27.048 16.0062 25.9388 14.6317 25.9388z",
    clipRule: "evenodd"
  })), _mask || (_mask = /*#__PURE__*/React__default['default'].createElement("mask", {
    id: "a",
    width: "56",
    height: "56",
    x: "0",
    y: "0",
    maskUnits: "userSpaceOnUse"
  })), _g || (_g = /*#__PURE__*/React__default['default'].createElement("g", {
    mask: "url(#a)"
  })), children);
});

module.exports = CashBasedTransfersNegative;
