/**
 *
 * Code generated by @un/icon-build-helpers. DO NOT EDIT.
 * @un/icon-build-helpers is a fork of @carbon/icon-build-helpers
 * 
 */
'use strict';

var index = {
  "elem": "svg",
  "attrs": {
    "xmlns": "http://www.w3.org/2000/svg",
    "viewBox": "0 0 39 33",
    "fill": "currentColor",
    "width": "39",
    "height": "33"
  },
  "content": [{
    "elem": "path",
    "attrs": {
      "fill-rule": "evenodd",
      "d": "M25,33 L19.9,22.7 C19.8,22.4 19.4,22.5 19.4,22.8 L19.4,33 L0.2,33 L2.6,14.5 C2.7,14.1 2.9,13.7 3.2,13.4 L18.3,1.3 C18.9,0.8 19.8,0.8 20.4,1.3 L35.5,13.4 C35.8,13.7 36.1,14.1 36.1,14.5 L38.6,33 L25,33 Z"
    }
  }],
  "name": "wfp-hum--refugee-camp-pos"
};

module.exports = index;
