/**
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @un/icon-build-helpers. DO NOT EDIT.
 * @un/icon-build-helpers is a fork of @carbon/icon-build-helpers
 */
'use strict';

var Icon = require('../Icon-17378097.js');
var React = require('react');
require('@carbon/icon-helpers');
require('prop-types');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var React__default = /*#__PURE__*/_interopDefaultLegacy(React);

var _mask, _g, _path;

var _excluded = ["children"];
var GreenhouseGasEmissionsPositive = /*#__PURE__*/React__default['default'].forwardRef(function GreenhouseGasEmissionsPositive(_ref, ref) {
  var children = _ref.children,
      rest = Icon._objectWithoutProperties(_ref, _excluded);

  return /*#__PURE__*/React__default['default'].createElement(Icon.Icon, Icon._extends({
    width: 46,
    height: 30,
    viewBox: "0 0 46 30",
    xmlns: "http://www.w3.org/2000/svg",
    fill: "currentColor",
    ref: ref
  }, rest), _mask || (_mask = /*#__PURE__*/React__default['default'].createElement("mask", {
    id: "a",
    width: "46",
    height: "30",
    x: "0",
    y: "0",
    maskUnits: "userSpaceOnUse"
  })), _g || (_g = /*#__PURE__*/React__default['default'].createElement("g", {
    mask: "url(#a)"
  })), _path || (_path = /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M25.88 14.109C24.093 14.109 23.188 15.386 23.188 17.905C23.188 20.401 24.088 21.666 25.863 21.666C26.767 21.666 27.451 21.347 27.893 20.719C28.322 20.11 28.538 19.163 28.538 17.905C28.538 16.64 28.319 15.687 27.885 15.071C27.437 14.433 26.762 14.109 25.88 14.109Z",
    clipRule: "evenodd"
  })), children);
});

module.exports = GreenhouseGasEmissionsPositive;
