/**
 *
 * Code generated by @un/icon-build-helpers. DO NOT EDIT.
 * @un/icon-build-helpers is a fork of @carbon/icon-build-helpers
 * 
 */
'use strict';

var index = {
  "elem": "svg",
  "attrs": {
    "xmlns": "http://www.w3.org/2000/svg",
    "fill": "currentColor",
    "viewBox": "0 0 47 15",
    "width": "47",
    "height": "15"
  },
  "content": [{
    "elem": "mask",
    "attrs": {
      "id": "a",
      "width": "47",
      "height": "15",
      "x": "0",
      "y": "0",
      "maskUnits": "userSpaceOnUse"
    },
    "content": [{
      "elem": "path",
      "attrs": {
        "fill-rule": "evenodd",
        "d": "M0 0.862H46.021V15H0V0.862Z",
        "clip-rule": "evenodd"
      }
    }]
  }, {
    "elem": "g",
    "attrs": {
      "mask": "url(#a)"
    },
    "content": [{
      "elem": "path",
      "attrs": {
        "d": "M40.947.919983L38.067 10.916H37.989L35.052.919983H29.986V15H33.357V8.88498C33.357 7.92798 33.289 6.58598 33.154 4.85898H33.241L36.121 15H39.742L42.583 4.87798H42.67C42.593 6.40598 42.549 7.36598 42.54 7.75798 42.53 8.14998 42.526 8.50598 42.526 8.82598V15H46.022V.919983H40.947zM9.428.919983L7.474 8.09498C7.371 8.47998 7.252 9.00998 7.117 9.68398 6.983 10.358 6.893 10.92 6.848 11.369 6.809 10.746 6.591 9.64198 6.193 8.05598L4.276.919983H0L4.594 15H9.072L13.685.919983H9.428zM18.65 9.241C19.235 7.032 19.611 5.552 19.781 4.801 19.951 4.05 20.066 3.511 20.123 3.183 20.188 3.536 20.322 4.12 20.524 4.936 20.726 5.751 20.897 6.416 21.038 6.929L21.646 9.241H18.65zM17.562.862L12.968 15H17.147L17.86 12.361H22.435L23.128 15H27.289L22.637.862H17.562z",
        "clip-rule": "evenodd"
      }
    }]
  }],
  "name": "vam (positive)"
};

module.exports = index;
