/**
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @un/icon-build-helpers. DO NOT EDIT.
 * @un/icon-build-helpers is a fork of @carbon/icon-build-helpers
 */
'use strict';

var Icon = require('../Icon-17378097.js');
var React = require('react');
require('@carbon/icon-helpers');
require('prop-types');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var React__default = /*#__PURE__*/_interopDefaultLegacy(React);

var _path, _mask, _g;

var _excluded = ["children"];
var LogisticsClusterNegative = /*#__PURE__*/React__default['default'].forwardRef(function LogisticsClusterNegative(_ref, ref) {
  var children = _ref.children,
      rest = Icon._objectWithoutProperties(_ref, _excluded);

  return /*#__PURE__*/React__default['default'].createElement(Icon.Icon, Icon._extends({
    width: 56,
    height: 56,
    viewBox: "0 0 56 56",
    xmlns: "http://www.w3.org/2000/svg",
    fill: "currentColor",
    ref: ref
  }, rest), _path || (_path = /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M34.72 37.0779C33.9645 37.0779 33.3534 37.688 33.3534 38.4435 33.3534 39.201 33.9645 39.8111 34.72 39.8111 35.4765 39.8111 36.0866 39.201 36.0866 38.4435 36.0866 37.688 35.4765 37.0779 34.72 37.0779zM46.1076 31.6115C46.1076 31.4573 46.09 31.3109 46.0536 31.1743 45.8522 30.3815 45.133 29.7891 44.2862 29.7891H36.0866C35.8311 29.7891 35.5855 29.8441 35.3674 29.9443H35.3576C34.72 30.2263 34.2641 30.8649 34.2641 31.6115V34.3447H46.1076V31.6115z",
    clipRule: "evenodd"
  })), _mask || (_mask = /*#__PURE__*/React__default['default'].createElement("mask", {
    id: "a",
    width: "56",
    height: "56",
    x: "0",
    y: "0",
    maskUnits: "userSpaceOnUse"
  })), _g || (_g = /*#__PURE__*/React__default['default'].createElement("g", {
    mask: "url(#a)"
  })), children);
});

module.exports = LogisticsClusterNegative;
