/**
 *
 * Code generated by @wfp/icon-build-helpers. DO NOT EDIT.
 * @wfp/icon-build-helpers is a fork of @carbon/icon-build-helpers
 */
'use strict';

var iconPropTypes = require('./iconPropTypes-dc77abf6.js');
var React = require('react');
require('@carbon/icon-helpers');
require('prop-types');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var React__default = /*#__PURE__*/_interopDefaultLegacy(React);

var _mask, _g, _mask2, _g2;

var _excluded = ["children", "size"];
var AirportPositive = /*#__PURE__*/React__default['default'].forwardRef(function AirportPositive(_ref, ref) {
  var children = _ref.children,
      _ref$size = _ref.size,
      size = _ref$size === void 0 ? 16 : _ref$size,
      rest = iconPropTypes._objectWithoutProperties(_ref, _excluded);

  if (size === "glyph" || size === "glyph" || size === "glyphpx") {
    return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
      width: size,
      height: size,
      ref: ref,
      xmlns: "http://www.w3.org/2000/svg",
      fill: "currentColor",
      viewBox: "0 0 41 41"
    }, rest), _mask || (_mask = /*#__PURE__*/React__default['default'].createElement("mask", {
      id: "a",
      width: "41",
      height: "41",
      x: "0",
      y: "0",
      maskUnits: "userSpaceOnUse"
    }, /*#__PURE__*/React__default['default'].createElement("path", {
      "fill-rule": "evenodd",
      d: "M0 0.536003H40.464V40.94H0V0.536003Z",
      "clip-rule": "evenodd"
    }))), _g || (_g = /*#__PURE__*/React__default['default'].createElement("g", {
      mask: "url(#a)"
    }, /*#__PURE__*/React__default['default'].createElement("path", {
      d: "M37.935 25.826C37.632 25.826 37.337 25.767 37.067 25.666L23.604 21.611V34.256L28.713 37.889C28.889 37.999 29.042 38.134 29.16 38.302C29.379 38.589 29.505 38.934 29.505 39.314C29.505 40.241 28.746 41 27.819 41C27.608 41 27.397 40.958 27.212 40.882L20.232 38.564L12.898 40.974C12.813 40.992 12.729 41 12.645 41C11.718 41 10.959 40.241 10.959 39.314C10.959 38.892 11.11 38.513 11.372 38.218C11.482 38.092 11.608 37.974 11.752 37.889L16.86 34.256V21.611L3.305 25.7C3.06 25.784 2.799 25.826 2.529 25.826C1.13 25.826 0 24.697 0 23.297C0 22.446 0.43 21.696 1.079 21.248L16.86 12.338V3.908C16.86 2.045 18.369 0.536003 20.232 0.536003C22.096 0.536003 23.604 2.045 23.604 3.908V12.338C23.604 12.338 39.107 21.055 39.115 21.063C39.916 21.485 40.464 22.327 40.464 23.297C40.464 24.697 39.334 25.826 37.935 25.826Z",
      "clip-rule": "evenodd"
    }))), children);
  }

  return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
    width: size,
    height: size,
    ref: ref,
    xmlns: "http://www.w3.org/2000/svg",
    fill: "currentColor",
    viewBox: "0 0 41 41"
  }, rest), _mask2 || (_mask2 = /*#__PURE__*/React__default['default'].createElement("mask", {
    id: "a",
    width: "41",
    height: "41",
    x: "0",
    y: "0",
    maskUnits: "userSpaceOnUse"
  }, /*#__PURE__*/React__default['default'].createElement("path", {
    "fill-rule": "evenodd",
    d: "M0 0.536003H40.464V40.94H0V0.536003Z",
    "clip-rule": "evenodd"
  }))), _g2 || (_g2 = /*#__PURE__*/React__default['default'].createElement("g", {
    mask: "url(#a)"
  }, /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M37.935 25.826C37.632 25.826 37.337 25.767 37.067 25.666L23.604 21.611V34.256L28.713 37.889C28.889 37.999 29.042 38.134 29.16 38.302C29.379 38.589 29.505 38.934 29.505 39.314C29.505 40.241 28.746 41 27.819 41C27.608 41 27.397 40.958 27.212 40.882L20.232 38.564L12.898 40.974C12.813 40.992 12.729 41 12.645 41C11.718 41 10.959 40.241 10.959 39.314C10.959 38.892 11.11 38.513 11.372 38.218C11.482 38.092 11.608 37.974 11.752 37.889L16.86 34.256V21.611L3.305 25.7C3.06 25.784 2.799 25.826 2.529 25.826C1.13 25.826 0 24.697 0 23.297C0 22.446 0.43 21.696 1.079 21.248L16.86 12.338V3.908C16.86 2.045 18.369 0.536003 20.232 0.536003C22.096 0.536003 23.604 2.045 23.604 3.908V12.338C23.604 12.338 39.107 21.055 39.115 21.063C39.916 21.485 40.464 22.327 40.464 23.297C40.464 24.697 39.334 25.826 37.935 25.826Z",
    "clip-rule": "evenodd"
  }))), children);
});
AirportPositive.propTypes = iconPropTypes.iconPropTypes;

module.exports = AirportPositive;
