/**
 *
 * Code generated by @wfp/icon-build-helpers. DO NOT EDIT.
 * @wfp/icon-build-helpers is a fork of @carbon/icon-build-helpers
 */
'use strict';

var iconPropTypes = require('./iconPropTypes-dc77abf6.js');
var React = require('react');
require('@carbon/icon-helpers');
require('prop-types');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var React__default = /*#__PURE__*/_interopDefaultLegacy(React);

var _mask, _g, _mask2, _g2;

var _excluded = ["children", "size"];
var AirportNegative = /*#__PURE__*/React__default['default'].forwardRef(function AirportNegative(_ref, ref) {
  var children = _ref.children,
      _ref$size = _ref.size,
      size = _ref$size === void 0 ? 16 : _ref$size,
      rest = iconPropTypes._objectWithoutProperties(_ref, _excluded);

  if (size === "glyph" || size === "glyph" || size === "glyphpx") {
    return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
      width: size,
      height: size,
      ref: ref,
      xmlns: "http://www.w3.org/2000/svg",
      fill: "currentColor",
      viewBox: "0 0 56 56"
    }, rest), _mask || (_mask = /*#__PURE__*/React__default['default'].createElement("mask", {
      id: "a",
      width: "56",
      height: "56",
      x: "0",
      y: "0",
      maskUnits: "userSpaceOnUse"
    }, /*#__PURE__*/React__default['default'].createElement("path", {
      "fill-rule": "evenodd",
      d: "M0 0H56V56H0V0Z",
      "clip-rule": "evenodd"
    }))), _g || (_g = /*#__PURE__*/React__default['default'].createElement("g", {
      mask: "url(#a)"
    }, /*#__PURE__*/React__default['default'].createElement("path", {
      d: "M45.4653 33.045C45.1664 33.045 44.8754 32.9861 44.609 32.8854L31.3267 28.8414V41.4551L36.3671 45.0791C36.5418 45.1878 36.6917 45.3225 36.8081 45.4911C37.0242 45.7774 37.1485 46.1215 37.1485 46.5006C37.1485 47.4253 36.3997 48.1814 35.4851 48.1814C35.277 48.1814 35.0688 48.1395 34.8863 48.0637L28 45.7514L20.7645 48.1565C20.6806 48.1734 20.5977 48.1814 20.5158 48.1814C19.6003 48.1814 18.8515 47.4253 18.8515 46.5006C18.8515 46.0796 19.0005 45.7006 19.2589 45.4073C19.3675 45.2806 19.4918 45.1629 19.6338 45.0791L24.6733 41.4551V28.8414L11.3002 32.9193C11.0595 33.0031 10.801 33.045 10.5347 33.045C9.15443 33.045 8.0396 31.9188 8.0396 30.5232C8.0396 29.6733 8.46383 28.9252 9.10412 28.4793L24.6733 19.5914V11.1812C24.6733 9.32386 26.162 7.8176 28 7.8176C29.839 7.8176 31.3267 9.32386 31.3267 11.1812V19.5914C31.3267 19.5914 46.6216 28.2858 46.6295 28.2948C47.4198 28.7147 47.9604 29.5556 47.9604 30.5232C47.9604 31.9188 46.8456 33.045 45.4653 33.045ZM53.6667 0H2.33325C1.04972 0 0 1.06137 0 2.35914V53.6409C0 54.9386 1.04972 56 2.33325 56H53.6667C54.9503 56 56 54.9386 56 53.6409V2.35914C56 1.06137 54.9503 0 53.6667 0Z",
      "clip-rule": "evenodd"
    }))), children);
  }

  return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
    width: size,
    height: size,
    ref: ref,
    xmlns: "http://www.w3.org/2000/svg",
    fill: "currentColor",
    viewBox: "0 0 56 56"
  }, rest), _mask2 || (_mask2 = /*#__PURE__*/React__default['default'].createElement("mask", {
    id: "a",
    width: "56",
    height: "56",
    x: "0",
    y: "0",
    maskUnits: "userSpaceOnUse"
  }, /*#__PURE__*/React__default['default'].createElement("path", {
    "fill-rule": "evenodd",
    d: "M0 0H56V56H0V0Z",
    "clip-rule": "evenodd"
  }))), _g2 || (_g2 = /*#__PURE__*/React__default['default'].createElement("g", {
    mask: "url(#a)"
  }, /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M45.4653 33.045C45.1664 33.045 44.8754 32.9861 44.609 32.8854L31.3267 28.8414V41.4551L36.3671 45.0791C36.5418 45.1878 36.6917 45.3225 36.8081 45.4911C37.0242 45.7774 37.1485 46.1215 37.1485 46.5006C37.1485 47.4253 36.3997 48.1814 35.4851 48.1814C35.277 48.1814 35.0688 48.1395 34.8863 48.0637L28 45.7514L20.7645 48.1565C20.6806 48.1734 20.5977 48.1814 20.5158 48.1814C19.6003 48.1814 18.8515 47.4253 18.8515 46.5006C18.8515 46.0796 19.0005 45.7006 19.2589 45.4073C19.3675 45.2806 19.4918 45.1629 19.6338 45.0791L24.6733 41.4551V28.8414L11.3002 32.9193C11.0595 33.0031 10.801 33.045 10.5347 33.045C9.15443 33.045 8.0396 31.9188 8.0396 30.5232C8.0396 29.6733 8.46383 28.9252 9.10412 28.4793L24.6733 19.5914V11.1812C24.6733 9.32386 26.162 7.8176 28 7.8176C29.839 7.8176 31.3267 9.32386 31.3267 11.1812V19.5914C31.3267 19.5914 46.6216 28.2858 46.6295 28.2948C47.4198 28.7147 47.9604 29.5556 47.9604 30.5232C47.9604 31.9188 46.8456 33.045 45.4653 33.045ZM53.6667 0H2.33325C1.04972 0 0 1.06137 0 2.35914V53.6409C0 54.9386 1.04972 56 2.33325 56H53.6667C54.9503 56 56 54.9386 56 53.6409V2.35914C56 1.06137 54.9503 0 53.6667 0Z",
    "clip-rule": "evenodd"
  }))), children);
});
AirportNegative.propTypes = iconPropTypes.iconPropTypes;

module.exports = AirportNegative;
