/**
 *
 * Code generated by @wfp/icon-build-helpers. DO NOT EDIT.
 * @wfp/icon-build-helpers is a fork of @carbon/icon-build-helpers
 */
'use strict';

var iconPropTypes = require('./iconPropTypes-dc77abf6.js');
var React = require('react');
require('@carbon/icon-helpers');
require('prop-types');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var React__default = /*#__PURE__*/_interopDefaultLegacy(React);

var _mask, _g, _mask2, _g2;

var _excluded = ["children", "size"];
var ConflictPositive = /*#__PURE__*/React__default['default'].forwardRef(function ConflictPositive(_ref, ref) {
  var children = _ref.children,
      _ref$size = _ref.size,
      size = _ref$size === void 0 ? 16 : _ref$size,
      rest = iconPropTypes._objectWithoutProperties(_ref, _excluded);

  if (size === "glyph" || size === "glyph" || size === "glyphpx") {
    return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
      width: size,
      height: size,
      ref: ref,
      xmlns: "http://www.w3.org/2000/svg",
      fill: "currentColor",
      viewBox: "0 0 39 39"
    }, rest), _mask || (_mask = /*#__PURE__*/React__default['default'].createElement("mask", {
      id: "a",
      width: "39",
      height: "39",
      x: "0",
      y: "0",
      maskUnits: "userSpaceOnUse"
    }, /*#__PURE__*/React__default['default'].createElement("path", {
      "fill-rule": "evenodd",
      d: "M0.0599976 0.559006H38.44V39H0.0599976V0.559006Z",
      "clip-rule": "evenodd"
    }))), _g || (_g = /*#__PURE__*/React__default['default'].createElement("g", {
      mask: "url(#a)"
    }, /*#__PURE__*/React__default['default'].createElement("path", {
      d: "M38.44 19.774C38.44 21.097 37.297 22.17 35.885 22.17H28.183C26.771 22.17 25.627 21.097 25.627 19.774C25.627 18.45 26.771 17.377 28.183 17.377H35.885C37.297 17.377 38.44 18.45 38.44 19.774ZM31.325 31.884C30.425 32.785 28.964 32.785 28.063 31.884L23.934 27.754C23.033 26.854 23.033 25.394 23.934 24.493C24.834 23.592 26.295 23.592 27.195 24.493L31.325 28.622C32.225 29.523 32.225 30.984 31.325 31.884ZM23.9 11.837L26.495 9.243C27.395 8.342 28.856 8.342 29.757 9.243C30.657 10.144 30.657 11.604 29.757 12.505L27.092 15.1C26.191 16.001 24.801 16.001 23.9 15.1C22.999 14.199 22.999 12.738 23.9 11.837ZM19.221 23.784C17.009 23.784 15.216 21.991 15.216 19.779C15.216 17.568 17.009 15.775 19.221 15.775C21.431 15.775 23.224 17.568 23.224 19.779C23.224 21.991 21.431 23.784 19.221 23.784ZM21.613 36.597C21.613 37.924 20.538 39 19.211 39C17.884 39 16.809 37.924 16.809 36.597V28.589C16.809 27.262 17.884 26.187 19.211 26.187C20.538 26.187 21.613 27.262 21.613 28.589V36.597ZM14.541 27.721L7.14099 35.121C6.23999 36.022 4.77999 36.022 3.87899 35.121C2.97799 34.22 2.97799 32.76 3.87899 31.859L11.278 24.459C12.18 23.559 13.639 23.559 14.541 24.459C15.441 25.36 15.441 26.82 14.541 27.721ZM12.813 19.77V19.79C12.813 21.111 11.742 22.182 10.421 22.182H5.59599C4.27399 22.182 3.20299 21.111 3.20299 19.79V19.77C3.20299 18.448 4.27399 17.377 5.59599 17.377H10.421C11.742 17.377 12.813 18.448 12.813 19.77ZM0.712988 1.272C1.66399 0.320996 3.20499 0.320996 4.15599 1.272L14.503 11.619C15.454 12.57 15.454 14.111 14.503 15.062C13.553 16.013 12.011 16.013 11.059 15.062L0.712988 4.715C-0.237012 3.765 -0.237012 2.223 0.712988 1.272ZM16.818 2.962C16.818 1.634 17.894 0.558996 19.221 0.558996C20.548 0.558996 21.623 1.634 21.623 2.962V10.97C21.623 12.297 20.548 13.372 19.221 13.372C17.894 13.372 16.818 12.297 16.818 10.97V2.962Z",
      "clip-rule": "evenodd"
    }))), children);
  }

  return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
    width: size,
    height: size,
    ref: ref,
    xmlns: "http://www.w3.org/2000/svg",
    fill: "currentColor",
    viewBox: "0 0 39 39"
  }, rest), _mask2 || (_mask2 = /*#__PURE__*/React__default['default'].createElement("mask", {
    id: "a",
    width: "39",
    height: "39",
    x: "0",
    y: "0",
    maskUnits: "userSpaceOnUse"
  }, /*#__PURE__*/React__default['default'].createElement("path", {
    "fill-rule": "evenodd",
    d: "M0.0599976 0.559006H38.44V39H0.0599976V0.559006Z",
    "clip-rule": "evenodd"
  }))), _g2 || (_g2 = /*#__PURE__*/React__default['default'].createElement("g", {
    mask: "url(#a)"
  }, /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M38.44 19.774C38.44 21.097 37.297 22.17 35.885 22.17H28.183C26.771 22.17 25.627 21.097 25.627 19.774C25.627 18.45 26.771 17.377 28.183 17.377H35.885C37.297 17.377 38.44 18.45 38.44 19.774ZM31.325 31.884C30.425 32.785 28.964 32.785 28.063 31.884L23.934 27.754C23.033 26.854 23.033 25.394 23.934 24.493C24.834 23.592 26.295 23.592 27.195 24.493L31.325 28.622C32.225 29.523 32.225 30.984 31.325 31.884ZM23.9 11.837L26.495 9.243C27.395 8.342 28.856 8.342 29.757 9.243C30.657 10.144 30.657 11.604 29.757 12.505L27.092 15.1C26.191 16.001 24.801 16.001 23.9 15.1C22.999 14.199 22.999 12.738 23.9 11.837ZM19.221 23.784C17.009 23.784 15.216 21.991 15.216 19.779C15.216 17.568 17.009 15.775 19.221 15.775C21.431 15.775 23.224 17.568 23.224 19.779C23.224 21.991 21.431 23.784 19.221 23.784ZM21.613 36.597C21.613 37.924 20.538 39 19.211 39C17.884 39 16.809 37.924 16.809 36.597V28.589C16.809 27.262 17.884 26.187 19.211 26.187C20.538 26.187 21.613 27.262 21.613 28.589V36.597ZM14.541 27.721L7.14099 35.121C6.23999 36.022 4.77999 36.022 3.87899 35.121C2.97799 34.22 2.97799 32.76 3.87899 31.859L11.278 24.459C12.18 23.559 13.639 23.559 14.541 24.459C15.441 25.36 15.441 26.82 14.541 27.721ZM12.813 19.77V19.79C12.813 21.111 11.742 22.182 10.421 22.182H5.59599C4.27399 22.182 3.20299 21.111 3.20299 19.79V19.77C3.20299 18.448 4.27399 17.377 5.59599 17.377H10.421C11.742 17.377 12.813 18.448 12.813 19.77ZM0.712988 1.272C1.66399 0.320996 3.20499 0.320996 4.15599 1.272L14.503 11.619C15.454 12.57 15.454 14.111 14.503 15.062C13.553 16.013 12.011 16.013 11.059 15.062L0.712988 4.715C-0.237012 3.765 -0.237012 2.223 0.712988 1.272ZM16.818 2.962C16.818 1.634 17.894 0.558996 19.221 0.558996C20.548 0.558996 21.623 1.634 21.623 2.962V10.97C21.623 12.297 20.548 13.372 19.221 13.372C17.894 13.372 16.818 12.297 16.818 10.97V2.962Z",
    "clip-rule": "evenodd"
  }))), children);
});
ConflictPositive.propTypes = iconPropTypes.iconPropTypes;

module.exports = ConflictPositive;
