/**
 *
 * Code generated by @wfp/icon-build-helpers. DO NOT EDIT.
 * @wfp/icon-build-helpers is a fork of @carbon/icon-build-helpers
 */
'use strict';

var iconPropTypes = require('./iconPropTypes-dc77abf6.js');
var React = require('react');
require('@carbon/icon-helpers');
require('prop-types');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var React__default = /*#__PURE__*/_interopDefaultLegacy(React);

var _mask, _g, _mask2, _g2;

var _excluded = ["children", "size"];
var DronePositive = /*#__PURE__*/React__default['default'].forwardRef(function DronePositive(_ref, ref) {
  var children = _ref.children,
      _ref$size = _ref.size,
      size = _ref$size === void 0 ? 16 : _ref$size,
      rest = iconPropTypes._objectWithoutProperties(_ref, _excluded);

  if (size === "glyph" || size === "glyph" || size === "glyphpx") {
    return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
      width: size,
      height: size,
      ref: ref,
      xmlns: "http://www.w3.org/2000/svg",
      fill: "currentColor",
      viewBox: "0 0 49 35"
    }, rest), _mask || (_mask = /*#__PURE__*/React__default['default'].createElement("mask", {
      id: "a",
      width: "49",
      height: "34",
      x: "0",
      y: "0",
      maskUnits: "userSpaceOnUse"
    }, /*#__PURE__*/React__default['default'].createElement("path", {
      "fill-rule": "evenodd",
      d: "M0 0.772995H48.5V34H0V0.772995Z",
      "clip-rule": "evenodd"
    }))), _g || (_g = /*#__PURE__*/React__default['default'].createElement("g", {
      mask: "url(#a)"
    }, /*#__PURE__*/React__default['default'].createElement("path", {
      d: "M48.5 33.065C48.5 33.749 47.789 34.201 47.17 33.911L29.91 25.835C28.992 25.406 28.406 24.484 28.406 23.47V23.392C28.406 22.893 28.003 22.488 27.504 22.484C27.41 23.715 26.633 24.756 25.551 25.228V25.28C25.551 25.844 25.193 26.322 24.692 26.503V27.232C24.966 27.348 25.187 27.568 25.302 27.843H28.406C28.65 27.843 28.847 28.041 28.847 28.285C28.847 28.528 28.65 28.726 28.406 28.726H25.302C25.129 29.137 24.724 29.426 24.25 29.426C23.777 29.426 23.37 29.137 23.198 28.726H20.094C19.85 28.726 19.653 28.528 19.653 28.285C19.653 28.041 19.85 27.843 20.094 27.843H23.198C23.314 27.568 23.533 27.348 23.808 27.232V26.503C23.307 26.322 22.948 25.844 22.948 25.28V25.228C21.867 24.756 21.09 23.715 20.995 22.484C20.497 22.488 20.094 22.893 20.094 23.392V23.47C20.094 24.484 19.507 25.406 18.589 25.835L1.329 33.911C0.71 34.201 0 33.749 0 33.065V28.994C0 26.372 1.041 23.857 2.896 22.003L17.467 7.432C18.389 6.51 19.126 5.406 19.537 4.169C20.195 2.196 22.056 0.772003 24.25 0.772003C26.445 0.772003 28.305 2.196 28.962 4.169C29.373 5.406 30.111 6.51 31.033 7.432L45.605 22.003C47.458 23.857 48.5 26.372 48.5 28.994V33.065Z",
      "clip-rule": "evenodd"
    }))), children);
  }

  return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
    width: size,
    height: size,
    ref: ref,
    xmlns: "http://www.w3.org/2000/svg",
    fill: "currentColor",
    viewBox: "0 0 49 35"
  }, rest), _mask2 || (_mask2 = /*#__PURE__*/React__default['default'].createElement("mask", {
    id: "a",
    width: "49",
    height: "34",
    x: "0",
    y: "0",
    maskUnits: "userSpaceOnUse"
  }, /*#__PURE__*/React__default['default'].createElement("path", {
    "fill-rule": "evenodd",
    d: "M0 0.772995H48.5V34H0V0.772995Z",
    "clip-rule": "evenodd"
  }))), _g2 || (_g2 = /*#__PURE__*/React__default['default'].createElement("g", {
    mask: "url(#a)"
  }, /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M48.5 33.065C48.5 33.749 47.789 34.201 47.17 33.911L29.91 25.835C28.992 25.406 28.406 24.484 28.406 23.47V23.392C28.406 22.893 28.003 22.488 27.504 22.484C27.41 23.715 26.633 24.756 25.551 25.228V25.28C25.551 25.844 25.193 26.322 24.692 26.503V27.232C24.966 27.348 25.187 27.568 25.302 27.843H28.406C28.65 27.843 28.847 28.041 28.847 28.285C28.847 28.528 28.65 28.726 28.406 28.726H25.302C25.129 29.137 24.724 29.426 24.25 29.426C23.777 29.426 23.37 29.137 23.198 28.726H20.094C19.85 28.726 19.653 28.528 19.653 28.285C19.653 28.041 19.85 27.843 20.094 27.843H23.198C23.314 27.568 23.533 27.348 23.808 27.232V26.503C23.307 26.322 22.948 25.844 22.948 25.28V25.228C21.867 24.756 21.09 23.715 20.995 22.484C20.497 22.488 20.094 22.893 20.094 23.392V23.47C20.094 24.484 19.507 25.406 18.589 25.835L1.329 33.911C0.71 34.201 0 33.749 0 33.065V28.994C0 26.372 1.041 23.857 2.896 22.003L17.467 7.432C18.389 6.51 19.126 5.406 19.537 4.169C20.195 2.196 22.056 0.772003 24.25 0.772003C26.445 0.772003 28.305 2.196 28.962 4.169C29.373 5.406 30.111 6.51 31.033 7.432L45.605 22.003C47.458 23.857 48.5 26.372 48.5 28.994V33.065Z",
    "clip-rule": "evenodd"
  }))), children);
});
DronePositive.propTypes = iconPropTypes.iconPropTypes;

module.exports = DronePositive;
