/**
 *
 * Code generated by @wfp/icon-build-helpers. DO NOT EDIT.
 * @wfp/icon-build-helpers is a fork of @carbon/icon-build-helpers
 */
'use strict';

var iconPropTypes = require('./iconPropTypes-dc77abf6.js');
var React = require('react');
require('@carbon/icon-helpers');
require('prop-types');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var React__default = /*#__PURE__*/_interopDefaultLegacy(React);

var _mask, _g, _mask2, _g2;

var _excluded = ["children", "size"];
var EarthquakePositive = /*#__PURE__*/React__default['default'].forwardRef(function EarthquakePositive(_ref, ref) {
  var children = _ref.children,
      _ref$size = _ref.size,
      size = _ref$size === void 0 ? 16 : _ref$size,
      rest = iconPropTypes._objectWithoutProperties(_ref, _excluded);

  if (size === "glyph" || size === "glyph" || size === "glyphpx") {
    return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
      width: size,
      height: size,
      ref: ref,
      xmlns: "http://www.w3.org/2000/svg",
      fill: "currentColor",
      viewBox: "0 0 34 41"
    }, rest), _mask || (_mask = /*#__PURE__*/React__default['default'].createElement("mask", {
      id: "a",
      style: "mask-type:alpha",
      width: "34",
      height: "41",
      x: "0",
      y: "0",
      maskUnits: "userSpaceOnUse"
    }, /*#__PURE__*/React__default['default'].createElement("path", {
      "fill-rule": "evenodd",
      d: "M0.0600586 0.535995H33.7201V40.94H0.0600586V0.535995Z",
      "clip-rule": "evenodd"
    }))), _g || (_g = /*#__PURE__*/React__default['default'].createElement("g", {
      mask: "url(#a)"
    }, /*#__PURE__*/React__default['default'].createElement("path", {
      d: "M33.72 40.157C33.72 40.621 33.341 41 32.877 41H16.708L23.106 34.602C23.436 34.281 23.612 33.835 23.604 33.371C23.596 32.907 23.393 32.469 23.048 32.157L16.042 25.86L20.485 22.049C20.839 21.746 21.059 21.299 21.075 20.836C21.092 20.363 20.915 19.908 20.578 19.58L17.56 16.553L19.734 14.37C20.4 13.712 20.4 12.65 19.734 11.992C19.077 11.326 18.015 11.326 17.357 11.992L13.985 15.364C13.319 16.022 13.319 17.084 13.985 17.742L16.911 20.675L12.393 24.545C12.021 24.865 11.81 25.32 11.802 25.809C11.794 26.29 11.996 26.753 12.358 27.082L19.465 33.481L11.954 41H0.843C0.38 41 0 40.621 0 40.157V16.57C0 16.258 0.127 15.954 0.362 15.744L16.278 0.763995C16.607 0.459995 17.113 0.459995 17.441 0.763995L33.357 15.744C33.594 15.954 33.72 16.258 33.72 16.57V40.157Z",
      "clip-rule": "evenodd"
    }))), children);
  }

  return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
    width: size,
    height: size,
    ref: ref,
    xmlns: "http://www.w3.org/2000/svg",
    fill: "currentColor",
    viewBox: "0 0 34 41"
  }, rest), _mask2 || (_mask2 = /*#__PURE__*/React__default['default'].createElement("mask", {
    id: "a",
    style: "mask-type:alpha",
    width: "34",
    height: "41",
    x: "0",
    y: "0",
    maskUnits: "userSpaceOnUse"
  }, /*#__PURE__*/React__default['default'].createElement("path", {
    "fill-rule": "evenodd",
    d: "M0.0600586 0.535995H33.7201V40.94H0.0600586V0.535995Z",
    "clip-rule": "evenodd"
  }))), _g2 || (_g2 = /*#__PURE__*/React__default['default'].createElement("g", {
    mask: "url(#a)"
  }, /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M33.72 40.157C33.72 40.621 33.341 41 32.877 41H16.708L23.106 34.602C23.436 34.281 23.612 33.835 23.604 33.371C23.596 32.907 23.393 32.469 23.048 32.157L16.042 25.86L20.485 22.049C20.839 21.746 21.059 21.299 21.075 20.836C21.092 20.363 20.915 19.908 20.578 19.58L17.56 16.553L19.734 14.37C20.4 13.712 20.4 12.65 19.734 11.992C19.077 11.326 18.015 11.326 17.357 11.992L13.985 15.364C13.319 16.022 13.319 17.084 13.985 17.742L16.911 20.675L12.393 24.545C12.021 24.865 11.81 25.32 11.802 25.809C11.794 26.29 11.996 26.753 12.358 27.082L19.465 33.481L11.954 41H0.843C0.38 41 0 40.621 0 40.157V16.57C0 16.258 0.127 15.954 0.362 15.744L16.278 0.763995C16.607 0.459995 17.113 0.459995 17.441 0.763995L33.357 15.744C33.594 15.954 33.72 16.258 33.72 16.57V40.157Z",
    "clip-rule": "evenodd"
  }))), children);
});
EarthquakePositive.propTypes = iconPropTypes.iconPropTypes;

module.exports = EarthquakePositive;
