/**
 *
 * Code generated by @wfp/icon-build-helpers. DO NOT EDIT.
 * @wfp/icon-build-helpers is a fork of @carbon/icon-build-helpers
 */
'use strict';

var iconPropTypes = require('./iconPropTypes-dc77abf6.js');
var React = require('react');
require('@carbon/icon-helpers');
require('prop-types');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var React__default = /*#__PURE__*/_interopDefaultLegacy(React);

var _mask, _g, _mask2, _g2;

var _excluded = ["children", "size"];
var EarthquakeNegative = /*#__PURE__*/React__default['default'].forwardRef(function EarthquakeNegative(_ref, ref) {
  var children = _ref.children,
      _ref$size = _ref.size,
      size = _ref$size === void 0 ? 16 : _ref$size,
      rest = iconPropTypes._objectWithoutProperties(_ref, _excluded);

  if (size === "glyph" || size === "glyph" || size === "glyphpx") {
    return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
      width: size,
      height: size,
      ref: ref,
      xmlns: "http://www.w3.org/2000/svg",
      fill: "currentColor",
      viewBox: "0 0 56 56"
    }, rest), _mask || (_mask = /*#__PURE__*/React__default['default'].createElement("mask", {
      id: "a",
      style: "mask-type:alpha",
      width: "56",
      height: "56",
      x: "0",
      y: "0",
      maskUnits: "userSpaceOnUse"
    }, /*#__PURE__*/React__default['default'].createElement("path", {
      "fill-rule": "evenodd",
      d: "M0 0H56V56H0V0Z",
      "clip-rule": "evenodd"
    }))), _g || (_g = /*#__PURE__*/React__default['default'].createElement("g", {
      mask: "url(#a)"
    }, /*#__PURE__*/React__default['default'].createElement("path", {
      d: "M44.6337 46.3689C44.6337 46.8308 44.2598 47.2088 43.802 47.2088H27.85L34.1622 40.8267C34.4877 40.5075 34.6614 40.0616 34.6544 39.5997C34.6456 39.1369 34.4463 38.6989 34.1049 38.3887L27.193 32.1063L31.5763 28.3057C31.9256 28.0035 32.1426 27.5566 32.1584 27.0947C32.1752 26.6239 32.0006 26.17 31.6681 25.8419L28.6906 22.8224L30.8354 20.6448C31.4925 19.9884 31.4925 18.929 30.8354 18.2736C30.1872 17.6093 29.1395 17.6093 28.4903 18.2736L25.1636 21.6373C24.5065 22.2927 24.5065 23.352 25.1636 24.0084L28.0503 26.9351L23.593 30.7946C23.226 31.1148 23.0188 31.5686 23.0099 32.0564C23.002 32.5362 23.2013 32.9981 23.5584 33.3263L30.57 39.7084L23.1599 47.2088H12.198C11.7412 47.2088 11.3663 46.8308 11.3663 46.3689V22.8393C11.3663 22.5281 11.4916 22.2258 11.7235 22.0154L27.4258 7.07245C27.7504 6.7692 28.2496 6.7692 28.5732 7.07245L44.2755 22.0154C44.5094 22.2258 44.6337 22.5281 44.6337 22.8393V46.3689ZM53.6667 0H2.33325C1.04972 0 0 1.06137 0 2.35914V53.6409C0 54.9386 1.04972 56 2.33325 56H53.6667C54.9503 56 56 54.9386 56 53.6409V2.35914C56 1.06137 54.9503 0 53.6667 0Z",
      "clip-rule": "evenodd"
    }))), children);
  }

  return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
    width: size,
    height: size,
    ref: ref,
    xmlns: "http://www.w3.org/2000/svg",
    fill: "currentColor",
    viewBox: "0 0 56 56"
  }, rest), _mask2 || (_mask2 = /*#__PURE__*/React__default['default'].createElement("mask", {
    id: "a",
    style: "mask-type:alpha",
    width: "56",
    height: "56",
    x: "0",
    y: "0",
    maskUnits: "userSpaceOnUse"
  }, /*#__PURE__*/React__default['default'].createElement("path", {
    "fill-rule": "evenodd",
    d: "M0 0H56V56H0V0Z",
    "clip-rule": "evenodd"
  }))), _g2 || (_g2 = /*#__PURE__*/React__default['default'].createElement("g", {
    mask: "url(#a)"
  }, /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M44.6337 46.3689C44.6337 46.8308 44.2598 47.2088 43.802 47.2088H27.85L34.1622 40.8267C34.4877 40.5075 34.6614 40.0616 34.6544 39.5997C34.6456 39.1369 34.4463 38.6989 34.1049 38.3887L27.193 32.1063L31.5763 28.3057C31.9256 28.0035 32.1426 27.5566 32.1584 27.0947C32.1752 26.6239 32.0006 26.17 31.6681 25.8419L28.6906 22.8224L30.8354 20.6448C31.4925 19.9884 31.4925 18.929 30.8354 18.2736C30.1872 17.6093 29.1395 17.6093 28.4903 18.2736L25.1636 21.6373C24.5065 22.2927 24.5065 23.352 25.1636 24.0084L28.0503 26.9351L23.593 30.7946C23.226 31.1148 23.0188 31.5686 23.0099 32.0564C23.002 32.5362 23.2013 32.9981 23.5584 33.3263L30.57 39.7084L23.1599 47.2088H12.198C11.7412 47.2088 11.3663 46.8308 11.3663 46.3689V22.8393C11.3663 22.5281 11.4916 22.2258 11.7235 22.0154L27.4258 7.07245C27.7504 6.7692 28.2496 6.7692 28.5732 7.07245L44.2755 22.0154C44.5094 22.2258 44.6337 22.5281 44.6337 22.8393V46.3689ZM53.6667 0H2.33325C1.04972 0 0 1.06137 0 2.35914V53.6409C0 54.9386 1.04972 56 2.33325 56H53.6667C54.9503 56 56 54.9386 56 53.6409V2.35914C56 1.06137 54.9503 0 53.6667 0Z",
    "clip-rule": "evenodd"
  }))), children);
});
EarthquakeNegative.propTypes = iconPropTypes.iconPropTypes;

module.exports = EarthquakeNegative;
