/**
 *
 * Code generated by @wfp/icon-build-helpers. DO NOT EDIT.
 * @wfp/icon-build-helpers is a fork of @carbon/icon-build-helpers
 */
'use strict';

var iconPropTypes = require('./iconPropTypes-dc77abf6.js');
var React = require('react');
require('@carbon/icon-helpers');
require('prop-types');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var React__default = /*#__PURE__*/_interopDefaultLegacy(React);

var _mask, _g, _mask2, _g2;

var _excluded = ["children", "size"];
var EmailContactPositive = /*#__PURE__*/React__default['default'].forwardRef(function EmailContactPositive(_ref, ref) {
  var children = _ref.children,
      _ref$size = _ref.size,
      size = _ref$size === void 0 ? 16 : _ref$size,
      rest = iconPropTypes._objectWithoutProperties(_ref, _excluded);

  if (size === "glyph" || size === "glyph" || size === "glyphpx") {
    return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
      width: size,
      height: size,
      ref: ref,
      xmlns: "http://www.w3.org/2000/svg",
      fill: "currentColor",
      viewBox: "0 0 39 24"
    }, rest), _mask || (_mask = /*#__PURE__*/React__default['default'].createElement("mask", {
      id: "a",
      width: "39",
      height: "24",
      x: "0",
      y: "0",
      maskUnits: "userSpaceOnUse"
    }, /*#__PURE__*/React__default['default'].createElement("path", {
      "fill-rule": "evenodd",
      d: "M0 0H38.38V23.965H0V0Z",
      "clip-rule": "evenodd"
    }))), _g || (_g = /*#__PURE__*/React__default['default'].createElement("g", {
      mask: "url(#a)"
    }, /*#__PURE__*/React__default['default'].createElement("path", {
      d: "M35.39 5.293L20.174 16.505C19.885 16.714 19.557 16.817 19.221 16.817C18.884 16.817 18.556 16.714 18.268 16.505L3.051 5.293C2.339 4.772 2.187 3.764 2.715 3.051C3.243 2.338 4.244 2.194 4.957 2.715L19.221 13.229L33.484 2.715C34.196 2.194 35.197 2.338 35.726 3.051C36.255 3.764 36.103 4.772 35.39 5.293ZM35.654 21.062C35.334 21.43 34.885 21.622 34.437 21.622C34.068 21.622 33.7 21.494 33.396 21.238L27.789 16.433C27.117 15.856 27.037 14.848 27.613 14.175C28.19 13.502 29.199 13.422 29.872 13.998L35.478 18.804C36.15 19.38 36.23 20.39 35.654 21.062ZM10.651 16.433L5.045 21.238C4.741 21.494 4.373 21.622 4.004 21.622C3.556 21.622 3.107 21.43 2.787 21.062C2.21 20.39 2.29 19.38 2.963 18.804L8.569 13.998C9.242 13.422 10.251 13.502 10.827 14.175C11.404 14.848 11.324 15.856 10.651 16.433ZM36.839 0H1.602C0.721 0 0 0.721 0 1.601V22.423C0 23.305 0.721 24.025 1.602 24.025H36.839C37.72 24.025 38.44 23.305 38.44 22.423V1.601C38.44 0.721 37.72 0 36.839 0Z",
      "clip-rule": "evenodd"
    }))), children);
  }

  return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
    width: size,
    height: size,
    ref: ref,
    xmlns: "http://www.w3.org/2000/svg",
    fill: "currentColor",
    viewBox: "0 0 39 24"
  }, rest), _mask2 || (_mask2 = /*#__PURE__*/React__default['default'].createElement("mask", {
    id: "a",
    width: "39",
    height: "24",
    x: "0",
    y: "0",
    maskUnits: "userSpaceOnUse"
  }, /*#__PURE__*/React__default['default'].createElement("path", {
    "fill-rule": "evenodd",
    d: "M0 0H38.38V23.965H0V0Z",
    "clip-rule": "evenodd"
  }))), _g2 || (_g2 = /*#__PURE__*/React__default['default'].createElement("g", {
    mask: "url(#a)"
  }, /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M35.39 5.293L20.174 16.505C19.885 16.714 19.557 16.817 19.221 16.817C18.884 16.817 18.556 16.714 18.268 16.505L3.051 5.293C2.339 4.772 2.187 3.764 2.715 3.051C3.243 2.338 4.244 2.194 4.957 2.715L19.221 13.229L33.484 2.715C34.196 2.194 35.197 2.338 35.726 3.051C36.255 3.764 36.103 4.772 35.39 5.293ZM35.654 21.062C35.334 21.43 34.885 21.622 34.437 21.622C34.068 21.622 33.7 21.494 33.396 21.238L27.789 16.433C27.117 15.856 27.037 14.848 27.613 14.175C28.19 13.502 29.199 13.422 29.872 13.998L35.478 18.804C36.15 19.38 36.23 20.39 35.654 21.062ZM10.651 16.433L5.045 21.238C4.741 21.494 4.373 21.622 4.004 21.622C3.556 21.622 3.107 21.43 2.787 21.062C2.21 20.39 2.29 19.38 2.963 18.804L8.569 13.998C9.242 13.422 10.251 13.502 10.827 14.175C11.404 14.848 11.324 15.856 10.651 16.433ZM36.839 0H1.602C0.721 0 0 0.721 0 1.601V22.423C0 23.305 0.721 24.025 1.602 24.025H36.839C37.72 24.025 38.44 23.305 38.44 22.423V1.601C38.44 0.721 37.72 0 36.839 0Z",
    "clip-rule": "evenodd"
  }))), children);
});
EmailContactPositive.propTypes = iconPropTypes.iconPropTypes;

module.exports = EmailContactPositive;
