/**
 *
 * Code generated by @wfp/icon-build-helpers. DO NOT EDIT.
 * @wfp/icon-build-helpers is a fork of @carbon/icon-build-helpers
 */
'use strict';

var iconPropTypes = require('./iconPropTypes-dc77abf6.js');
var React = require('react');
require('@carbon/icon-helpers');
require('prop-types');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var React__default = /*#__PURE__*/_interopDefaultLegacy(React);

var _mask, _g, _mask2, _g2;

var _excluded = ["children", "size"];
var EmergencyTelecommunicationsClusterNegative = /*#__PURE__*/React__default['default'].forwardRef(function EmergencyTelecommunicationsClusterNegative(_ref, ref) {
  var children = _ref.children,
      _ref$size = _ref.size,
      size = _ref$size === void 0 ? 16 : _ref$size,
      rest = iconPropTypes._objectWithoutProperties(_ref, _excluded);

  if (size === "glyph" || size === "glyph" || size === "glyphpx") {
    return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
      width: size,
      height: size,
      ref: ref,
      xmlns: "http://www.w3.org/2000/svg",
      fill: "currentColor",
      viewBox: "0 0 56 56"
    }, rest), _mask || (_mask = /*#__PURE__*/React__default['default'].createElement("mask", {
      id: "a",
      width: "56",
      height: "56",
      x: "0",
      y: "0",
      maskUnits: "userSpaceOnUse"
    }, /*#__PURE__*/React__default['default'].createElement("path", {
      "fill-rule": "evenodd",
      d: "M0 0H56V56H0V0Z",
      "clip-rule": "evenodd"
    }))), _g || (_g = /*#__PURE__*/React__default['default'].createElement("g", {
      mask: "url(#a)"
    }, /*#__PURE__*/React__default['default'].createElement("path", {
      d: "M40.9458 23.378C40.348 24.2169 39.3407 24.4074 38.8711 23.9007C38.3985 23.3929 38.4774 22.5311 38.9214 21.9036C41.1599 18.7674 41.1599 14.504 38.9214 11.3668C38.4784 10.7403 38.3985 9.87848 38.8711 9.36974C39.3407 8.863 40.348 9.05453 40.9458 9.89245C43.8118 13.9065 43.8118 19.3639 40.9458 23.378ZM38.1134 46.9086H18.154C17.2345 46.9086 16.4896 46.1554 16.4896 45.2267C16.4896 44.298 17.2345 43.5449 18.154 43.5449H26.4708V19.5774C26.4708 19.5634 26.4738 19.5495 26.4757 19.5345C25.4832 18.953 24.8074 17.8796 24.8074 16.6357C24.8074 14.7773 26.2972 13.2721 28.1342 13.2721C29.9712 13.2721 31.4609 14.7773 31.4609 16.6357C31.4609 17.8786 30.7861 18.953 29.7936 19.5345C29.7936 19.5495 29.7975 19.5634 29.7975 19.5774V43.5449H38.1134C39.0329 43.5449 39.7777 44.298 39.7777 45.2267C39.7777 46.1554 39.0329 46.9086 38.1134 46.9086ZM15.3225 9.89245C15.9194 9.05453 16.9267 8.863 17.3963 9.36974C17.8708 9.87848 17.7899 10.7393 17.347 11.3668C15.1074 14.504 15.1074 18.7674 17.347 21.9036C17.7899 22.5311 17.8708 23.3929 17.3963 23.9007C16.9267 24.4074 15.9194 24.2169 15.3225 23.378C12.4565 19.3639 12.4565 13.9065 15.3225 9.89245ZM20.354 11.669C20.946 10.7344 22.0066 10.4999 22.4693 11.0127C22.9379 11.5264 22.855 12.3873 22.4554 13.0287C21.0663 15.2202 21.0663 18.0512 22.4554 20.2428C22.855 20.8842 22.9379 21.745 22.4693 22.2578C22.0066 22.7705 20.945 22.5371 20.354 21.6024C18.4401 18.5849 18.4401 14.6865 20.354 11.669ZM33.729 13.0287C33.3305 12.3873 33.2456 11.5264 33.7142 11.0127C34.1789 10.5009 35.2385 10.7344 35.8305 11.669C37.7444 14.6865 37.7444 18.5849 35.8305 21.6024C35.2395 22.5371 34.1789 22.7705 33.7142 22.2578C33.2466 21.745 33.3305 20.8842 33.729 20.2428C35.1181 18.0512 35.1181 15.2202 33.729 13.0287ZM53.6667 0H2.33325C1.04972 0 0 1.06137 0 2.35914V53.6409C0 54.9386 1.04972 56 2.33325 56H53.6667C54.9503 56 56 54.9386 56 53.6409V2.35914C56 1.06137 54.9503 0 53.6667 0Z",
      "clip-rule": "evenodd"
    }))), children);
  }

  return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
    width: size,
    height: size,
    ref: ref,
    xmlns: "http://www.w3.org/2000/svg",
    fill: "currentColor",
    viewBox: "0 0 56 56"
  }, rest), _mask2 || (_mask2 = /*#__PURE__*/React__default['default'].createElement("mask", {
    id: "a",
    width: "56",
    height: "56",
    x: "0",
    y: "0",
    maskUnits: "userSpaceOnUse"
  }, /*#__PURE__*/React__default['default'].createElement("path", {
    "fill-rule": "evenodd",
    d: "M0 0H56V56H0V0Z",
    "clip-rule": "evenodd"
  }))), _g2 || (_g2 = /*#__PURE__*/React__default['default'].createElement("g", {
    mask: "url(#a)"
  }, /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M40.9458 23.378C40.348 24.2169 39.3407 24.4074 38.8711 23.9007C38.3985 23.3929 38.4774 22.5311 38.9214 21.9036C41.1599 18.7674 41.1599 14.504 38.9214 11.3668C38.4784 10.7403 38.3985 9.87848 38.8711 9.36974C39.3407 8.863 40.348 9.05453 40.9458 9.89245C43.8118 13.9065 43.8118 19.3639 40.9458 23.378ZM38.1134 46.9086H18.154C17.2345 46.9086 16.4896 46.1554 16.4896 45.2267C16.4896 44.298 17.2345 43.5449 18.154 43.5449H26.4708V19.5774C26.4708 19.5634 26.4738 19.5495 26.4757 19.5345C25.4832 18.953 24.8074 17.8796 24.8074 16.6357C24.8074 14.7773 26.2972 13.2721 28.1342 13.2721C29.9712 13.2721 31.4609 14.7773 31.4609 16.6357C31.4609 17.8786 30.7861 18.953 29.7936 19.5345C29.7936 19.5495 29.7975 19.5634 29.7975 19.5774V43.5449H38.1134C39.0329 43.5449 39.7777 44.298 39.7777 45.2267C39.7777 46.1554 39.0329 46.9086 38.1134 46.9086ZM15.3225 9.89245C15.9194 9.05453 16.9267 8.863 17.3963 9.36974C17.8708 9.87848 17.7899 10.7393 17.347 11.3668C15.1074 14.504 15.1074 18.7674 17.347 21.9036C17.7899 22.5311 17.8708 23.3929 17.3963 23.9007C16.9267 24.4074 15.9194 24.2169 15.3225 23.378C12.4565 19.3639 12.4565 13.9065 15.3225 9.89245ZM20.354 11.669C20.946 10.7344 22.0066 10.4999 22.4693 11.0127C22.9379 11.5264 22.855 12.3873 22.4554 13.0287C21.0663 15.2202 21.0663 18.0512 22.4554 20.2428C22.855 20.8842 22.9379 21.745 22.4693 22.2578C22.0066 22.7705 20.945 22.5371 20.354 21.6024C18.4401 18.5849 18.4401 14.6865 20.354 11.669ZM33.729 13.0287C33.3305 12.3873 33.2456 11.5264 33.7142 11.0127C34.1789 10.5009 35.2385 10.7344 35.8305 11.669C37.7444 14.6865 37.7444 18.5849 35.8305 21.6024C35.2395 22.5371 34.1789 22.7705 33.7142 22.2578C33.2466 21.745 33.3305 20.8842 33.729 20.2428C35.1181 18.0512 35.1181 15.2202 33.729 13.0287ZM53.6667 0H2.33325C1.04972 0 0 1.06137 0 2.35914V53.6409C0 54.9386 1.04972 56 2.33325 56H53.6667C54.9503 56 56 54.9386 56 53.6409V2.35914C56 1.06137 54.9503 0 53.6667 0Z",
    "clip-rule": "evenodd"
  }))), children);
});
EmergencyTelecommunicationsClusterNegative.propTypes = iconPropTypes.iconPropTypes;

module.exports = EmergencyTelecommunicationsClusterNegative;
