/**
 *
 * Code generated by @wfp/icon-build-helpers. DO NOT EDIT.
 * @wfp/icon-build-helpers is a fork of @carbon/icon-build-helpers
 */
'use strict';

var iconPropTypes = require('./iconPropTypes-dc77abf6.js');
var React = require('react');
require('@carbon/icon-helpers');
require('prop-types');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var React__default = /*#__PURE__*/_interopDefaultLegacy(React);

var _path, _path2;

var _excluded = ["children", "size"];
var FoodPositive = /*#__PURE__*/React__default['default'].forwardRef(function FoodPositive(_ref, ref) {
  var children = _ref.children,
      _ref$size = _ref.size,
      size = _ref$size === void 0 ? 16 : _ref$size,
      rest = iconPropTypes._objectWithoutProperties(_ref, _excluded);

  if (size === "glyph" || size === "glyph" || size === "glyphpx") {
    return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
      width: size,
      height: size,
      ref: ref,
      xmlns: "http://www.w3.org/2000/svg",
      fill: "currentColor",
      viewBox: "0 0 41 28"
    }, rest), _path || (_path = /*#__PURE__*/React__default['default'].createElement("path", {
      d: "M37.252 24.607C35.271 26.588 32.531 27.819 29.505 27.819H10.959C4.906 27.819 0 22.913 0 16.86H40.464C40.464 19.887 39.233 22.626 37.252 24.607ZM6.761 8.43C6.763 8.43 6.764 8.43 6.766 8.43C6.981 5.601 9.34 3.372 12.223 3.372C13.102 3.372 13.931 3.584 14.668 3.952C15.473 1.652 17.657 0 20.232 0C22.808 0 24.991 1.652 25.797 3.952C26.533 3.584 27.361 3.372 28.241 3.372C31.125 3.372 33.483 5.601 33.699 8.43C33.7 8.43 33.702 8.43 33.703 8.43C36.974 8.43 39.621 11.069 39.621 14.331H0.843C0.843 11.069 3.49 8.43 6.761 8.43Z",
      "clip-rule": "evenodd"
    })), children);
  }

  return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
    width: size,
    height: size,
    ref: ref,
    xmlns: "http://www.w3.org/2000/svg",
    fill: "currentColor",
    viewBox: "0 0 41 28"
  }, rest), _path2 || (_path2 = /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M37.252 24.607C35.271 26.588 32.531 27.819 29.505 27.819H10.959C4.906 27.819 0 22.913 0 16.86H40.464C40.464 19.887 39.233 22.626 37.252 24.607ZM6.761 8.43C6.763 8.43 6.764 8.43 6.766 8.43C6.981 5.601 9.34 3.372 12.223 3.372C13.102 3.372 13.931 3.584 14.668 3.952C15.473 1.652 17.657 0 20.232 0C22.808 0 24.991 1.652 25.797 3.952C26.533 3.584 27.361 3.372 28.241 3.372C31.125 3.372 33.483 5.601 33.699 8.43C33.7 8.43 33.702 8.43 33.703 8.43C36.974 8.43 39.621 11.069 39.621 14.331H0.843C0.843 11.069 3.49 8.43 6.761 8.43Z",
    "clip-rule": "evenodd"
  })), children);
});
FoodPositive.propTypes = iconPropTypes.iconPropTypes;

module.exports = FoodPositive;
