/**
 *
 * Code generated by @wfp/icon-build-helpers. DO NOT EDIT.
 * @wfp/icon-build-helpers is a fork of @carbon/icon-build-helpers
 */
'use strict';

var iconPropTypes = require('./iconPropTypes-dc77abf6.js');
var React = require('react');
require('@carbon/icon-helpers');
require('prop-types');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var React__default = /*#__PURE__*/_interopDefaultLegacy(React);

var _mask, _g, _mask2, _g2;

var _excluded = ["children", "size"];
var FoodNegative = /*#__PURE__*/React__default['default'].forwardRef(function FoodNegative(_ref, ref) {
  var children = _ref.children,
      _ref$size = _ref.size,
      size = _ref$size === void 0 ? 16 : _ref$size,
      rest = iconPropTypes._objectWithoutProperties(_ref, _excluded);

  if (size === "glyph" || size === "glyph" || size === "glyphpx") {
    return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
      width: size,
      height: size,
      ref: ref,
      xmlns: "http://www.w3.org/2000/svg",
      fill: "currentColor",
      viewBox: "0 0 56 56"
    }, rest), _mask || (_mask = /*#__PURE__*/React__default['default'].createElement("mask", {
      id: "a",
      style: "mask-type:alpha",
      width: "56",
      height: "56",
      x: "0",
      y: "0",
      maskUnits: "userSpaceOnUse"
    }, /*#__PURE__*/React__default['default'].createElement("path", {
      "fill-rule": "evenodd",
      d: "M0 0H56V56H0V0Z",
      "clip-rule": "evenodd"
    }))), _g || (_g = /*#__PURE__*/React__default['default'].createElement("g", {
      mask: "url(#a)"
    }, /*#__PURE__*/React__default['default'].createElement("path", {
      d: "M44.7915 38.0316C42.8381 40.0077 40.1339 41.2356 37.1485 41.2356H18.8515C12.8797 41.2356 8.0396 36.3418 8.0396 30.3038H47.9604C47.9604 33.3233 46.7459 36.0555 44.7915 38.0316ZM14.7098 21.8947C14.7118 21.8947 14.7128 21.8947 14.7148 21.8947C14.9269 19.0727 17.2542 16.8492 20.0995 16.8492C20.9667 16.8492 21.7836 17.0607 22.5107 17.4287C23.3049 15.1334 25.4596 13.4855 28 13.4855C30.5414 13.4855 32.6951 15.1334 33.4903 17.4287C34.2164 17.0607 35.0333 16.8492 35.9015 16.8492C38.7468 16.8492 41.0731 19.0727 41.2862 21.8947C41.2872 21.8947 41.2892 21.8947 41.2902 21.8947C44.5182 21.8947 47.1287 24.5271 47.1287 27.781H8.87129C8.87129 24.5271 11.4828 21.8947 14.7098 21.8947ZM53.6667 0H2.33325C1.04972 0 0 1.06137 0 2.35914V53.6409C0 54.9386 1.04972 56 2.33325 56H53.6667C54.9503 56 56 54.9386 56 53.6409V2.35914C56 1.06137 54.9503 0 53.6667 0Z",
      "clip-rule": "evenodd"
    }))), children);
  }

  return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
    width: size,
    height: size,
    ref: ref,
    xmlns: "http://www.w3.org/2000/svg",
    fill: "currentColor",
    viewBox: "0 0 56 56"
  }, rest), _mask2 || (_mask2 = /*#__PURE__*/React__default['default'].createElement("mask", {
    id: "a",
    style: "mask-type:alpha",
    width: "56",
    height: "56",
    x: "0",
    y: "0",
    maskUnits: "userSpaceOnUse"
  }, /*#__PURE__*/React__default['default'].createElement("path", {
    "fill-rule": "evenodd",
    d: "M0 0H56V56H0V0Z",
    "clip-rule": "evenodd"
  }))), _g2 || (_g2 = /*#__PURE__*/React__default['default'].createElement("g", {
    mask: "url(#a)"
  }, /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M44.7915 38.0316C42.8381 40.0077 40.1339 41.2356 37.1485 41.2356H18.8515C12.8797 41.2356 8.0396 36.3418 8.0396 30.3038H47.9604C47.9604 33.3233 46.7459 36.0555 44.7915 38.0316ZM14.7098 21.8947C14.7118 21.8947 14.7128 21.8947 14.7148 21.8947C14.9269 19.0727 17.2542 16.8492 20.0995 16.8492C20.9667 16.8492 21.7836 17.0607 22.5107 17.4287C23.3049 15.1334 25.4596 13.4855 28 13.4855C30.5414 13.4855 32.6951 15.1334 33.4903 17.4287C34.2164 17.0607 35.0333 16.8492 35.9015 16.8492C38.7468 16.8492 41.0731 19.0727 41.2862 21.8947C41.2872 21.8947 41.2892 21.8947 41.2902 21.8947C44.5182 21.8947 47.1287 24.5271 47.1287 27.781H8.87129C8.87129 24.5271 11.4828 21.8947 14.7098 21.8947ZM53.6667 0H2.33325C1.04972 0 0 1.06137 0 2.35914V53.6409C0 54.9386 1.04972 56 2.33325 56H53.6667C54.9503 56 56 54.9386 56 53.6409V2.35914C56 1.06137 54.9503 0 53.6667 0Z",
    "clip-rule": "evenodd"
  }))), children);
});
FoodNegative.propTypes = iconPropTypes.iconPropTypes;

module.exports = FoodNegative;
