/**
 *
 * Code generated by @wfp/icon-build-helpers. DO NOT EDIT.
 * @wfp/icon-build-helpers is a fork of @carbon/icon-build-helpers
 */
'use strict';

var iconPropTypes = require('./iconPropTypes-dc77abf6.js');
var React = require('react');
require('@carbon/icon-helpers');
require('prop-types');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var React__default = /*#__PURE__*/_interopDefaultLegacy(React);

var _mask, _g, _mask2, _g2;

var _excluded = ["children", "size"];
var FoodSecurityClusterPositive = /*#__PURE__*/React__default['default'].forwardRef(function FoodSecurityClusterPositive(_ref, ref) {
  var children = _ref.children,
      _ref$size = _ref.size,
      size = _ref$size === void 0 ? 16 : _ref$size,
      rest = iconPropTypes._objectWithoutProperties(_ref, _excluded);

  if (size === "glyph" || size === "glyph" || size === "glyphpx") {
    return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
      width: size,
      height: size,
      ref: ref,
      xmlns: "http://www.w3.org/2000/svg",
      fill: "currentColor",
      viewBox: "0 0 41 32"
    }, rest), _mask || (_mask = /*#__PURE__*/React__default['default'].createElement("mask", {
      id: "a",
      width: "41",
      height: "32",
      x: "0",
      y: "0",
      maskUnits: "userSpaceOnUse"
    }, /*#__PURE__*/React__default['default'].createElement("path", {
      "fill-rule": "evenodd",
      d: "M0 0.931H40.464V32H0V0.931Z",
      "clip-rule": "evenodd"
    }))), _g || (_g = /*#__PURE__*/React__default['default'].createElement("g", {
      mask: "url(#a)"
    }, /*#__PURE__*/React__default['default'].createElement("path", {
      d: "M29.505 32H10.959C4.906 32 0 27.094 0 21.041C0 20.576 0.378 20.198 0.843 20.198H39.621C40.087 20.198 40.464 20.576 40.464 21.041C40.464 27.094 35.557 32 29.505 32ZM8.969 12.517C8.798 13.156 8.142 13.535 7.503 13.364L4.418 12.537C3.779 12.366 3.4 11.709 3.571 11.071C3.743 10.432 4.399 10.053 5.038 10.224L8.122 11.051C8.761 11.222 9.141 11.878 8.969 12.517ZM1.727 5.61801C1.898 4.97901 2.555 4.60001 3.193 4.77201L11.675 7.04401C12.313 7.21501 12.693 7.87201 12.521 8.51101C12.35 9.14901 11.694 9.52901 11.056 9.35701L2.574 7.08501C1.934 6.91301 1.556 6.25701 1.727 5.61801ZM6.051 1.81901C6.222 1.18001 6.879 0.801006 7.517 0.972006L10.601 1.79801C11.24 1.96901 11.619 2.62601 11.448 3.26401C11.277 3.90301 10.62 4.28301 9.981 4.11101L6.897 3.28501C6.259 3.11401 5.88 2.45701 6.051 1.81901ZM13.151 3.07601L13.3 2.52101L15.397 3.08301C17.645 3.68601 18.98 5.99701 18.378 8.24501L18.228 8.80001L16.132 8.23901C13.884 7.63601 12.549 5.32501 13.151 3.07601ZM12.298 14.649L10.201 14.087L10.349 13.532C10.952 11.284 13.264 9.94901 15.512 10.552L17.609 11.114L17.46 11.668C16.858 13.917 14.547 15.251 12.298 14.649ZM22.451 12.411L24.549 12.972L24.399 13.528C23.797 15.776 21.486 17.111 19.237 16.508L17.14 15.946L17.289 15.391C17.891 13.143 20.203 11.808 22.451 12.411ZM20.091 4.93501L20.239 4.38101L22.337 4.94301C24.585 5.54501 25.92 7.85601 25.317 10.105L25.168 10.66L23.071 10.097C20.823 9.49501 19.488 7.18401 20.091 4.93501ZM29.39 14.27L31.488 14.832L31.339 15.387C30.736 17.636 28.426 18.97 26.177 18.368L24.08 17.806L24.228 17.251C24.831 15.002 27.142 13.668 29.39 14.27ZM27.03 6.79501L27.179 6.24001L29.275 6.80201C31.524 7.40401 32.858 9.71601 32.256 11.964L32.107 12.519L30.011 11.957C27.762 11.355 26.428 9.04301 27.03 6.79501ZM33.649 12.932L37.89 14.069C38.529 14.24 38.908 14.896 38.737 15.535C38.565 16.174 37.909 16.553 37.27 16.382L33.03 15.245L33.649 12.932Z",
      "clip-rule": "evenodd"
    }))), children);
  }

  return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
    width: size,
    height: size,
    ref: ref,
    xmlns: "http://www.w3.org/2000/svg",
    fill: "currentColor",
    viewBox: "0 0 41 32"
  }, rest), _mask2 || (_mask2 = /*#__PURE__*/React__default['default'].createElement("mask", {
    id: "a",
    width: "41",
    height: "32",
    x: "0",
    y: "0",
    maskUnits: "userSpaceOnUse"
  }, /*#__PURE__*/React__default['default'].createElement("path", {
    "fill-rule": "evenodd",
    d: "M0 0.931H40.464V32H0V0.931Z",
    "clip-rule": "evenodd"
  }))), _g2 || (_g2 = /*#__PURE__*/React__default['default'].createElement("g", {
    mask: "url(#a)"
  }, /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M29.505 32H10.959C4.906 32 0 27.094 0 21.041C0 20.576 0.378 20.198 0.843 20.198H39.621C40.087 20.198 40.464 20.576 40.464 21.041C40.464 27.094 35.557 32 29.505 32ZM8.969 12.517C8.798 13.156 8.142 13.535 7.503 13.364L4.418 12.537C3.779 12.366 3.4 11.709 3.571 11.071C3.743 10.432 4.399 10.053 5.038 10.224L8.122 11.051C8.761 11.222 9.141 11.878 8.969 12.517ZM1.727 5.61801C1.898 4.97901 2.555 4.60001 3.193 4.77201L11.675 7.04401C12.313 7.21501 12.693 7.87201 12.521 8.51101C12.35 9.14901 11.694 9.52901 11.056 9.35701L2.574 7.08501C1.934 6.91301 1.556 6.25701 1.727 5.61801ZM6.051 1.81901C6.222 1.18001 6.879 0.801006 7.517 0.972006L10.601 1.79801C11.24 1.96901 11.619 2.62601 11.448 3.26401C11.277 3.90301 10.62 4.28301 9.981 4.11101L6.897 3.28501C6.259 3.11401 5.88 2.45701 6.051 1.81901ZM13.151 3.07601L13.3 2.52101L15.397 3.08301C17.645 3.68601 18.98 5.99701 18.378 8.24501L18.228 8.80001L16.132 8.23901C13.884 7.63601 12.549 5.32501 13.151 3.07601ZM12.298 14.649L10.201 14.087L10.349 13.532C10.952 11.284 13.264 9.94901 15.512 10.552L17.609 11.114L17.46 11.668C16.858 13.917 14.547 15.251 12.298 14.649ZM22.451 12.411L24.549 12.972L24.399 13.528C23.797 15.776 21.486 17.111 19.237 16.508L17.14 15.946L17.289 15.391C17.891 13.143 20.203 11.808 22.451 12.411ZM20.091 4.93501L20.239 4.38101L22.337 4.94301C24.585 5.54501 25.92 7.85601 25.317 10.105L25.168 10.66L23.071 10.097C20.823 9.49501 19.488 7.18401 20.091 4.93501ZM29.39 14.27L31.488 14.832L31.339 15.387C30.736 17.636 28.426 18.97 26.177 18.368L24.08 17.806L24.228 17.251C24.831 15.002 27.142 13.668 29.39 14.27ZM27.03 6.79501L27.179 6.24001L29.275 6.80201C31.524 7.40401 32.858 9.71601 32.256 11.964L32.107 12.519L30.011 11.957C27.762 11.355 26.428 9.04301 27.03 6.79501ZM33.649 12.932L37.89 14.069C38.529 14.24 38.908 14.896 38.737 15.535C38.565 16.174 37.909 16.553 37.27 16.382L33.03 15.245L33.649 12.932Z",
    "clip-rule": "evenodd"
  }))), children);
});
FoodSecurityClusterPositive.propTypes = iconPropTypes.iconPropTypes;

module.exports = FoodSecurityClusterPositive;
