/**
 *
 * Code generated by @wfp/icon-build-helpers. DO NOT EDIT.
 * @wfp/icon-build-helpers is a fork of @carbon/icon-build-helpers
 */
'use strict';

var iconPropTypes = require('./iconPropTypes-dc77abf6.js');
var React = require('react');
require('@carbon/icon-helpers');
require('prop-types');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var React__default = /*#__PURE__*/_interopDefaultLegacy(React);

var _mask, _g, _mask2, _g2;

var _excluded = ["children", "size"];
var FoodForAssetsPositive = /*#__PURE__*/React__default['default'].forwardRef(function FoodForAssetsPositive(_ref, ref) {
  var children = _ref.children,
      _ref$size = _ref.size,
      size = _ref$size === void 0 ? 16 : _ref$size,
      rest = iconPropTypes._objectWithoutProperties(_ref, _excluded);

  if (size === "glyph" || size === "glyph" || size === "glyphpx") {
    return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
      width: size,
      height: size,
      ref: ref,
      xmlns: "http://www.w3.org/2000/svg",
      fill: "currentColor",
      viewBox: "0 0 34 15"
    }, rest), _mask || (_mask = /*#__PURE__*/React__default['default'].createElement("mask", {
      id: "a",
      style: "mask-type:alpha",
      width: "34",
      height: "15",
      x: "0",
      y: "0",
      maskUnits: "userSpaceOnUse"
    }, /*#__PURE__*/React__default['default'].createElement("path", {
      "fill-rule": "evenodd",
      d: "M0.0600586 0.916992H33.1451V15H0.0600586V0.916992Z",
      "clip-rule": "evenodd"
    }))), _g || (_g = /*#__PURE__*/React__default['default'].createElement("g", {
      mask: "url(#a)"
    }, /*#__PURE__*/React__default['default'].createElement("path", {
      d: "M14.3209 4.01701H18.8799V.975006H10.5909V15H14.3209V9.73401H18.5239V6.69201H14.3209V4.01701zM0 15H3.731V9.73401H7.934V6.69201H3.731V4.01701H8.289V.975006H0V15zM24.539 9.26299C25.121 7.06399 25.497 5.58899 25.667 4.84099 25.836 4.09199 25.95 3.55599 26.008 3.22899 26.07 3.58199 26.204 4.16299 26.405 4.97599 26.608 5.78799 26.778 6.44899 26.919 6.96099L27.524 9.26299H24.539zM28.512.916992H23.455L18.88 15H23.042L23.753 12.371H28.31L29 15H33.145L28.512.916992z",
      "clip-rule": "evenodd"
    }))), children);
  }

  return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
    width: size,
    height: size,
    ref: ref,
    xmlns: "http://www.w3.org/2000/svg",
    fill: "currentColor",
    viewBox: "0 0 34 15"
  }, rest), _mask2 || (_mask2 = /*#__PURE__*/React__default['default'].createElement("mask", {
    id: "a",
    style: "mask-type:alpha",
    width: "34",
    height: "15",
    x: "0",
    y: "0",
    maskUnits: "userSpaceOnUse"
  }, /*#__PURE__*/React__default['default'].createElement("path", {
    "fill-rule": "evenodd",
    d: "M0.0600586 0.916992H33.1451V15H0.0600586V0.916992Z",
    "clip-rule": "evenodd"
  }))), _g2 || (_g2 = /*#__PURE__*/React__default['default'].createElement("g", {
    mask: "url(#a)"
  }, /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M14.3209 4.01701H18.8799V.975006H10.5909V15H14.3209V9.73401H18.5239V6.69201H14.3209V4.01701zM0 15H3.731V9.73401H7.934V6.69201H3.731V4.01701H8.289V.975006H0V15zM24.539 9.26299C25.121 7.06399 25.497 5.58899 25.667 4.84099 25.836 4.09199 25.95 3.55599 26.008 3.22899 26.07 3.58199 26.204 4.16299 26.405 4.97599 26.608 5.78799 26.778 6.44899 26.919 6.96099L27.524 9.26299H24.539zM28.512.916992H23.455L18.88 15H23.042L23.753 12.371H28.31L29 15H33.145L28.512.916992z",
    "clip-rule": "evenodd"
  }))), children);
});
FoodForAssetsPositive.propTypes = iconPropTypes.iconPropTypes;

module.exports = FoodForAssetsPositive;
