/**
 *
 * Code generated by @wfp/icon-build-helpers. DO NOT EDIT.
 * @wfp/icon-build-helpers is a fork of @carbon/icon-build-helpers
 */
'use strict';

var iconPropTypes = require('./iconPropTypes-dc77abf6.js');
var React = require('react');
require('@carbon/icon-helpers');
require('prop-types');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var React__default = /*#__PURE__*/_interopDefaultLegacy(React);

var _path, _mask, _g, _path2, _mask2, _g2;

var _excluded = ["children", "size"];
var GenderPositive = /*#__PURE__*/React__default['default'].forwardRef(function GenderPositive(_ref, ref) {
  var children = _ref.children,
      _ref$size = _ref.size,
      size = _ref$size === void 0 ? 16 : _ref$size,
      rest = iconPropTypes._objectWithoutProperties(_ref, _excluded);

  if (size === "glyph" || size === "glyph" || size === "glyphpx") {
    return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
      width: size,
      height: size,
      ref: ref,
      xmlns: "http://www.w3.org/2000/svg",
      fill: "currentColor",
      viewBox: "0 0 35 44"
    }, rest), _path || (_path = /*#__PURE__*/React__default['default'].createElement("path", {
      d: "M18.529 14.26H9.971C9.134 14.26 8.448 14.946 8.448 15.784C8.448 16.621 9.134 17.306 9.971 17.306H18.529C19.367 17.306 20.052 16.621 20.052 15.784C20.052 14.946 19.367 14.26 18.529 14.26Z",
      "clip-rule": "evenodd"
    })), _mask || (_mask = /*#__PURE__*/React__default['default'].createElement("mask", {
      id: "a",
      width: "35",
      height: "44",
      x: "0",
      y: "0",
      maskUnits: "userSpaceOnUse"
    }, /*#__PURE__*/React__default['default'].createElement("path", {
      "fill-rule": "evenodd",
      d: "M0 0.359985H34.005V44H0V0.359985Z",
      "clip-rule": "evenodd"
    }))), _g || (_g = /*#__PURE__*/React__default['default'].createElement("g", {
      mask: "url(#a)"
    }, /*#__PURE__*/React__default['default'].createElement("path", {
      d: "M18.529 19.434H9.971C9.134 19.434 8.448 20.12 8.448 20.957C8.448 21.795 9.134 22.48 9.971 22.48H18.529C19.367 22.48 20.052 21.795 20.052 20.957C20.052 20.12 19.367 19.434 18.529 19.434Z",
      "clip-rule": "evenodd"
    }), /*#__PURE__*/React__default['default'].createElement("path", {
      d: "M22.088 25.874C20.927 27.135 19.466 28.118 17.813 28.695C17.35 28.859 16.879 28.995 16.388 29.094C15.696 29.237 14.985 29.308 14.25 29.308C13.517 29.308 12.804 29.237 12.113 29.094C11.621 28.995 11.151 28.859 10.688 28.695C9.034 28.118 7.574 27.135 6.412 25.874C4.639 23.971 3.563 21.42 3.563 18.621C3.563 12.721 8.351 7.93299 14.25 7.93299C20.15 7.93299 24.938 12.721 24.938 18.621C24.938 21.42 23.862 23.971 22.088 25.874ZM32.58 0.359987H26.534C25.747 0.359987 25.11 0.997986 25.11 1.78499C25.109 2.57199 25.747 3.20999 26.534 3.20999H29.14L24.085 8.34199C21.527 5.89399 18.073 4.36999 14.25 4.36999C6.377 4.36999 0 10.747 0 18.621C0 26.005 5.632 32.003 12.825 32.727V36.336H9.971C9.134 36.336 8.448 37.02 8.448 37.858C8.448 38.696 9.134 39.381 9.971 39.381H12.825V42.575C12.825 43.362 13.463 44 14.25 44C14.644 44 15 43.84 15.258 43.583C15.516 43.325 15.675 42.968 15.675 42.575V39.381H18.529C19.367 39.381 20.052 38.696 20.052 37.858C20.052 37.02 19.367 36.336 18.529 36.336H15.675V32.727C22.869 32.003 28.501 26.005 28.501 18.621C28.501 15.602 27.551 12.813 25.95 10.51L31.155 5.22499V7.83099C31.155 8.61799 31.793 9.25499 32.58 9.25499C32.974 9.25499 33.33 9.09599 33.588 8.83799C33.846 8.58099 34.005 8.22399 34.005 7.83099V1.78499C34.005 0.997986 33.367 0.358987 32.58 0.359987Z",
      "clip-rule": "evenodd"
    }))), children);
  }

  return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
    width: size,
    height: size,
    ref: ref,
    xmlns: "http://www.w3.org/2000/svg",
    fill: "currentColor",
    viewBox: "0 0 35 44"
  }, rest), _path2 || (_path2 = /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M18.529 14.26H9.971C9.134 14.26 8.448 14.946 8.448 15.784C8.448 16.621 9.134 17.306 9.971 17.306H18.529C19.367 17.306 20.052 16.621 20.052 15.784C20.052 14.946 19.367 14.26 18.529 14.26Z",
    "clip-rule": "evenodd"
  })), _mask2 || (_mask2 = /*#__PURE__*/React__default['default'].createElement("mask", {
    id: "a",
    width: "35",
    height: "44",
    x: "0",
    y: "0",
    maskUnits: "userSpaceOnUse"
  }, /*#__PURE__*/React__default['default'].createElement("path", {
    "fill-rule": "evenodd",
    d: "M0 0.359985H34.005V44H0V0.359985Z",
    "clip-rule": "evenodd"
  }))), _g2 || (_g2 = /*#__PURE__*/React__default['default'].createElement("g", {
    mask: "url(#a)"
  }, /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M18.529 19.434H9.971C9.134 19.434 8.448 20.12 8.448 20.957C8.448 21.795 9.134 22.48 9.971 22.48H18.529C19.367 22.48 20.052 21.795 20.052 20.957C20.052 20.12 19.367 19.434 18.529 19.434Z",
    "clip-rule": "evenodd"
  }), /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M22.088 25.874C20.927 27.135 19.466 28.118 17.813 28.695C17.35 28.859 16.879 28.995 16.388 29.094C15.696 29.237 14.985 29.308 14.25 29.308C13.517 29.308 12.804 29.237 12.113 29.094C11.621 28.995 11.151 28.859 10.688 28.695C9.034 28.118 7.574 27.135 6.412 25.874C4.639 23.971 3.563 21.42 3.563 18.621C3.563 12.721 8.351 7.93299 14.25 7.93299C20.15 7.93299 24.938 12.721 24.938 18.621C24.938 21.42 23.862 23.971 22.088 25.874ZM32.58 0.359987H26.534C25.747 0.359987 25.11 0.997986 25.11 1.78499C25.109 2.57199 25.747 3.20999 26.534 3.20999H29.14L24.085 8.34199C21.527 5.89399 18.073 4.36999 14.25 4.36999C6.377 4.36999 0 10.747 0 18.621C0 26.005 5.632 32.003 12.825 32.727V36.336H9.971C9.134 36.336 8.448 37.02 8.448 37.858C8.448 38.696 9.134 39.381 9.971 39.381H12.825V42.575C12.825 43.362 13.463 44 14.25 44C14.644 44 15 43.84 15.258 43.583C15.516 43.325 15.675 42.968 15.675 42.575V39.381H18.529C19.367 39.381 20.052 38.696 20.052 37.858C20.052 37.02 19.367 36.336 18.529 36.336H15.675V32.727C22.869 32.003 28.501 26.005 28.501 18.621C28.501 15.602 27.551 12.813 25.95 10.51L31.155 5.22499V7.83099C31.155 8.61799 31.793 9.25499 32.58 9.25499C32.974 9.25499 33.33 9.09599 33.588 8.83799C33.846 8.58099 34.005 8.22399 34.005 7.83099V1.78499C34.005 0.997986 33.367 0.358987 32.58 0.359987Z",
    "clip-rule": "evenodd"
  }))), children);
});
GenderPositive.propTypes = iconPropTypes.iconPropTypes;

module.exports = GenderPositive;
