/**
 *
 * Code generated by @wfp/icon-build-helpers. DO NOT EDIT.
 * @wfp/icon-build-helpers is a fork of @carbon/icon-build-helpers
 */
'use strict';

var iconPropTypes = require('./iconPropTypes-dc77abf6.js');
var React = require('react');
require('@carbon/icon-helpers');
require('prop-types');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var React__default = /*#__PURE__*/_interopDefaultLegacy(React);

var _mask, _g, _mask2, _g2;

var _excluded = ["children", "size"];
var InfantPositive = /*#__PURE__*/React__default['default'].forwardRef(function InfantPositive(_ref, ref) {
  var children = _ref.children,
      _ref$size = _ref.size,
      size = _ref$size === void 0 ? 16 : _ref$size,
      rest = iconPropTypes._objectWithoutProperties(_ref, _excluded);

  if (size === "glyph" || size === "glyph" || size === "glyphpx") {
    return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
      width: size,
      height: size,
      ref: ref,
      xmlns: "http://www.w3.org/2000/svg",
      fill: "currentColor",
      viewBox: "0 0 25 42"
    }, rest), _mask || (_mask = /*#__PURE__*/React__default['default'].createElement("mask", {
      id: "a",
      style: "mask-type:alpha",
      width: "25",
      height: "42",
      x: "0",
      y: "0",
      maskUnits: "userSpaceOnUse"
    }, /*#__PURE__*/React__default['default'].createElement("path", {
      "fill-rule": "evenodd",
      d: "M0 0.444H24.481V41.94H0V0.444Z",
      "clip-rule": "evenodd"
    }))), _g || (_g = /*#__PURE__*/React__default['default'].createElement("g", {
      mask: "url(#a)"
    }, /*#__PURE__*/React__default['default'].createElement("path", {
      d: "M22.441 24.925C21.314 24.925 20.401 24.011 20.401 22.885C20.401 20.473 19.13 18.569 17.34 17.333V23.905H7.14V17.333C5.351 18.569 4.08 20.473 4.08 22.885C4.08 24.011 3.166 24.925 2.04 24.925C0.913 24.925 0 24.011 0 22.885C0 16.698 5.491 11.665 12.241 11.665C18.99 11.665 24.481 16.698 24.481 22.885C24.481 24.011 23.567 24.925 22.441 24.925ZM17.483 41.633C17.126 41.877 16.718 42 16.321 42C15.678 42 15.035 41.694 14.648 41.123C14.005 40.195 14.23 38.919 15.158 38.287C16.525 37.338 17.34 35.778 17.34 34.105C17.34 32.216 16.304 30.561 14.773 29.683C14.625 29.599 14.593 29.406 14.712 29.287L17.296 26.703C17.386 26.613 17.531 26.6 17.633 26.675C19.928 28.35 21.42 31.053 21.42 34.105C21.42 37.114 19.951 39.929 17.483 41.633ZM9.648 41.354C8.952 42.109 7.757 42.17 6.918 41.578C4.497 39.869 3.06 37.082 3.06 34.105C3.06 31.053 4.552 28.35 6.847 26.675C6.95 26.6 7.095 26.613 7.185 26.703L9.768 29.287C9.888 29.406 9.855 29.599 9.708 29.683C8.177 30.561 7.14 32.216 7.14 34.105C7.14 35.778 7.956 37.338 9.323 38.287C10.331 38.974 10.509 40.418 9.648 41.354ZM12.241 0.444C14.776 0.444 16.83 2.499 16.83 5.034C16.83 7.569 14.776 9.624 12.241 9.624C9.705 9.624 7.65 7.569 7.65 5.034C7.65 2.499 9.705 0.444 12.241 0.444Z",
      "clip-rule": "evenodd"
    }))), children);
  }

  return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
    width: size,
    height: size,
    ref: ref,
    xmlns: "http://www.w3.org/2000/svg",
    fill: "currentColor",
    viewBox: "0 0 25 42"
  }, rest), _mask2 || (_mask2 = /*#__PURE__*/React__default['default'].createElement("mask", {
    id: "a",
    style: "mask-type:alpha",
    width: "25",
    height: "42",
    x: "0",
    y: "0",
    maskUnits: "userSpaceOnUse"
  }, /*#__PURE__*/React__default['default'].createElement("path", {
    "fill-rule": "evenodd",
    d: "M0 0.444H24.481V41.94H0V0.444Z",
    "clip-rule": "evenodd"
  }))), _g2 || (_g2 = /*#__PURE__*/React__default['default'].createElement("g", {
    mask: "url(#a)"
  }, /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M22.441 24.925C21.314 24.925 20.401 24.011 20.401 22.885C20.401 20.473 19.13 18.569 17.34 17.333V23.905H7.14V17.333C5.351 18.569 4.08 20.473 4.08 22.885C4.08 24.011 3.166 24.925 2.04 24.925C0.913 24.925 0 24.011 0 22.885C0 16.698 5.491 11.665 12.241 11.665C18.99 11.665 24.481 16.698 24.481 22.885C24.481 24.011 23.567 24.925 22.441 24.925ZM17.483 41.633C17.126 41.877 16.718 42 16.321 42C15.678 42 15.035 41.694 14.648 41.123C14.005 40.195 14.23 38.919 15.158 38.287C16.525 37.338 17.34 35.778 17.34 34.105C17.34 32.216 16.304 30.561 14.773 29.683C14.625 29.599 14.593 29.406 14.712 29.287L17.296 26.703C17.386 26.613 17.531 26.6 17.633 26.675C19.928 28.35 21.42 31.053 21.42 34.105C21.42 37.114 19.951 39.929 17.483 41.633ZM9.648 41.354C8.952 42.109 7.757 42.17 6.918 41.578C4.497 39.869 3.06 37.082 3.06 34.105C3.06 31.053 4.552 28.35 6.847 26.675C6.95 26.6 7.095 26.613 7.185 26.703L9.768 29.287C9.888 29.406 9.855 29.599 9.708 29.683C8.177 30.561 7.14 32.216 7.14 34.105C7.14 35.778 7.956 37.338 9.323 38.287C10.331 38.974 10.509 40.418 9.648 41.354ZM12.241 0.444C14.776 0.444 16.83 2.499 16.83 5.034C16.83 7.569 14.776 9.624 12.241 9.624C9.705 9.624 7.65 7.569 7.65 5.034C7.65 2.499 9.705 0.444 12.241 0.444Z",
    "clip-rule": "evenodd"
  }))), children);
});
InfantPositive.propTypes = iconPropTypes.iconPropTypes;

module.exports = InfantPositive;
