/**
 *
 * Code generated by @wfp/icon-build-helpers. DO NOT EDIT.
 * @wfp/icon-build-helpers is a fork of @carbon/icon-build-helpers
 */
'use strict';

var iconPropTypes = require('./iconPropTypes-dc77abf6.js');
var React = require('react');
require('@carbon/icon-helpers');
require('prop-types');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var React__default = /*#__PURE__*/_interopDefaultLegacy(React);

var _mask, _g, _mask2, _g2;

var _excluded = ["children", "size"];
var InfantNegative = /*#__PURE__*/React__default['default'].forwardRef(function InfantNegative(_ref, ref) {
  var children = _ref.children,
      _ref$size = _ref.size,
      size = _ref$size === void 0 ? 16 : _ref$size,
      rest = iconPropTypes._objectWithoutProperties(_ref, _excluded);

  if (size === "glyph" || size === "glyph" || size === "glyphpx") {
    return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
      width: size,
      height: size,
      ref: ref,
      xmlns: "http://www.w3.org/2000/svg",
      fill: "currentColor",
      viewBox: "0 0 56 56"
    }, rest), _mask || (_mask = /*#__PURE__*/React__default['default'].createElement("mask", {
      id: "a",
      style: "mask-type:alpha",
      width: "56",
      height: "56",
      x: "0",
      y: "0",
      maskUnits: "userSpaceOnUse"
    }, /*#__PURE__*/React__default['default'].createElement("path", {
      "fill-rule": "evenodd",
      d: "M0 0H56V56H0V0Z",
      "clip-rule": "evenodd"
    }))), _g || (_g = /*#__PURE__*/React__default['default'].createElement("g", {
      mask: "url(#a)"
    }, /*#__PURE__*/React__default['default'].createElement("path", {
      d: "M38.0641 31.6933C36.9522 31.6933 36.0514 30.7826 36.0514 29.6584C36.0514 27.2534 34.7975 25.3531 33.0315 24.1211V30.6759H22.9685V24.1211C21.2035 25.3531 19.9495 27.2534 19.9495 29.6584C19.9495 30.7826 19.0478 31.6933 17.9369 31.6933C16.8251 31.6933 15.9243 30.7826 15.9243 29.6584C15.9243 23.4867 21.3406 18.4662 28 18.4662C34.6584 18.4662 40.0767 23.4867 40.0767 29.6584C40.0767 30.7826 39.1749 31.6933 38.0641 31.6933ZM33.1726 48.36C32.8204 48.6044 32.4179 48.7271 32.0252 48.7271C31.3918 48.7271 30.7575 48.4208 30.3757 47.8522C29.7413 46.9255 29.9633 45.6537 30.8778 45.0232C32.2275 44.0766 33.0315 42.5195 33.0315 40.8506C33.0315 38.9663 32.0094 37.3164 30.499 36.4405C30.353 36.3568 30.3214 36.1642 30.4388 36.0445L32.9881 33.4679C33.0769 33.3781 33.219 33.3652 33.3206 33.44C35.5848 35.1099 37.0568 37.8062 37.0568 40.8506C37.0568 43.8531 35.6075 46.6612 33.1726 48.36ZM25.4428 48.0826C24.7561 48.8358 23.5772 48.8956 22.7494 48.3051C20.3609 46.6013 18.9432 43.8212 18.9432 40.8506C18.9432 37.8062 20.4152 35.1099 22.6794 33.44C22.78 33.3652 22.9241 33.3781 23.0129 33.4679L25.5612 36.0445C25.6796 36.1642 25.647 36.3568 25.502 36.4405C23.9915 37.3164 22.9685 38.9663 22.9685 40.8506C22.9685 42.5195 23.7735 44.0766 25.1212 45.0232C26.1166 45.7075 26.2922 47.149 25.4428 48.0826ZM28 7.27295C30.502 7.27295 32.5284 9.32386 32.5284 11.8526C32.5284 14.3803 30.502 16.4312 28 16.4312C25.499 16.4312 23.4716 14.3803 23.4716 11.8526C23.4716 9.32386 25.499 7.27295 28 7.27295ZM53.6667 0H2.33325C1.04972 0 0 1.06137 0 2.35914V53.6409C0 54.9386 1.04972 56 2.33325 56H53.6667C54.9503 56 56 54.9386 56 53.6409V2.35914C56 1.06137 54.9503 0 53.6667 0Z",
      "clip-rule": "evenodd"
    }))), children);
  }

  return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
    width: size,
    height: size,
    ref: ref,
    xmlns: "http://www.w3.org/2000/svg",
    fill: "currentColor",
    viewBox: "0 0 56 56"
  }, rest), _mask2 || (_mask2 = /*#__PURE__*/React__default['default'].createElement("mask", {
    id: "a",
    style: "mask-type:alpha",
    width: "56",
    height: "56",
    x: "0",
    y: "0",
    maskUnits: "userSpaceOnUse"
  }, /*#__PURE__*/React__default['default'].createElement("path", {
    "fill-rule": "evenodd",
    d: "M0 0H56V56H0V0Z",
    "clip-rule": "evenodd"
  }))), _g2 || (_g2 = /*#__PURE__*/React__default['default'].createElement("g", {
    mask: "url(#a)"
  }, /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M38.0641 31.6933C36.9522 31.6933 36.0514 30.7826 36.0514 29.6584C36.0514 27.2534 34.7975 25.3531 33.0315 24.1211V30.6759H22.9685V24.1211C21.2035 25.3531 19.9495 27.2534 19.9495 29.6584C19.9495 30.7826 19.0478 31.6933 17.9369 31.6933C16.8251 31.6933 15.9243 30.7826 15.9243 29.6584C15.9243 23.4867 21.3406 18.4662 28 18.4662C34.6584 18.4662 40.0767 23.4867 40.0767 29.6584C40.0767 30.7826 39.1749 31.6933 38.0641 31.6933ZM33.1726 48.36C32.8204 48.6044 32.4179 48.7271 32.0252 48.7271C31.3918 48.7271 30.7575 48.4208 30.3757 47.8522C29.7413 46.9255 29.9633 45.6537 30.8778 45.0232C32.2275 44.0766 33.0315 42.5195 33.0315 40.8506C33.0315 38.9663 32.0094 37.3164 30.499 36.4405C30.353 36.3568 30.3214 36.1642 30.4388 36.0445L32.9881 33.4679C33.0769 33.3781 33.219 33.3652 33.3206 33.44C35.5848 35.1099 37.0568 37.8062 37.0568 40.8506C37.0568 43.8531 35.6075 46.6612 33.1726 48.36ZM25.4428 48.0826C24.7561 48.8358 23.5772 48.8956 22.7494 48.3051C20.3609 46.6013 18.9432 43.8212 18.9432 40.8506C18.9432 37.8062 20.4152 35.1099 22.6794 33.44C22.78 33.3652 22.9241 33.3781 23.0129 33.4679L25.5612 36.0445C25.6796 36.1642 25.647 36.3568 25.502 36.4405C23.9915 37.3164 22.9685 38.9663 22.9685 40.8506C22.9685 42.5195 23.7735 44.0766 25.1212 45.0232C26.1166 45.7075 26.2922 47.149 25.4428 48.0826ZM28 7.27295C30.502 7.27295 32.5284 9.32386 32.5284 11.8526C32.5284 14.3803 30.502 16.4312 28 16.4312C25.499 16.4312 23.4716 14.3803 23.4716 11.8526C23.4716 9.32386 25.499 7.27295 28 7.27295ZM53.6667 0H2.33325C1.04972 0 0 1.06137 0 2.35914V53.6409C0 54.9386 1.04972 56 2.33325 56H53.6667C54.9503 56 56 54.9386 56 53.6409V2.35914C56 1.06137 54.9503 0 53.6667 0Z",
    "clip-rule": "evenodd"
  }))), children);
});
InfantNegative.propTypes = iconPropTypes.iconPropTypes;

module.exports = InfantNegative;
