/**
 *
 * Code generated by @wfp/icon-build-helpers. DO NOT EDIT.
 * @wfp/icon-build-helpers is a fork of @carbon/icon-build-helpers
 */
'use strict';

var iconPropTypes = require('./iconPropTypes-dc77abf6.js');
var React = require('react');
require('@carbon/icon-helpers');
require('prop-types');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var React__default = /*#__PURE__*/_interopDefaultLegacy(React);

var _mask, _g, _mask2, _g2;

var _excluded = ["children", "size"];
var MVamNegative = /*#__PURE__*/React__default['default'].forwardRef(function MVamNegative(_ref, ref) {
  var children = _ref.children,
      _ref$size = _ref.size,
      size = _ref$size === void 0 ? 16 : _ref$size,
      rest = iconPropTypes._objectWithoutProperties(_ref, _excluded);

  if (size === "glyph" || size === "glyph" || size === "glyphpx") {
    return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
      width: size,
      height: size,
      ref: ref,
      xmlns: "http://www.w3.org/2000/svg",
      fill: "currentColor",
      viewBox: "0 0 56 56"
    }, rest), _mask || (_mask = /*#__PURE__*/React__default['default'].createElement("mask", {
      id: "a",
      width: "56",
      height: "56",
      x: "0",
      y: "0",
      maskUnits: "userSpaceOnUse"
    }, /*#__PURE__*/React__default['default'].createElement("path", {
      "fill-rule": "evenodd",
      d: "M0 0H56V56H0V0Z",
      "clip-rule": "evenodd"
    }))), _g || (_g = /*#__PURE__*/React__default['default'].createElement("g", {
      mask: "url(#a)"
    }, /*#__PURE__*/React__default['default'].createElement("path", {
      d: "M32.1882 29.5867H34.6905L33.4399 25.9447L32.1882 29.5867Z",
      "clip-rule": "evenodd"
    }), /*#__PURE__*/React__default['default'].createElement("path", {
      d: "M50.5788 33.1617H47.9594V26.2488L46.0672 30.7347H44.2499L42.3566 26.2488V33.1617H39.8744V22.8383H42.9328L45.2305 28.0175L47.5204 22.8383H50.5788V33.1617ZM36.1797 33.1617L35.4694 31.0749H31.6908L30.9795 33.1617H28.3256L32.0972 22.8383H35.128L38.8987 33.1617H36.1797ZM22.3775 33.1617L18.6542 22.8383H21.4205L23.888 30.0853L26.3564 22.8383H29.0497L25.3254 33.1617H22.3775ZM18.004 33.1617H15.5287V29.2723C15.5287 28.8883 15.5208 28.5651 15.504 28.3018C15.4882 28.0384 15.4389 27.8229 15.357 27.6574C15.2791 27.4908 15.1558 27.3691 14.9871 27.2933C14.8174 27.2164 14.5796 27.1785 14.2728 27.1785C14.0676 27.1785 13.8663 27.2144 13.67 27.2853C13.4737 27.3571 13.2339 27.4768 12.9498 27.6424V33.1617H10.4755V29.2723C10.4755 28.8933 10.4656 28.5711 10.4468 28.3047C10.4291 28.0394 10.3788 27.8229 10.2969 27.6574C10.214 27.4908 10.0897 27.3691 9.92298 27.2933C9.75526 27.2164 9.52144 27.1785 9.21955 27.1785C8.97784 27.1785 8.74205 27.2284 8.51316 27.3272C8.28526 27.4269 8.07907 27.5327 7.89655 27.6424V33.1617H5.42123V25.376H7.89655V26.2359C8.32078 25.8977 8.72725 25.6344 9.11596 25.4448C9.5027 25.2553 9.93284 25.1615 10.4034 25.1615C10.9096 25.1615 11.3565 25.2753 11.7462 25.5037C12.1329 25.7331 12.4368 26.0693 12.6568 26.5132C13.1491 26.0922 13.6286 25.7621 14.0942 25.5217C14.5599 25.2812 15.0157 25.1615 15.4626 25.1615C16.2943 25.1615 16.9257 25.4129 17.3568 25.9167C17.788 26.4204 18.004 27.1456 18.004 28.0943V33.1617ZM53.6667 0H2.33325C1.04972 0 0 1.06137 0 2.35914V53.6409C0 54.9386 1.04972 56 2.33325 56H53.6667C54.9503 56 56 54.9386 56 53.6409V2.35914C56 1.06137 54.9503 0 53.6667 0Z",
      "clip-rule": "evenodd"
    }))), children);
  }

  return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
    width: size,
    height: size,
    ref: ref,
    xmlns: "http://www.w3.org/2000/svg",
    fill: "currentColor",
    viewBox: "0 0 56 56"
  }, rest), _mask2 || (_mask2 = /*#__PURE__*/React__default['default'].createElement("mask", {
    id: "a",
    width: "56",
    height: "56",
    x: "0",
    y: "0",
    maskUnits: "userSpaceOnUse"
  }, /*#__PURE__*/React__default['default'].createElement("path", {
    "fill-rule": "evenodd",
    d: "M0 0H56V56H0V0Z",
    "clip-rule": "evenodd"
  }))), _g2 || (_g2 = /*#__PURE__*/React__default['default'].createElement("g", {
    mask: "url(#a)"
  }, /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M32.1882 29.5867H34.6905L33.4399 25.9447L32.1882 29.5867Z",
    "clip-rule": "evenodd"
  }), /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M50.5788 33.1617H47.9594V26.2488L46.0672 30.7347H44.2499L42.3566 26.2488V33.1617H39.8744V22.8383H42.9328L45.2305 28.0175L47.5204 22.8383H50.5788V33.1617ZM36.1797 33.1617L35.4694 31.0749H31.6908L30.9795 33.1617H28.3256L32.0972 22.8383H35.128L38.8987 33.1617H36.1797ZM22.3775 33.1617L18.6542 22.8383H21.4205L23.888 30.0853L26.3564 22.8383H29.0497L25.3254 33.1617H22.3775ZM18.004 33.1617H15.5287V29.2723C15.5287 28.8883 15.5208 28.5651 15.504 28.3018C15.4882 28.0384 15.4389 27.8229 15.357 27.6574C15.2791 27.4908 15.1558 27.3691 14.9871 27.2933C14.8174 27.2164 14.5796 27.1785 14.2728 27.1785C14.0676 27.1785 13.8663 27.2144 13.67 27.2853C13.4737 27.3571 13.2339 27.4768 12.9498 27.6424V33.1617H10.4755V29.2723C10.4755 28.8933 10.4656 28.5711 10.4468 28.3047C10.4291 28.0394 10.3788 27.8229 10.2969 27.6574C10.214 27.4908 10.0897 27.3691 9.92298 27.2933C9.75526 27.2164 9.52144 27.1785 9.21955 27.1785C8.97784 27.1785 8.74205 27.2284 8.51316 27.3272C8.28526 27.4269 8.07907 27.5327 7.89655 27.6424V33.1617H5.42123V25.376H7.89655V26.2359C8.32078 25.8977 8.72725 25.6344 9.11596 25.4448C9.5027 25.2553 9.93284 25.1615 10.4034 25.1615C10.9096 25.1615 11.3565 25.2753 11.7462 25.5037C12.1329 25.7331 12.4368 26.0693 12.6568 26.5132C13.1491 26.0922 13.6286 25.7621 14.0942 25.5217C14.5599 25.2812 15.0157 25.1615 15.4626 25.1615C16.2943 25.1615 16.9257 25.4129 17.3568 25.9167C17.788 26.4204 18.004 27.1456 18.004 28.0943V33.1617ZM53.6667 0H2.33325C1.04972 0 0 1.06137 0 2.35914V53.6409C0 54.9386 1.04972 56 2.33325 56H53.6667C54.9503 56 56 54.9386 56 53.6409V2.35914C56 1.06137 54.9503 0 53.6667 0Z",
    "clip-rule": "evenodd"
  }))), children);
});
MVamNegative.propTypes = iconPropTypes.iconPropTypes;

module.exports = MVamNegative;
