/**
 *
 * Code generated by @wfp/icon-build-helpers. DO NOT EDIT.
 * @wfp/icon-build-helpers is a fork of @carbon/icon-build-helpers
 */
'use strict';

var iconPropTypes = require('./iconPropTypes-dc77abf6.js');
var React = require('react');
require('@carbon/icon-helpers');
require('prop-types');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var React__default = /*#__PURE__*/_interopDefaultLegacy(React);

var _path, _mask, _g, _path2, _path3, _mask2, _g2, _path4;

var _excluded = ["children", "size"];
var P4pNegative = /*#__PURE__*/React__default['default'].forwardRef(function P4pNegative(_ref, ref) {
  var children = _ref.children,
      _ref$size = _ref.size,
      size = _ref$size === void 0 ? 16 : _ref$size,
      rest = iconPropTypes._objectWithoutProperties(_ref, _excluded);

  if (size === "glyph" || size === "glyph" || size === "glyphpx") {
    return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
      width: size,
      height: size,
      ref: ref,
      xmlns: "http://www.w3.org/2000/svg",
      fill: "currentColor",
      viewBox: "0 0 56 56"
    }, rest), _path || (_path = /*#__PURE__*/React__default['default'].createElement("path", {
      d: "M42.3026 24.1998C41.9194 24.0466 41.5432 23.9621 41.1787 23.9464C40.8142 23.9307 40.3259 23.9218 39.7197 23.9218H39.0841V28.1975H40.1402C40.769 28.1975 41.2867 28.1601 41.6935 28.0825C42.0973 28.0059 42.4401 27.8526 42.7182 27.6237C42.952 27.4164 43.122 27.1708 43.23 26.8878C43.3381 26.6049 43.3872 26.2591 43.3872 25.8494C43.3872 25.4456 43.2782 25.0998 43.063 24.809C42.8449 24.5182 42.5885 24.3158 42.3026 24.1998Z",
      "clip-rule": "evenodd"
    })), _mask || (_mask = /*#__PURE__*/React__default['default'].createElement("mask", {
      id: "a",
      style: "mask-type:alpha",
      width: "56",
      height: "56",
      x: "0",
      y: "0",
      maskUnits: "userSpaceOnUse"
    }, /*#__PURE__*/React__default['default'].createElement("path", {
      "fill-rule": "evenodd",
      d: "M0 0H56V56H0V0Z",
      "clip-rule": "evenodd"
    }))), _g || (_g = /*#__PURE__*/React__default['default'].createElement("g", {
      mask: "url(#a)"
    }, /*#__PURE__*/React__default['default'].createElement("path", {
      d: "M28.1061 29.6486V24.4691L23.9405 29.6486H28.1061Z",
      "clip-rule": "evenodd"
    }), /*#__PURE__*/React__default['default'].createElement("path", {
      d: "M47.0616 27.2105C46.8387 27.8289 46.5141 28.3516 46.0968 28.7736C45.5226 29.3482 44.8843 29.7781 44.1828 30.0734C43.4794 30.3666 42.6013 30.5113 41.5546 30.5113H39.2479V35.2415H35.5443V20.7196H41.6414C42.5559 20.7196 43.3255 20.7994 43.9529 20.958C44.5784 21.1166 45.1339 21.355 45.6153 21.6732C46.1944 22.0582 46.6364 22.551 46.9422 23.1485C47.2471 23.7481 47.4 24.4643 47.4 25.3022C47.4 25.9536 47.2885 26.589 47.0616 27.2105ZM33.7192 31.8968H31.7618V35.2804H28.224V31.8968H21.2656V29.1457L27.9911 20.7196H31.7618V29.2444H33.7192V31.8968ZM20.1173 27.2105C19.8933 27.8289 19.5707 28.3516 19.1544 28.7736C18.5802 29.3482 17.9438 29.7781 17.2404 30.0734C16.533 30.3666 15.657 30.5113 14.6112 30.5113H12.3046V35.2415H8.59998V20.7196H14.698C15.6106 20.7196 16.3821 20.7994 17.0076 20.958C17.635 21.1166 18.1905 21.355 18.6719 21.6732C19.251 22.0582 19.693 22.551 19.9989 23.1485C20.3047 23.7481 20.4566 24.4643 20.4566 25.3022C20.4566 25.9536 20.3461 26.589 20.1173 27.2105ZM53.6667 0H2.33325C1.04972 0 0 1.06137 0 2.35914V53.6409C0 54.9386 1.04972 56 2.33325 56H53.6667C54.9503 56 56 54.9386 56 53.6409V2.35914C56 1.06137 54.9503 0 53.6667 0Z",
      "clip-rule": "evenodd"
    }))), _path2 || (_path2 = /*#__PURE__*/React__default['default'].createElement("path", {
      d: "M15.4727 24.1998C15.0895 24.0466 14.7113 23.9621 14.3448 23.9464C13.9843 23.9307 13.496 23.9218 12.8898 23.9218H12.2532V28.1975H13.3093C13.9352 28.1975 14.4549 28.1601 14.8636 28.0825C15.2674 28.0059 15.6093 27.8526 15.8853 27.6237C16.1221 27.4164 16.2921 27.1708 16.3992 26.8878C16.5013 26.6049 16.5563 26.2591 16.5563 25.8494C16.5563 25.4456 16.4483 25.0998 16.2321 24.809C16.0111 24.5182 15.7606 24.3158 15.4727 24.1998Z",
      "clip-rule": "evenodd"
    })), children);
  }

  return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
    width: size,
    height: size,
    ref: ref,
    xmlns: "http://www.w3.org/2000/svg",
    fill: "currentColor",
    viewBox: "0 0 56 56"
  }, rest), _path3 || (_path3 = /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M42.3026 24.1998C41.9194 24.0466 41.5432 23.9621 41.1787 23.9464C40.8142 23.9307 40.3259 23.9218 39.7197 23.9218H39.0841V28.1975H40.1402C40.769 28.1975 41.2867 28.1601 41.6935 28.0825C42.0973 28.0059 42.4401 27.8526 42.7182 27.6237C42.952 27.4164 43.122 27.1708 43.23 26.8878C43.3381 26.6049 43.3872 26.2591 43.3872 25.8494C43.3872 25.4456 43.2782 25.0998 43.063 24.809C42.8449 24.5182 42.5885 24.3158 42.3026 24.1998Z",
    "clip-rule": "evenodd"
  })), _mask2 || (_mask2 = /*#__PURE__*/React__default['default'].createElement("mask", {
    id: "a",
    style: "mask-type:alpha",
    width: "56",
    height: "56",
    x: "0",
    y: "0",
    maskUnits: "userSpaceOnUse"
  }, /*#__PURE__*/React__default['default'].createElement("path", {
    "fill-rule": "evenodd",
    d: "M0 0H56V56H0V0Z",
    "clip-rule": "evenodd"
  }))), _g2 || (_g2 = /*#__PURE__*/React__default['default'].createElement("g", {
    mask: "url(#a)"
  }, /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M28.1061 29.6486V24.4691L23.9405 29.6486H28.1061Z",
    "clip-rule": "evenodd"
  }), /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M47.0616 27.2105C46.8387 27.8289 46.5141 28.3516 46.0968 28.7736C45.5226 29.3482 44.8843 29.7781 44.1828 30.0734C43.4794 30.3666 42.6013 30.5113 41.5546 30.5113H39.2479V35.2415H35.5443V20.7196H41.6414C42.5559 20.7196 43.3255 20.7994 43.9529 20.958C44.5784 21.1166 45.1339 21.355 45.6153 21.6732C46.1944 22.0582 46.6364 22.551 46.9422 23.1485C47.2471 23.7481 47.4 24.4643 47.4 25.3022C47.4 25.9536 47.2885 26.589 47.0616 27.2105ZM33.7192 31.8968H31.7618V35.2804H28.224V31.8968H21.2656V29.1457L27.9911 20.7196H31.7618V29.2444H33.7192V31.8968ZM20.1173 27.2105C19.8933 27.8289 19.5707 28.3516 19.1544 28.7736C18.5802 29.3482 17.9438 29.7781 17.2404 30.0734C16.533 30.3666 15.657 30.5113 14.6112 30.5113H12.3046V35.2415H8.59998V20.7196H14.698C15.6106 20.7196 16.3821 20.7994 17.0076 20.958C17.635 21.1166 18.1905 21.355 18.6719 21.6732C19.251 22.0582 19.693 22.551 19.9989 23.1485C20.3047 23.7481 20.4566 24.4643 20.4566 25.3022C20.4566 25.9536 20.3461 26.589 20.1173 27.2105ZM53.6667 0H2.33325C1.04972 0 0 1.06137 0 2.35914V53.6409C0 54.9386 1.04972 56 2.33325 56H53.6667C54.9503 56 56 54.9386 56 53.6409V2.35914C56 1.06137 54.9503 0 53.6667 0Z",
    "clip-rule": "evenodd"
  }))), _path4 || (_path4 = /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M15.4727 24.1998C15.0895 24.0466 14.7113 23.9621 14.3448 23.9464C13.9843 23.9307 13.496 23.9218 12.8898 23.9218H12.2532V28.1975H13.3093C13.9352 28.1975 14.4549 28.1601 14.8636 28.0825C15.2674 28.0059 15.6093 27.8526 15.8853 27.6237C16.1221 27.4164 16.2921 27.1708 16.3992 26.8878C16.5013 26.6049 16.5563 26.2591 16.5563 25.8494C16.5563 25.4456 16.4483 25.0998 16.2321 24.809C16.0111 24.5182 15.7606 24.3158 15.4727 24.1998Z",
    "clip-rule": "evenodd"
  })), children);
});
P4pNegative.propTypes = iconPropTypes.iconPropTypes;

module.exports = P4pNegative;
