/**
 *
 * Code generated by @wfp/icon-build-helpers. DO NOT EDIT.
 * @wfp/icon-build-helpers is a fork of @carbon/icon-build-helpers
 */
'use strict';

var iconPropTypes = require('./iconPropTypes-dc77abf6.js');
var React = require('react');
require('@carbon/icon-helpers');
require('prop-types');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var React__default = /*#__PURE__*/_interopDefaultLegacy(React);

var _mask, _g, _mask2, _g2;

var _excluded = ["children", "size"];
var PopulationDisplacementNegative = /*#__PURE__*/React__default['default'].forwardRef(function PopulationDisplacementNegative(_ref, ref) {
  var children = _ref.children,
      _ref$size = _ref.size,
      size = _ref$size === void 0 ? 16 : _ref$size,
      rest = iconPropTypes._objectWithoutProperties(_ref, _excluded);

  if (size === "glyph" || size === "glyph" || size === "glyphpx") {
    return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
      width: size,
      height: size,
      ref: ref,
      xmlns: "http://www.w3.org/2000/svg",
      fill: "currentColor",
      viewBox: "0 0 56 56"
    }, rest), _mask || (_mask = /*#__PURE__*/React__default['default'].createElement("mask", {
      id: "a",
      style: "mask-type:alpha",
      width: "56",
      height: "56",
      x: "0",
      y: "0",
      maskUnits: "userSpaceOnUse"
    }, /*#__PURE__*/React__default['default'].createElement("path", {
      "fill-rule": "evenodd",
      d: "M0 0H56V56H0V0Z",
      "clip-rule": "evenodd"
    }))), _g || (_g = /*#__PURE__*/React__default['default'].createElement("g", {
      mask: "url(#a)"
    }, /*#__PURE__*/React__default['default'].createElement("path", {
      d: "M47.8538 28.9172L42.0765 34.7587C41.8239 35.0141 41.4934 35.1408 41.1629 35.1408C40.8324 35.1408 40.5019 35.0141 40.2503 34.7587C39.7462 34.249 39.7462 33.422 40.2503 32.9133L43.8681 29.2554H32.8461C32.1574 29.2554 31.599 28.6908 31.599 27.9935C31.599 27.2972 32.1574 26.7326 32.8461 26.7326H43.8681L40.2503 23.0747C39.7462 22.564 39.7462 21.738 40.2503 21.2283C40.7544 20.7176 41.5713 20.7176 42.0765 21.2283L47.8538 27.0708C48.0975 27.3152 48.2327 27.6474 48.2327 27.9935C48.2327 28.3407 48.0975 28.6718 47.8538 28.9172ZM26.7747 14.3394C26.2005 12.5758 27.1496 10.6745 28.8948 10.0939C30.6401 9.51239 32.5205 10.472 33.0957 12.2366C33.6689 14.0012 32.7208 15.9025 30.9755 16.4831C29.2303 17.0636 27.3489 16.104 26.7747 14.3394ZM29.3704 45.126C29.1494 45.5569 28.7784 45.8562 28.3542 45.9908C27.9309 46.1265 27.4564 46.0986 27.0302 45.8751C26.1798 45.4282 25.8483 44.3699 26.2903 43.509C28.4055 39.3902 26.8516 34.3148 22.8372 32.1063L19.1149 30.207L11.5952 45.115C11.2874 45.7235 10.6787 46.0726 10.0463 46.0726C9.7819 46.0726 9.51157 46.0118 9.25901 45.8821C8.40562 45.4412 8.06624 44.3838 8.50231 43.52L20.8819 18.9779C17.494 18.548 14.0439 20.2507 12.4013 23.4977C11.9681 24.3526 10.9322 24.6907 10.0867 24.2528C9.24125 23.8159 8.90582 22.7675 9.33892 21.9126C12.1921 16.2766 18.8998 13.9274 24.5608 16.4402C24.6812 16.4701 24.7995 16.51 24.915 16.5689L27.042 17.6532C29.031 18.6687 29.8311 21.1236 28.8258 23.1356L25.5572 29.6853C30.425 33.0739 32.1633 39.6895 29.3704 45.126ZM53.6667 0H2.33325C1.04972 0 0 1.06137 0 2.35914V53.6409C0 54.9386 1.04972 56 2.33325 56H53.6667C54.9503 56 56 54.9386 56 53.6409V2.35914C56 1.06137 54.9503 0 53.6667 0Z",
      "clip-rule": "evenodd"
    }))), children);
  }

  return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
    width: size,
    height: size,
    ref: ref,
    xmlns: "http://www.w3.org/2000/svg",
    fill: "currentColor",
    viewBox: "0 0 56 56"
  }, rest), _mask2 || (_mask2 = /*#__PURE__*/React__default['default'].createElement("mask", {
    id: "a",
    style: "mask-type:alpha",
    width: "56",
    height: "56",
    x: "0",
    y: "0",
    maskUnits: "userSpaceOnUse"
  }, /*#__PURE__*/React__default['default'].createElement("path", {
    "fill-rule": "evenodd",
    d: "M0 0H56V56H0V0Z",
    "clip-rule": "evenodd"
  }))), _g2 || (_g2 = /*#__PURE__*/React__default['default'].createElement("g", {
    mask: "url(#a)"
  }, /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M47.8538 28.9172L42.0765 34.7587C41.8239 35.0141 41.4934 35.1408 41.1629 35.1408C40.8324 35.1408 40.5019 35.0141 40.2503 34.7587C39.7462 34.249 39.7462 33.422 40.2503 32.9133L43.8681 29.2554H32.8461C32.1574 29.2554 31.599 28.6908 31.599 27.9935C31.599 27.2972 32.1574 26.7326 32.8461 26.7326H43.8681L40.2503 23.0747C39.7462 22.564 39.7462 21.738 40.2503 21.2283C40.7544 20.7176 41.5713 20.7176 42.0765 21.2283L47.8538 27.0708C48.0975 27.3152 48.2327 27.6474 48.2327 27.9935C48.2327 28.3407 48.0975 28.6718 47.8538 28.9172ZM26.7747 14.3394C26.2005 12.5758 27.1496 10.6745 28.8948 10.0939C30.6401 9.51239 32.5205 10.472 33.0957 12.2366C33.6689 14.0012 32.7208 15.9025 30.9755 16.4831C29.2303 17.0636 27.3489 16.104 26.7747 14.3394ZM29.3704 45.126C29.1494 45.5569 28.7784 45.8562 28.3542 45.9908C27.9309 46.1265 27.4564 46.0986 27.0302 45.8751C26.1798 45.4282 25.8483 44.3699 26.2903 43.509C28.4055 39.3902 26.8516 34.3148 22.8372 32.1063L19.1149 30.207L11.5952 45.115C11.2874 45.7235 10.6787 46.0726 10.0463 46.0726C9.7819 46.0726 9.51157 46.0118 9.25901 45.8821C8.40562 45.4412 8.06624 44.3838 8.50231 43.52L20.8819 18.9779C17.494 18.548 14.0439 20.2507 12.4013 23.4977C11.9681 24.3526 10.9322 24.6907 10.0867 24.2528C9.24125 23.8159 8.90582 22.7675 9.33892 21.9126C12.1921 16.2766 18.8998 13.9274 24.5608 16.4402C24.6812 16.4701 24.7995 16.51 24.915 16.5689L27.042 17.6532C29.031 18.6687 29.8311 21.1236 28.8258 23.1356L25.5572 29.6853C30.425 33.0739 32.1633 39.6895 29.3704 45.126ZM53.6667 0H2.33325C1.04972 0 0 1.06137 0 2.35914V53.6409C0 54.9386 1.04972 56 2.33325 56H53.6667C54.9503 56 56 54.9386 56 53.6409V2.35914C56 1.06137 54.9503 0 53.6667 0Z",
    "clip-rule": "evenodd"
  }))), children);
});
PopulationDisplacementNegative.propTypes = iconPropTypes.iconPropTypes;

module.exports = PopulationDisplacementNegative;
