/**
 *
 * Code generated by @wfp/icon-build-helpers. DO NOT EDIT.
 * @wfp/icon-build-helpers is a fork of @carbon/icon-build-helpers
 */
'use strict';

var iconPropTypes = require('./iconPropTypes-dc77abf6.js');
var React = require('react');
require('@carbon/icon-helpers');
require('prop-types');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var React__default = /*#__PURE__*/_interopDefaultLegacy(React);

var _mask, _g, _mask2, _g2;

var _excluded = ["children", "size"];
var PopulationDisplacementPositive = /*#__PURE__*/React__default['default'].forwardRef(function PopulationDisplacementPositive(_ref, ref) {
  var children = _ref.children,
      _ref$size = _ref.size,
      size = _ref$size === void 0 ? 16 : _ref$size,
      rest = iconPropTypes._objectWithoutProperties(_ref, _excluded);

  if (size === "glyph" || size === "glyph" || size === "glyphpx") {
    return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
      width: size,
      height: size,
      ref: ref,
      xmlns: "http://www.w3.org/2000/svg",
      fill: "currentColor",
      viewBox: "0 0 41 37"
    }, rest), _mask || (_mask = /*#__PURE__*/React__default['default'].createElement("mask", {
      id: "a",
      width: "41",
      height: "37",
      x: "0",
      y: "0",
      maskUnits: "userSpaceOnUse"
    }, /*#__PURE__*/React__default['default'].createElement("path", {
      "fill-rule": "evenodd",
      d: "M0.000244141 0.760986H40.464V36.94H0.000244141V0.760986Z",
      "clip-rule": "evenodd"
    }))), _g || (_g = /*#__PURE__*/React__default['default'].createElement("g", {
      mask: "url(#a)"
    }, /*#__PURE__*/React__default['default'].createElement("path", {
      d: "M40.08 19.801L34.224 25.658C33.968 25.913 33.633 26.041 33.298 26.041C32.963 26.041 32.628 25.913 32.373 25.658C31.861 25.146 31.861 24.318 32.373 23.807L36.04 20.14H24.868C24.17 20.14 23.604 19.574 23.604 18.875C23.604 18.177 24.17 17.611 24.868 17.611H36.04L32.373 13.944C31.861 13.433 31.861 12.604 32.373 12.093C32.884 11.582 33.712 11.582 34.224 12.093L40.08 17.95C40.326 18.196 40.464 18.529 40.464 18.876C40.464 19.223 40.326 19.556 40.08 19.801ZM18.714 5.188C18.132 3.419 19.094 1.513 20.862 0.931001C22.632 0.348001 24.537 1.31 25.12 3.079C25.702 4.848 24.74 6.754 22.972 7.337C21.202 7.919 19.296 6.957 18.714 5.188ZM21.345 36.051C21.121 36.482 20.744 36.782 20.315 36.918C19.886 37.054 19.404 37.026 18.973 36.802C18.111 36.353 17.775 35.292 18.223 34.43C20.367 30.3 18.792 25.213 14.723 22.998L10.949 21.095L3.32701 36.039C3.01601 36.649 2.39901 37 1.75801 37C1.48901 37 1.21601 36.938 0.960014 36.808C0.0950142 36.366 -0.248986 35.307 0.193014 34.441L12.74 9.838C9.30701 9.407 5.81001 11.114 4.14501 14.368C3.70601 15.225 2.65501 15.565 1.79901 15.126C0.942014 14.688 0.602014 13.637 1.04101 12.78C3.93301 7.129 10.732 4.775 16.47 7.294C16.592 7.323 16.712 7.364 16.829 7.422L18.985 8.51C21.001 9.528 21.812 11.988 20.793 14.005L17.48 20.572C22.414 23.968 24.176 30.6 21.345 36.051Z",
      "clip-rule": "evenodd"
    }))), children);
  }

  return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
    width: size,
    height: size,
    ref: ref,
    xmlns: "http://www.w3.org/2000/svg",
    fill: "currentColor",
    viewBox: "0 0 41 37"
  }, rest), _mask2 || (_mask2 = /*#__PURE__*/React__default['default'].createElement("mask", {
    id: "a",
    width: "41",
    height: "37",
    x: "0",
    y: "0",
    maskUnits: "userSpaceOnUse"
  }, /*#__PURE__*/React__default['default'].createElement("path", {
    "fill-rule": "evenodd",
    d: "M0.000244141 0.760986H40.464V36.94H0.000244141V0.760986Z",
    "clip-rule": "evenodd"
  }))), _g2 || (_g2 = /*#__PURE__*/React__default['default'].createElement("g", {
    mask: "url(#a)"
  }, /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M40.08 19.801L34.224 25.658C33.968 25.913 33.633 26.041 33.298 26.041C32.963 26.041 32.628 25.913 32.373 25.658C31.861 25.146 31.861 24.318 32.373 23.807L36.04 20.14H24.868C24.17 20.14 23.604 19.574 23.604 18.875C23.604 18.177 24.17 17.611 24.868 17.611H36.04L32.373 13.944C31.861 13.433 31.861 12.604 32.373 12.093C32.884 11.582 33.712 11.582 34.224 12.093L40.08 17.95C40.326 18.196 40.464 18.529 40.464 18.876C40.464 19.223 40.326 19.556 40.08 19.801ZM18.714 5.188C18.132 3.419 19.094 1.513 20.862 0.931001C22.632 0.348001 24.537 1.31 25.12 3.079C25.702 4.848 24.74 6.754 22.972 7.337C21.202 7.919 19.296 6.957 18.714 5.188ZM21.345 36.051C21.121 36.482 20.744 36.782 20.315 36.918C19.886 37.054 19.404 37.026 18.973 36.802C18.111 36.353 17.775 35.292 18.223 34.43C20.367 30.3 18.792 25.213 14.723 22.998L10.949 21.095L3.32701 36.039C3.01601 36.649 2.39901 37 1.75801 37C1.48901 37 1.21601 36.938 0.960014 36.808C0.0950142 36.366 -0.248986 35.307 0.193014 34.441L12.74 9.838C9.30701 9.407 5.81001 11.114 4.14501 14.368C3.70601 15.225 2.65501 15.565 1.79901 15.126C0.942014 14.688 0.602014 13.637 1.04101 12.78C3.93301 7.129 10.732 4.775 16.47 7.294C16.592 7.323 16.712 7.364 16.829 7.422L18.985 8.51C21.001 9.528 21.812 11.988 20.793 14.005L17.48 20.572C22.414 23.968 24.176 30.6 21.345 36.051Z",
    "clip-rule": "evenodd"
  }))), children);
});
PopulationDisplacementPositive.propTypes = iconPropTypes.iconPropTypes;

module.exports = PopulationDisplacementPositive;
