/**
 *
 * Code generated by @wfp/icon-build-helpers. DO NOT EDIT.
 * @wfp/icon-build-helpers is a fork of @carbon/icon-build-helpers
 */
'use strict';

var iconPropTypes = require('./iconPropTypes-dc77abf6.js');
var React = require('react');
require('@carbon/icon-helpers');
require('prop-types');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var React__default = /*#__PURE__*/_interopDefaultLegacy(React);

var _mask, _g, _path, _mask2, _g2, _path2;

var _excluded = ["children", "size"];
var PregnantNegative = /*#__PURE__*/React__default['default'].forwardRef(function PregnantNegative(_ref, ref) {
  var children = _ref.children,
      _ref$size = _ref.size,
      size = _ref$size === void 0 ? 16 : _ref$size,
      rest = iconPropTypes._objectWithoutProperties(_ref, _excluded);

  if (size === "glyph" || size === "glyph" || size === "glyphpx") {
    return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
      width: size,
      height: size,
      ref: ref,
      xmlns: "http://www.w3.org/2000/svg",
      fill: "currentColor",
      viewBox: "0 0 56 56"
    }, rest), _mask || (_mask = /*#__PURE__*/React__default['default'].createElement("mask", {
      id: "a",
      width: "56",
      height: "56",
      x: "0",
      y: "0",
      maskUnits: "userSpaceOnUse"
    }, /*#__PURE__*/React__default['default'].createElement("path", {
      "fill-rule": "evenodd",
      d: "M0 0H56V56H0V0Z",
      "clip-rule": "evenodd"
    }))), _g || (_g = /*#__PURE__*/React__default['default'].createElement("g", {
      mask: "url(#a)"
    }, /*#__PURE__*/React__default['default'].createElement("path", {
      d: "M35.3115 34.5163C35.0619 35.5518 34.5301 36.4595 33.8228 37.082V46.5006C33.8228 47.4253 33.074 48.1814 32.1584 48.1814C31.2448 48.1814 30.496 47.4253 30.496 46.5006V38.0915H28.8317V46.5006C28.8317 47.4293 28.0868 48.1814 27.1693 48.1814C26.2498 48.1814 25.505 47.4293 25.505 46.5006V38.0915H22.3696C21.7047 38.0915 21.2222 37.3513 21.3722 36.5692L25.505 19.5914C22.2246 20.3934 19.6832 23.5984 19.6832 27.1586C19.6832 28.0873 18.9383 28.8404 18.0188 28.8404C17.1003 28.8404 16.3564 28.0873 16.3564 27.1586C16.3564 21.1974 21.1009 16.3444 26.972 16.2367C26.974 16.2367 26.9759 16.2357 26.9769 16.2357C26.9947 16.2277 27.0193 16.2277 27.0361 16.2277H27.1614C27.1634 16.2277 27.1663 16.2267 27.1693 16.2267C27.1703 16.2267 27.1723 16.2277 27.1733 16.2277H32.6418C33.1904 16.2277 33.6481 16.7145 33.7221 17.3629L34.6544 22.955V22.971C37.482 23.383 39.6436 25.8389 39.6436 28.8075C39.6436 31.5407 37.8066 33.844 35.3115 34.5163ZM30.496 7.8176C32.333 7.8176 33.8228 9.32386 33.8228 11.1812C33.8228 13.0396 32.333 14.5449 30.496 14.5449C28.658 14.5449 27.1693 13.0396 27.1693 11.1812C27.1693 9.32386 28.658 7.8176 30.496 7.8176ZM53.6667 0H2.33325C1.04972 0 0 1.06137 0 2.35914V53.6409C0 54.9386 1.04972 56 2.33325 56H53.6667C54.9503 56 56 54.9386 56 53.6409V2.35914C56 1.06137 54.9503 0 53.6667 0Z",
      "clip-rule": "evenodd"
    }))), _path || (_path = /*#__PURE__*/React__default['default'].createElement("path", {
      d: "M34.6168 26.8663C34.3358 26.9576 34.0696 27.1227 33.8466 27.3545L33.6815 27.5206L33.5155 27.3545C32.8111 26.6256 31.6606 26.5519 30.9395 27.2553C30.1948 27.9843 30.1771 29.2016 30.8982 29.9472L32.0418 31.1311L33.2502 32.3818C33.3671 32.4977 33.5155 32.5557 33.6638 32.5645C33.821 32.5645 33.9871 32.5065 34.1118 32.3818L35.1297 31.3296L36.2487 30.1703L36.4638 29.9472C37.184 29.2016 37.1683 27.9843 36.4226 27.2553C35.9255 26.7749 35.2387 26.659 34.6168 26.8663Z",
      "clip-rule": "evenodd"
    })), children);
  }

  return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
    width: size,
    height: size,
    ref: ref,
    xmlns: "http://www.w3.org/2000/svg",
    fill: "currentColor",
    viewBox: "0 0 56 56"
  }, rest), _mask2 || (_mask2 = /*#__PURE__*/React__default['default'].createElement("mask", {
    id: "a",
    width: "56",
    height: "56",
    x: "0",
    y: "0",
    maskUnits: "userSpaceOnUse"
  }, /*#__PURE__*/React__default['default'].createElement("path", {
    "fill-rule": "evenodd",
    d: "M0 0H56V56H0V0Z",
    "clip-rule": "evenodd"
  }))), _g2 || (_g2 = /*#__PURE__*/React__default['default'].createElement("g", {
    mask: "url(#a)"
  }, /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M35.3115 34.5163C35.0619 35.5518 34.5301 36.4595 33.8228 37.082V46.5006C33.8228 47.4253 33.074 48.1814 32.1584 48.1814C31.2448 48.1814 30.496 47.4253 30.496 46.5006V38.0915H28.8317V46.5006C28.8317 47.4293 28.0868 48.1814 27.1693 48.1814C26.2498 48.1814 25.505 47.4293 25.505 46.5006V38.0915H22.3696C21.7047 38.0915 21.2222 37.3513 21.3722 36.5692L25.505 19.5914C22.2246 20.3934 19.6832 23.5984 19.6832 27.1586C19.6832 28.0873 18.9383 28.8404 18.0188 28.8404C17.1003 28.8404 16.3564 28.0873 16.3564 27.1586C16.3564 21.1974 21.1009 16.3444 26.972 16.2367C26.974 16.2367 26.9759 16.2357 26.9769 16.2357C26.9947 16.2277 27.0193 16.2277 27.0361 16.2277H27.1614C27.1634 16.2277 27.1663 16.2267 27.1693 16.2267C27.1703 16.2267 27.1723 16.2277 27.1733 16.2277H32.6418C33.1904 16.2277 33.6481 16.7145 33.7221 17.3629L34.6544 22.955V22.971C37.482 23.383 39.6436 25.8389 39.6436 28.8075C39.6436 31.5407 37.8066 33.844 35.3115 34.5163ZM30.496 7.8176C32.333 7.8176 33.8228 9.32386 33.8228 11.1812C33.8228 13.0396 32.333 14.5449 30.496 14.5449C28.658 14.5449 27.1693 13.0396 27.1693 11.1812C27.1693 9.32386 28.658 7.8176 30.496 7.8176ZM53.6667 0H2.33325C1.04972 0 0 1.06137 0 2.35914V53.6409C0 54.9386 1.04972 56 2.33325 56H53.6667C54.9503 56 56 54.9386 56 53.6409V2.35914C56 1.06137 54.9503 0 53.6667 0Z",
    "clip-rule": "evenodd"
  }))), _path2 || (_path2 = /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M34.6168 26.8663C34.3358 26.9576 34.0696 27.1227 33.8466 27.3545L33.6815 27.5206L33.5155 27.3545C32.8111 26.6256 31.6606 26.5519 30.9395 27.2553C30.1948 27.9843 30.1771 29.2016 30.8982 29.9472L32.0418 31.1311L33.2502 32.3818C33.3671 32.4977 33.5155 32.5557 33.6638 32.5645C33.821 32.5645 33.9871 32.5065 34.1118 32.3818L35.1297 31.3296L36.2487 30.1703L36.4638 29.9472C37.184 29.2016 37.1683 27.9843 36.4226 27.2553C35.9255 26.7749 35.2387 26.659 34.6168 26.8663Z",
    "clip-rule": "evenodd"
  })), children);
});
PregnantNegative.propTypes = iconPropTypes.iconPropTypes;

module.exports = PregnantNegative;
