/**
 *
 * Code generated by @wfp/icon-build-helpers. DO NOT EDIT.
 * @wfp/icon-build-helpers is a fork of @carbon/icon-build-helpers
 */
'use strict';

var iconPropTypes = require('./iconPropTypes-dc77abf6.js');
var React = require('react');
require('@carbon/icon-helpers');
require('prop-types');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var React__default = /*#__PURE__*/_interopDefaultLegacy(React);

var _mask, _g, _mask2, _g2;

var _excluded = ["children", "size"];
var ProtectionClusterPositive = /*#__PURE__*/React__default['default'].forwardRef(function ProtectionClusterPositive(_ref, ref) {
  var children = _ref.children,
      _ref$size = _ref.size,
      size = _ref$size === void 0 ? 16 : _ref$size,
      rest = iconPropTypes._objectWithoutProperties(_ref, _excluded);

  if (size === "glyph" || size === "glyph" || size === "glyphpx") {
    return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
      width: size,
      height: size,
      ref: ref,
      xmlns: "http://www.w3.org/2000/svg",
      fill: "currentColor",
      viewBox: "0 0 39 39"
    }, rest), _mask || (_mask = /*#__PURE__*/React__default['default'].createElement("mask", {
      id: "a",
      width: "39",
      height: "39",
      x: "0",
      y: "0",
      maskUnits: "userSpaceOnUse"
    }, /*#__PURE__*/React__default['default'].createElement("path", {
      "fill-rule": "evenodd",
      d: "M0.0600586 0.559021H38.44V39H0.0600586V0.559021Z",
      "clip-rule": "evenodd"
    }))), _g || (_g = /*#__PURE__*/React__default['default'].createElement("g", {
      mask: "url(#a)"
    }, /*#__PURE__*/React__default['default'].createElement("path", {
      d: "M38.44 20.9C38.44 21.538 38.191 22.15 37.748 22.601L30.164 30.301C29.764 30.708 29.312 31.027 28.83 31.268V39H21.623V26.987H21.637C21.56 25.591 22.04 24.169 23.089 23.102L29.39 16.691C30.041 16.028 31.099 16.028 31.75 16.691C32.402 17.355 32.402 18.43 31.75 19.093L28.503 22.399C28.123 22.785 28.123 23.411 28.503 23.797C28.882 24.184 29.498 24.184 29.786 23.659L33.636 19.779V6.96602C33.636 5.63902 34.734 4.56402 36.038 4.56402C37.343 4.56402 38.44 5.63902 38.44 6.96602V20.9ZM12.013 7.76702C12.013 3.78602 15.24 0.559021 19.221 0.559021C23.201 0.559021 26.428 3.78602 26.428 7.76702C26.428 11.748 23.201 14.974 19.221 14.974C15.24 14.974 12.013 11.748 12.013 7.76702ZM16.817 39H9.60999V31.268C9.12899 31.027 8.67699 30.708 8.276 30.301L0.693 22.601C0.249 22.15 0 21.538 0 20.9V6.96602C0 5.63902 1.099 4.56402 2.402 4.56402C3.707 4.56402 4.805 5.63902 4.805 6.96602V19.779L8.564 23.797C8.94299 24.184 9.55899 24.184 9.93799 23.797C10.318 23.411 10.318 22.785 9.93799 22.399L6.69 19.093C6.038 18.43 6.038 17.355 6.69 16.691C7.343 16.028 8.399 16.028 9.05199 16.691L15.353 23.102C16.4 24.169 16.881 25.591 16.805 26.987H16.817V39Z",
      "clip-rule": "evenodd"
    }))), children);
  }

  return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
    width: size,
    height: size,
    ref: ref,
    xmlns: "http://www.w3.org/2000/svg",
    fill: "currentColor",
    viewBox: "0 0 39 39"
  }, rest), _mask2 || (_mask2 = /*#__PURE__*/React__default['default'].createElement("mask", {
    id: "a",
    width: "39",
    height: "39",
    x: "0",
    y: "0",
    maskUnits: "userSpaceOnUse"
  }, /*#__PURE__*/React__default['default'].createElement("path", {
    "fill-rule": "evenodd",
    d: "M0.0600586 0.559021H38.44V39H0.0600586V0.559021Z",
    "clip-rule": "evenodd"
  }))), _g2 || (_g2 = /*#__PURE__*/React__default['default'].createElement("g", {
    mask: "url(#a)"
  }, /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M38.44 20.9C38.44 21.538 38.191 22.15 37.748 22.601L30.164 30.301C29.764 30.708 29.312 31.027 28.83 31.268V39H21.623V26.987H21.637C21.56 25.591 22.04 24.169 23.089 23.102L29.39 16.691C30.041 16.028 31.099 16.028 31.75 16.691C32.402 17.355 32.402 18.43 31.75 19.093L28.503 22.399C28.123 22.785 28.123 23.411 28.503 23.797C28.882 24.184 29.498 24.184 29.786 23.659L33.636 19.779V6.96602C33.636 5.63902 34.734 4.56402 36.038 4.56402C37.343 4.56402 38.44 5.63902 38.44 6.96602V20.9ZM12.013 7.76702C12.013 3.78602 15.24 0.559021 19.221 0.559021C23.201 0.559021 26.428 3.78602 26.428 7.76702C26.428 11.748 23.201 14.974 19.221 14.974C15.24 14.974 12.013 11.748 12.013 7.76702ZM16.817 39H9.60999V31.268C9.12899 31.027 8.67699 30.708 8.276 30.301L0.693 22.601C0.249 22.15 0 21.538 0 20.9V6.96602C0 5.63902 1.099 4.56402 2.402 4.56402C3.707 4.56402 4.805 5.63902 4.805 6.96602V19.779L8.564 23.797C8.94299 24.184 9.55899 24.184 9.93799 23.797C10.318 23.411 10.318 22.785 9.93799 22.399L6.69 19.093C6.038 18.43 6.038 17.355 6.69 16.691C7.343 16.028 8.399 16.028 9.05199 16.691L15.353 23.102C16.4 24.169 16.881 25.591 16.805 26.987H16.817V39Z",
    "clip-rule": "evenodd"
  }))), children);
});
ProtectionClusterPositive.propTypes = iconPropTypes.iconPropTypes;

module.exports = ProtectionClusterPositive;
