/**
 *
 * Code generated by @wfp/icon-build-helpers. DO NOT EDIT.
 * @wfp/icon-build-helpers is a fork of @carbon/icon-build-helpers
 */
'use strict';

var iconPropTypes = require('./iconPropTypes-dc77abf6.js');
var React = require('react');
require('@carbon/icon-helpers');
require('prop-types');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var React__default = /*#__PURE__*/_interopDefaultLegacy(React);

var _mask, _g, _mask2, _g2;

var _excluded = ["children", "size"];
var PublicInformationNegative = /*#__PURE__*/React__default['default'].forwardRef(function PublicInformationNegative(_ref, ref) {
  var children = _ref.children,
      _ref$size = _ref.size,
      size = _ref$size === void 0 ? 16 : _ref$size,
      rest = iconPropTypes._objectWithoutProperties(_ref, _excluded);

  if (size === "glyph" || size === "glyph" || size === "glyphpx") {
    return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
      width: size,
      height: size,
      ref: ref,
      xmlns: "http://www.w3.org/2000/svg",
      fill: "currentColor",
      viewBox: "0 0 56 56"
    }, rest), _mask || (_mask = /*#__PURE__*/React__default['default'].createElement("mask", {
      id: "a",
      style: "mask-type:alpha",
      width: "56",
      height: "56",
      x: "0",
      y: "0",
      maskUnits: "userSpaceOnUse"
    }, /*#__PURE__*/React__default['default'].createElement("path", {
      "fill-rule": "evenodd",
      d: "M0 0H56V56H0V0Z",
      "clip-rule": "evenodd"
    }))), _g || (_g = /*#__PURE__*/React__default['default'].createElement("g", {
      mask: "url(#a)"
    }, /*#__PURE__*/React__default['default'].createElement("path", {
      d: "M29.5805 39.4521V43.9768H32.7583C33.3216 43.9768 33.877 44.2641 34.1266 44.7749C34.7196 45.9789 33.8682 47.1729 32.7405 47.1729H23.2427C22.6784 47.1729 22.124 46.8856 21.8724 46.3749C21.2814 45.1709 22.1318 43.9768 23.2595 43.9768H26.4195V39.4601C21.0703 38.693 16.9395 34.0325 16.9395 28.3995C16.9395 27.7382 17.4703 27.2015 18.1244 27.2015C18.7785 27.2015 19.3093 27.7382 19.3093 28.3995C19.3093 33.2445 23.1924 37.1867 27.9674 37.1867C32.777 37.1867 36.6907 33.2445 36.6907 28.3995C36.6907 27.7382 37.2215 27.2015 37.8766 27.2015C38.5307 27.2015 39.0615 27.7382 39.0615 28.3995C39.0615 34.0126 34.9337 38.66 29.5805 39.4521ZM21.679 15.2013C21.679 11.695 24.5154 8.82709 27.9832 8.82709H28.0168C31.4846 8.82709 34.321 11.695 34.321 15.2013V28.8165C34.321 32.3218 31.4846 35.1897 28.0168 35.1897H27.9832C24.5154 35.1897 21.679 32.3218 21.679 28.8165V15.2013ZM53.6667 0H2.33325C1.04972 0 0 1.06137 0 2.35914V53.6409C0 54.9386 1.04972 56 2.33325 56H53.6667C54.9503 56 56 54.9386 56 53.6409V2.35914C56 1.06137 54.9503 0 53.6667 0Z",
      "clip-rule": "evenodd"
    }))), children);
  }

  return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
    width: size,
    height: size,
    ref: ref,
    xmlns: "http://www.w3.org/2000/svg",
    fill: "currentColor",
    viewBox: "0 0 56 56"
  }, rest), _mask2 || (_mask2 = /*#__PURE__*/React__default['default'].createElement("mask", {
    id: "a",
    style: "mask-type:alpha",
    width: "56",
    height: "56",
    x: "0",
    y: "0",
    maskUnits: "userSpaceOnUse"
  }, /*#__PURE__*/React__default['default'].createElement("path", {
    "fill-rule": "evenodd",
    d: "M0 0H56V56H0V0Z",
    "clip-rule": "evenodd"
  }))), _g2 || (_g2 = /*#__PURE__*/React__default['default'].createElement("g", {
    mask: "url(#a)"
  }, /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M29.5805 39.4521V43.9768H32.7583C33.3216 43.9768 33.877 44.2641 34.1266 44.7749C34.7196 45.9789 33.8682 47.1729 32.7405 47.1729H23.2427C22.6784 47.1729 22.124 46.8856 21.8724 46.3749C21.2814 45.1709 22.1318 43.9768 23.2595 43.9768H26.4195V39.4601C21.0703 38.693 16.9395 34.0325 16.9395 28.3995C16.9395 27.7382 17.4703 27.2015 18.1244 27.2015C18.7785 27.2015 19.3093 27.7382 19.3093 28.3995C19.3093 33.2445 23.1924 37.1867 27.9674 37.1867C32.777 37.1867 36.6907 33.2445 36.6907 28.3995C36.6907 27.7382 37.2215 27.2015 37.8766 27.2015C38.5307 27.2015 39.0615 27.7382 39.0615 28.3995C39.0615 34.0126 34.9337 38.66 29.5805 39.4521ZM21.679 15.2013C21.679 11.695 24.5154 8.82709 27.9832 8.82709H28.0168C31.4846 8.82709 34.321 11.695 34.321 15.2013V28.8165C34.321 32.3218 31.4846 35.1897 28.0168 35.1897H27.9832C24.5154 35.1897 21.679 32.3218 21.679 28.8165V15.2013ZM53.6667 0H2.33325C1.04972 0 0 1.06137 0 2.35914V53.6409C0 54.9386 1.04972 56 2.33325 56H53.6667C54.9503 56 56 54.9386 56 53.6409V2.35914C56 1.06137 54.9503 0 53.6667 0Z",
    "clip-rule": "evenodd"
  }))), children);
});
PublicInformationNegative.propTypes = iconPropTypes.iconPropTypes;

module.exports = PublicInformationNegative;
