/**
 *
 * Code generated by @wfp/icon-build-helpers. DO NOT EDIT.
 * @wfp/icon-build-helpers is a fork of @carbon/icon-build-helpers
 */
'use strict';

var iconPropTypes = require('./iconPropTypes-dc77abf6.js');
var React = require('react');
require('@carbon/icon-helpers');
require('prop-types');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var React__default = /*#__PURE__*/_interopDefaultLegacy(React);

var _path, _path2;

var _excluded = ["children", "size"];
var PublicInformationPositive = /*#__PURE__*/React__default['default'].forwardRef(function PublicInformationPositive(_ref, ref) {
  var children = _ref.children,
      _ref$size = _ref.size,
      size = _ref$size === void 0 ? 16 : _ref$size,
      rest = iconPropTypes._objectWithoutProperties(_ref, _excluded);

  if (size === "glyph" || size === "glyph" || size === "glyphpx") {
    return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
      width: size,
      height: size,
      ref: ref,
      xmlns: "http://www.w3.org/2000/svg",
      fill: "currentColor",
      viewBox: "0 0 23 39"
    }, rest), _path || (_path = /*#__PURE__*/React__default['default'].createElement("path", {
      d: "M12.814 30.701V35.237H16.035C16.606 35.237 17.168 35.525 17.422 36.037C18.023 37.244 17.16 38.441 16.017 38.441H6.39C5.818 38.441 5.256 38.153 5.001 37.641C4.402 36.434 5.264 35.237 6.407 35.237H9.61V30.709C4.188 29.941 0 25.268 0 19.621C0 18.958 0.538 18.42 1.201 18.42C1.865 18.42 2.403 18.958 2.403 19.621C2.403 24.479 6.339 28.43 11.179 28.43C16.054 28.43 20.021 24.479 20.021 19.621C20.021 18.958 20.559 18.42 21.223 18.42C21.886 18.42 22.424 18.958 22.424 19.621C22.424 25.248 18.24 29.907 12.814 30.701ZM4.805 6.39C4.805 2.876 7.68 0 11.195 0H11.229C14.744 0 17.618 2.876 17.618 6.39V20.039C17.618 23.553 14.744 26.428 11.229 26.428H11.195C7.68 26.428 4.805 23.553 4.805 20.039V6.39Z",
      "clip-rule": "evenodd"
    })), children);
  }

  return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
    width: size,
    height: size,
    ref: ref,
    xmlns: "http://www.w3.org/2000/svg",
    fill: "currentColor",
    viewBox: "0 0 23 39"
  }, rest), _path2 || (_path2 = /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M12.814 30.701V35.237H16.035C16.606 35.237 17.168 35.525 17.422 36.037C18.023 37.244 17.16 38.441 16.017 38.441H6.39C5.818 38.441 5.256 38.153 5.001 37.641C4.402 36.434 5.264 35.237 6.407 35.237H9.61V30.709C4.188 29.941 0 25.268 0 19.621C0 18.958 0.538 18.42 1.201 18.42C1.865 18.42 2.403 18.958 2.403 19.621C2.403 24.479 6.339 28.43 11.179 28.43C16.054 28.43 20.021 24.479 20.021 19.621C20.021 18.958 20.559 18.42 21.223 18.42C21.886 18.42 22.424 18.958 22.424 19.621C22.424 25.248 18.24 29.907 12.814 30.701ZM4.805 6.39C4.805 2.876 7.68 0 11.195 0H11.229C14.744 0 17.618 2.876 17.618 6.39V20.039C17.618 23.553 14.744 26.428 11.229 26.428H11.195C7.68 26.428 4.805 23.553 4.805 20.039V6.39Z",
    "clip-rule": "evenodd"
  })), children);
});
PublicInformationPositive.propTypes = iconPropTypes.iconPropTypes;

module.exports = PublicInformationPositive;
