/**
 *
 * Code generated by @wfp/icon-build-helpers. DO NOT EDIT.
 * @wfp/icon-build-helpers is a fork of @carbon/icon-build-helpers
 */
'use strict';

var iconPropTypes = require('./iconPropTypes-dc77abf6.js');
var React = require('react');
require('@carbon/icon-helpers');
require('prop-types');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var React__default = /*#__PURE__*/_interopDefaultLegacy(React);

var _mask, _g, _mask2, _g2;

var _excluded = ["children", "size"];
var ReliefGoodsNegative = /*#__PURE__*/React__default['default'].forwardRef(function ReliefGoodsNegative(_ref, ref) {
  var children = _ref.children,
      _ref$size = _ref.size,
      size = _ref$size === void 0 ? 16 : _ref$size,
      rest = iconPropTypes._objectWithoutProperties(_ref, _excluded);

  if (size === "glyph" || size === "glyph" || size === "glyphpx") {
    return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
      width: size,
      height: size,
      ref: ref,
      xmlns: "http://www.w3.org/2000/svg",
      fill: "currentColor",
      viewBox: "0 0 56 56"
    }, rest), _mask || (_mask = /*#__PURE__*/React__default['default'].createElement("mask", {
      id: "a",
      width: "56",
      height: "56",
      x: "0",
      y: "0",
      maskUnits: "userSpaceOnUse"
    }, /*#__PURE__*/React__default['default'].createElement("path", {
      "fill-rule": "evenodd",
      d: "M0 0H56V56H0V0Z",
      "clip-rule": "evenodd"
    }))), _g || (_g = /*#__PURE__*/React__default['default'].createElement("g", {
      mask: "url(#a)"
    }, /*#__PURE__*/React__default['default'].createElement("path", {
      d: "M13.8614 22.1131C13.8614 14.2187 20.1913 7.8176 28 7.8176C35.8087 7.8176 42.1396 14.2187 42.1396 22.1131H13.8614ZM39.2608 25.9665L28.8642 36.0575C28.8563 36.0655 28.8455 36.0675 28.8366 36.0755C28.7241 36.1792 28.5998 36.262 28.4647 36.3169C28.4558 36.3208 28.4469 36.3218 28.4371 36.3248C28.296 36.3787 28.149 36.4086 28 36.4086C27.851 36.4086 27.704 36.3787 27.5629 36.3248C27.5531 36.3218 27.5452 36.3208 27.5353 36.3169C27.4002 36.262 27.2759 36.1792 27.1634 36.0755C27.1545 36.0675 27.1437 36.0655 27.1358 36.0575L16.7392 25.9665C16.242 25.4847 16.2272 24.6857 16.7037 24.183C17.1832 23.6802 17.9715 23.6643 18.4677 24.1471L28 33.3991L37.5313 24.1471C38.0285 23.6643 38.8178 23.6802 39.2963 24.183C39.7738 24.6857 39.757 25.4847 39.2608 25.9665ZM32.9901 47.3405C32.9901 47.8053 32.6182 48.1814 32.1584 48.1814H23.8426C23.3828 48.1814 23.0099 47.8053 23.0099 47.3405V38.9314C23.0099 38.4675 23.3828 38.0914 23.8426 38.0914H32.1584C32.6182 38.0914 32.9901 38.4675 32.9901 38.9314V47.3405ZM53.6667 0H2.33325C1.04972 0 0 1.06137 0 2.35914V53.6409C0 54.9386 1.04972 56 2.33325 56H53.6667C54.9503 56 56 54.9386 56 53.6409V2.35914C56 1.06137 54.9503 0 53.6667 0Z",
      "clip-rule": "evenodd"
    }))), children);
  }

  return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
    width: size,
    height: size,
    ref: ref,
    xmlns: "http://www.w3.org/2000/svg",
    fill: "currentColor",
    viewBox: "0 0 56 56"
  }, rest), _mask2 || (_mask2 = /*#__PURE__*/React__default['default'].createElement("mask", {
    id: "a",
    width: "56",
    height: "56",
    x: "0",
    y: "0",
    maskUnits: "userSpaceOnUse"
  }, /*#__PURE__*/React__default['default'].createElement("path", {
    "fill-rule": "evenodd",
    d: "M0 0H56V56H0V0Z",
    "clip-rule": "evenodd"
  }))), _g2 || (_g2 = /*#__PURE__*/React__default['default'].createElement("g", {
    mask: "url(#a)"
  }, /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M13.8614 22.1131C13.8614 14.2187 20.1913 7.8176 28 7.8176C35.8087 7.8176 42.1396 14.2187 42.1396 22.1131H13.8614ZM39.2608 25.9665L28.8642 36.0575C28.8563 36.0655 28.8455 36.0675 28.8366 36.0755C28.7241 36.1792 28.5998 36.262 28.4647 36.3169C28.4558 36.3208 28.4469 36.3218 28.4371 36.3248C28.296 36.3787 28.149 36.4086 28 36.4086C27.851 36.4086 27.704 36.3787 27.5629 36.3248C27.5531 36.3218 27.5452 36.3208 27.5353 36.3169C27.4002 36.262 27.2759 36.1792 27.1634 36.0755C27.1545 36.0675 27.1437 36.0655 27.1358 36.0575L16.7392 25.9665C16.242 25.4847 16.2272 24.6857 16.7037 24.183C17.1832 23.6802 17.9715 23.6643 18.4677 24.1471L28 33.3991L37.5313 24.1471C38.0285 23.6643 38.8178 23.6802 39.2963 24.183C39.7738 24.6857 39.757 25.4847 39.2608 25.9665ZM32.9901 47.3405C32.9901 47.8053 32.6182 48.1814 32.1584 48.1814H23.8426C23.3828 48.1814 23.0099 47.8053 23.0099 47.3405V38.9314C23.0099 38.4675 23.3828 38.0914 23.8426 38.0914H32.1584C32.6182 38.0914 32.9901 38.4675 32.9901 38.9314V47.3405ZM53.6667 0H2.33325C1.04972 0 0 1.06137 0 2.35914V53.6409C0 54.9386 1.04972 56 2.33325 56H53.6667C54.9503 56 56 54.9386 56 53.6409V2.35914C56 1.06137 54.9503 0 53.6667 0Z",
    "clip-rule": "evenodd"
  }))), children);
});
ReliefGoodsNegative.propTypes = iconPropTypes.iconPropTypes;

module.exports = ReliefGoodsNegative;
