/**
 *
 * Code generated by @wfp/icon-build-helpers. DO NOT EDIT.
 * @wfp/icon-build-helpers is a fork of @carbon/icon-build-helpers
 */
'use strict';

var iconPropTypes = require('./iconPropTypes-dc77abf6.js');
var React = require('react');
require('@carbon/icon-helpers');
require('prop-types');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var React__default = /*#__PURE__*/_interopDefaultLegacy(React);

var _path, _mask, _g, _path2, _mask2, _g2;

var _excluded = ["children", "size"];
var ResourcingPositive = /*#__PURE__*/React__default['default'].forwardRef(function ResourcingPositive(_ref, ref) {
  var children = _ref.children,
      _ref$size = _ref.size,
      size = _ref$size === void 0 ? 16 : _ref$size,
      rest = iconPropTypes._objectWithoutProperties(_ref, _excluded);

  if (size === "glyph" || size === "glyph" || size === "glyphpx") {
    return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
      width: size,
      height: size,
      ref: ref,
      xmlns: "http://www.w3.org/2000/svg",
      fill: "currentColor",
      viewBox: "0 0 29 39"
    }, rest), _path || (_path = /*#__PURE__*/React__default['default'].createElement("path", {
      d: "M13.6079 9.36901L12.2889 3.41601C12.1259 2.68201 11.4759 2.16101 10.7239 2.16101H6.40094C5.88894 2.16101 5.50794 2.63501 5.61894 3.13501L7.20194 9.36901H13.6079Z",
      "clip-rule": "evenodd"
    })), _mask || (_mask = /*#__PURE__*/React__default['default'].createElement("mask", {
      id: "a",
      style: "mask-type:alpha",
      width: "29",
      height: "39",
      x: "0",
      y: "0",
      maskUnits: "userSpaceOnUse"
    }, /*#__PURE__*/React__default['default'].createElement("path", {
      "fill-rule": "evenodd",
      d: "M0 0.559021H28.8246V39H0V0.559021Z",
      "clip-rule": "evenodd"
    }))), _g || (_g = /*#__PURE__*/React__default['default'].createElement("g", {
      mask: "url(#a)"
    }, /*#__PURE__*/React__default['default'].createElement("path", {
      d: "M18.417 9.36902H21.617L23.206 1.50402C23.294 1.01602 22.918.559021 22.413.559021H20.018C19.142.559021 18.427 1.28802 18.414 2.16102 18.4 1.28802 17.696.559021 16.819.559021H14.417C13.913.559021 13.536 1.01602 13.625 1.50402L15.211 9.36902H18.417zM15.213 30.992V32.193C15.213 32.857 14.677 33.394 14.012 33.394 13.348 33.394 12.811 32.857 12.811 32.193V30.992H12.41C11.745 30.992 11.209 30.455 11.209 29.79 11.209 29.125 11.745 28.589 12.41 28.589H14.772C15.47 28.589 16.015 28.068 16.015 27.412 16.015 26.707 15.47 26.186 14.772 26.186H14.06C12.05 26.186 10.408 24.577 10.408 22.591 10.408 21.029 11.417 19.7 12.811 19.195V17.777C12.811 17.113 13.348 16.576 14.012 16.576 14.677 16.576 15.213 17.113 15.213 17.777V18.979H16.414C17.079 18.979 17.616 19.515 17.616 20.18 17.616 20.845 17.079 21.381 16.414 21.381H14.06C13.371 21.381 12.811 21.926 12.811 22.591 12.811 23.248 13.371 23.784 14.06 23.784H14.772C16.783 23.784 18.417 25.394 18.417 27.364 18.417 29.23 17.015 30.775 15.213 30.992zM27.906 23.375L21.62 10.97H7.20501L.918008 23.375C-.979992 27.804.205008 32.537 3.18401 35.613 5.18601 37.679 7.98101 39 11.209 39H17.616C20.844 39 23.639 37.679 25.64 35.613 28.619 32.537 29.805 27.804 27.906 23.375z",
      "clip-rule": "evenodd"
    }))), children);
  }

  return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
    width: size,
    height: size,
    ref: ref,
    xmlns: "http://www.w3.org/2000/svg",
    fill: "currentColor",
    viewBox: "0 0 29 39"
  }, rest), _path2 || (_path2 = /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M13.6079 9.36901L12.2889 3.41601C12.1259 2.68201 11.4759 2.16101 10.7239 2.16101H6.40094C5.88894 2.16101 5.50794 2.63501 5.61894 3.13501L7.20194 9.36901H13.6079Z",
    "clip-rule": "evenodd"
  })), _mask2 || (_mask2 = /*#__PURE__*/React__default['default'].createElement("mask", {
    id: "a",
    style: "mask-type:alpha",
    width: "29",
    height: "39",
    x: "0",
    y: "0",
    maskUnits: "userSpaceOnUse"
  }, /*#__PURE__*/React__default['default'].createElement("path", {
    "fill-rule": "evenodd",
    d: "M0 0.559021H28.8246V39H0V0.559021Z",
    "clip-rule": "evenodd"
  }))), _g2 || (_g2 = /*#__PURE__*/React__default['default'].createElement("g", {
    mask: "url(#a)"
  }, /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M18.417 9.36902H21.617L23.206 1.50402C23.294 1.01602 22.918.559021 22.413.559021H20.018C19.142.559021 18.427 1.28802 18.414 2.16102 18.4 1.28802 17.696.559021 16.819.559021H14.417C13.913.559021 13.536 1.01602 13.625 1.50402L15.211 9.36902H18.417zM15.213 30.992V32.193C15.213 32.857 14.677 33.394 14.012 33.394 13.348 33.394 12.811 32.857 12.811 32.193V30.992H12.41C11.745 30.992 11.209 30.455 11.209 29.79 11.209 29.125 11.745 28.589 12.41 28.589H14.772C15.47 28.589 16.015 28.068 16.015 27.412 16.015 26.707 15.47 26.186 14.772 26.186H14.06C12.05 26.186 10.408 24.577 10.408 22.591 10.408 21.029 11.417 19.7 12.811 19.195V17.777C12.811 17.113 13.348 16.576 14.012 16.576 14.677 16.576 15.213 17.113 15.213 17.777V18.979H16.414C17.079 18.979 17.616 19.515 17.616 20.18 17.616 20.845 17.079 21.381 16.414 21.381H14.06C13.371 21.381 12.811 21.926 12.811 22.591 12.811 23.248 13.371 23.784 14.06 23.784H14.772C16.783 23.784 18.417 25.394 18.417 27.364 18.417 29.23 17.015 30.775 15.213 30.992zM27.906 23.375L21.62 10.97H7.20501L.918008 23.375C-.979992 27.804.205008 32.537 3.18401 35.613 5.18601 37.679 7.98101 39 11.209 39H17.616C20.844 39 23.639 37.679 25.64 35.613 28.619 32.537 29.805 27.804 27.906 23.375z",
    "clip-rule": "evenodd"
  }))), children);
});
ResourcingPositive.propTypes = iconPropTypes.iconPropTypes;

module.exports = ResourcingPositive;
