/**
 *
 * Code generated by @wfp/icon-build-helpers. DO NOT EDIT.
 * @wfp/icon-build-helpers is a fork of @carbon/icon-build-helpers
 */
'use strict';

var iconPropTypes = require('./iconPropTypes-dc77abf6.js');
var React = require('react');
require('@carbon/icon-helpers');
require('prop-types');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var React__default = /*#__PURE__*/_interopDefaultLegacy(React);

var _mask, _g, _mask2, _g2;

var _excluded = ["children", "size"];
var ResourcingNegative = /*#__PURE__*/React__default['default'].forwardRef(function ResourcingNegative(_ref, ref) {
  var children = _ref.children,
      _ref$size = _ref.size,
      size = _ref$size === void 0 ? 16 : _ref$size,
      rest = iconPropTypes._objectWithoutProperties(_ref, _excluded);

  if (size === "glyph" || size === "glyph" || size === "glyphpx") {
    return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
      width: size,
      height: size,
      ref: ref,
      xmlns: "http://www.w3.org/2000/svg",
      fill: "currentColor",
      viewBox: "0 0 56 56"
    }, rest), _mask || (_mask = /*#__PURE__*/React__default['default'].createElement("mask", {
      id: "a",
      width: "56",
      height: "56",
      x: "0",
      y: "0",
      maskUnits: "userSpaceOnUse"
    }, /*#__PURE__*/React__default['default'].createElement("path", {
      "fill-rule": "evenodd",
      d: "M0 0H56V56H0V0Z",
      "clip-rule": "evenodd"
    }))), _g || (_g = /*#__PURE__*/React__default['default'].createElement("g", {
      mask: "url(#a)"
    }, /*#__PURE__*/React__default['default'].createElement("path", {
      d: "M27.4086 32.3572H26.7091C26.0321 32.3572 25.481 31.8296 25.481 31.1851C25.481 30.5318 26.0321 29.9963 26.7091 29.9963H29.0227C29.6751 29.9963 30.2027 29.4697 30.2027 28.8164C30.2027 28.1631 29.6751 27.6365 29.0227 27.6365H27.8418V26.4556C27.8418 25.8032 27.3142 25.2756 26.6609 25.2756C26.0086 25.2756 25.481 25.8032 25.481 26.4556V27.8487C24.1124 28.3448 23.1211 29.6505 23.1211 31.1851C23.1211 33.1363 24.7333 34.718 26.7091 34.718H27.4086C28.0933 34.718 28.6288 35.2289 28.6288 35.9215C28.6288 36.566 28.0933 37.0779 27.4086 37.0779H25.088C24.4347 37.0779 23.9081 37.6045 23.9081 38.2578C23.9081 38.9111 24.4347 39.4387 25.088 39.4387H25.481V40.6187C25.481 41.271 26.0086 41.7986 26.6609 41.7986C27.3142 41.7986 27.8418 41.271 27.8418 40.6187V39.4387C29.6122 39.2255 30.9896 37.7067 30.9896 35.8744C30.9896 33.9389 29.3843 32.3572 27.4086 32.3572Z",
      "clip-rule": "evenodd"
    }), /*#__PURE__*/React__default['default'].createElement("path", {
      d: "M38.2456 43.7933C36.2705 45.8552 33.513 47.1729 30.3293 47.1729H24.0083C20.8237 47.1729 18.0662 45.8552 16.091 43.7933C13.152 40.7259 11.9829 36.0046 13.8555 31.5866L20.0581 19.2123H34.2796L40.4812 31.5866C42.3537 36.0046 41.1846 40.7259 38.2456 43.7933ZM19.2649 10.4251H23.5298C24.2707 10.4251 24.912 10.9448 25.0738 11.676L26.3751 17.6153H20.0551L18.4934 11.3967C18.3829 10.8979 18.7587 10.4251 19.2649 10.4251ZM27.1733 8.82709H29.543C30.4082 8.82709 31.1028 9.55429 31.1166 10.4251C31.1284 9.55429 31.8338 8.82709 32.6991 8.82709H35.0619C35.5601 8.82709 35.9311 9.28296 35.8443 9.76975L34.2766 17.6153H27.9566L26.3909 9.76975C26.3041 9.28296 26.676 8.82709 27.1733 8.82709ZM53.6667 0H2.33325C1.04972 0 0 1.06137 0 2.35914V53.6409C0 54.9386 1.04972 56 2.33325 56H53.6667C54.9503 56 56 54.9386 56 53.6409V2.35914C56 1.06137 54.9503 0 53.6667 0Z",
      "clip-rule": "evenodd"
    }))), children);
  }

  return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
    width: size,
    height: size,
    ref: ref,
    xmlns: "http://www.w3.org/2000/svg",
    fill: "currentColor",
    viewBox: "0 0 56 56"
  }, rest), _mask2 || (_mask2 = /*#__PURE__*/React__default['default'].createElement("mask", {
    id: "a",
    width: "56",
    height: "56",
    x: "0",
    y: "0",
    maskUnits: "userSpaceOnUse"
  }, /*#__PURE__*/React__default['default'].createElement("path", {
    "fill-rule": "evenodd",
    d: "M0 0H56V56H0V0Z",
    "clip-rule": "evenodd"
  }))), _g2 || (_g2 = /*#__PURE__*/React__default['default'].createElement("g", {
    mask: "url(#a)"
  }, /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M27.4086 32.3572H26.7091C26.0321 32.3572 25.481 31.8296 25.481 31.1851C25.481 30.5318 26.0321 29.9963 26.7091 29.9963H29.0227C29.6751 29.9963 30.2027 29.4697 30.2027 28.8164C30.2027 28.1631 29.6751 27.6365 29.0227 27.6365H27.8418V26.4556C27.8418 25.8032 27.3142 25.2756 26.6609 25.2756C26.0086 25.2756 25.481 25.8032 25.481 26.4556V27.8487C24.1124 28.3448 23.1211 29.6505 23.1211 31.1851C23.1211 33.1363 24.7333 34.718 26.7091 34.718H27.4086C28.0933 34.718 28.6288 35.2289 28.6288 35.9215C28.6288 36.566 28.0933 37.0779 27.4086 37.0779H25.088C24.4347 37.0779 23.9081 37.6045 23.9081 38.2578C23.9081 38.9111 24.4347 39.4387 25.088 39.4387H25.481V40.6187C25.481 41.271 26.0086 41.7986 26.6609 41.7986C27.3142 41.7986 27.8418 41.271 27.8418 40.6187V39.4387C29.6122 39.2255 30.9896 37.7067 30.9896 35.8744C30.9896 33.9389 29.3843 32.3572 27.4086 32.3572Z",
    "clip-rule": "evenodd"
  }), /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M38.2456 43.7933C36.2705 45.8552 33.513 47.1729 30.3293 47.1729H24.0083C20.8237 47.1729 18.0662 45.8552 16.091 43.7933C13.152 40.7259 11.9829 36.0046 13.8555 31.5866L20.0581 19.2123H34.2796L40.4812 31.5866C42.3537 36.0046 41.1846 40.7259 38.2456 43.7933ZM19.2649 10.4251H23.5298C24.2707 10.4251 24.912 10.9448 25.0738 11.676L26.3751 17.6153H20.0551L18.4934 11.3967C18.3829 10.8979 18.7587 10.4251 19.2649 10.4251ZM27.1733 8.82709H29.543C30.4082 8.82709 31.1028 9.55429 31.1166 10.4251C31.1284 9.55429 31.8338 8.82709 32.6991 8.82709H35.0619C35.5601 8.82709 35.9311 9.28296 35.8443 9.76975L34.2766 17.6153H27.9566L26.3909 9.76975C26.3041 9.28296 26.676 8.82709 27.1733 8.82709ZM53.6667 0H2.33325C1.04972 0 0 1.06137 0 2.35914V53.6409C0 54.9386 1.04972 56 2.33325 56H53.6667C54.9503 56 56 54.9386 56 53.6409V2.35914C56 1.06137 54.9503 0 53.6667 0Z",
    "clip-rule": "evenodd"
  }))), children);
});
ResourcingNegative.propTypes = iconPropTypes.iconPropTypes;

module.exports = ResourcingNegative;
