/**
 *
 * Code generated by @wfp/icon-build-helpers. DO NOT EDIT.
 * @wfp/icon-build-helpers is a fork of @carbon/icon-build-helpers
 */
'use strict';

var iconPropTypes = require('./iconPropTypes-dc77abf6.js');
var React = require('react');
require('@carbon/icon-helpers');
require('prop-types');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var React__default = /*#__PURE__*/_interopDefaultLegacy(React);

var _mask, _g, _mask2, _g2;

var _excluded = ["children", "size"];
var SecurityNegative = /*#__PURE__*/React__default['default'].forwardRef(function SecurityNegative(_ref, ref) {
  var children = _ref.children,
      _ref$size = _ref.size,
      size = _ref$size === void 0 ? 16 : _ref$size,
      rest = iconPropTypes._objectWithoutProperties(_ref, _excluded);

  if (size === "glyph" || size === "glyph" || size === "glyphpx") {
    return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
      width: size,
      height: size,
      ref: ref,
      xmlns: "http://www.w3.org/2000/svg",
      fill: "currentColor",
      viewBox: "0 0 56 56"
    }, rest), _mask || (_mask = /*#__PURE__*/React__default['default'].createElement("mask", {
      id: "a",
      width: "56",
      height: "56",
      x: "0",
      y: "0",
      maskUnits: "userSpaceOnUse"
    }, /*#__PURE__*/React__default['default'].createElement("path", {
      "fill-rule": "evenodd",
      d: "M0 0H56V56H0V0Z",
      "clip-rule": "evenodd"
    }))), _g || (_g = /*#__PURE__*/React__default['default'].createElement("g", {
      mask: "url(#a)"
    }, /*#__PURE__*/React__default['default'].createElement("path", {
      d: "M30.743 22.8991C29.8922 22.8991 29.0424 23.2214 28.3901 23.859L27.7131 24.4809L27.0362 23.859C26.3839 23.2214 25.5341 22.8991 24.6842 22.8991C23.8658 22.8991 23.0396 23.1978 22.4098 23.7882C21.0334 25.0713 21.1277 27.3211 22.458 28.6425L23.0091 29.1858L27.4302 33.8044C27.5884 33.9616 27.8399 33.9616 27.9971 33.8044L32.4191 29.1858L32.9693 28.6425C34.2995 27.3211 34.3929 25.0713 33.0164 23.7882C32.3867 23.1978 31.5614 22.8991 30.743 22.8991Z",
      "clip-rule": "evenodd"
    }), /*#__PURE__*/React__default['default'].createElement("path", {
      d: "M40.4713 30.5083C40.4713 38.3847 34.7028 44.7679 27.8293 44.7679C20.9559 44.7679 15.1873 38.3847 15.1873 30.5083V14.3863C15.1873 14.0032 15.4567 13.6761 15.8286 13.6042L27.6794 11.2471C27.7741 11.2231 27.8846 11.2231 27.9793 11.2471L39.831 13.6042C40.203 13.6761 40.4713 14.0032 40.4713 14.3863V30.5083ZM53.6667 0H2.33325C1.04972 0 0 1.06137 0 2.35914V53.6409C0 54.9386 1.04972 56 2.33325 56H53.6667C54.9503 56 56 54.9386 56 53.6409V2.35914C56 1.06137 54.9503 0 53.6667 0Z",
      "clip-rule": "evenodd"
    }))), children);
  }

  return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
    width: size,
    height: size,
    ref: ref,
    xmlns: "http://www.w3.org/2000/svg",
    fill: "currentColor",
    viewBox: "0 0 56 56"
  }, rest), _mask2 || (_mask2 = /*#__PURE__*/React__default['default'].createElement("mask", {
    id: "a",
    width: "56",
    height: "56",
    x: "0",
    y: "0",
    maskUnits: "userSpaceOnUse"
  }, /*#__PURE__*/React__default['default'].createElement("path", {
    "fill-rule": "evenodd",
    d: "M0 0H56V56H0V0Z",
    "clip-rule": "evenodd"
  }))), _g2 || (_g2 = /*#__PURE__*/React__default['default'].createElement("g", {
    mask: "url(#a)"
  }, /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M30.743 22.8991C29.8922 22.8991 29.0424 23.2214 28.3901 23.859L27.7131 24.4809L27.0362 23.859C26.3839 23.2214 25.5341 22.8991 24.6842 22.8991C23.8658 22.8991 23.0396 23.1978 22.4098 23.7882C21.0334 25.0713 21.1277 27.3211 22.458 28.6425L23.0091 29.1858L27.4302 33.8044C27.5884 33.9616 27.8399 33.9616 27.9971 33.8044L32.4191 29.1858L32.9693 28.6425C34.2995 27.3211 34.3929 25.0713 33.0164 23.7882C32.3867 23.1978 31.5614 22.8991 30.743 22.8991Z",
    "clip-rule": "evenodd"
  }), /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M40.4713 30.5083C40.4713 38.3847 34.7028 44.7679 27.8293 44.7679C20.9559 44.7679 15.1873 38.3847 15.1873 30.5083V14.3863C15.1873 14.0032 15.4567 13.6761 15.8286 13.6042L27.6794 11.2471C27.7741 11.2231 27.8846 11.2231 27.9793 11.2471L39.831 13.6042C40.203 13.6761 40.4713 14.0032 40.4713 14.3863V30.5083ZM53.6667 0H2.33325C1.04972 0 0 1.06137 0 2.35914V53.6409C0 54.9386 1.04972 56 2.33325 56H53.6667C54.9503 56 56 54.9386 56 53.6409V2.35914C56 1.06137 54.9503 0 53.6667 0Z",
    "clip-rule": "evenodd"
  }))), children);
});
SecurityNegative.propTypes = iconPropTypes.iconPropTypes;

module.exports = SecurityNegative;
