/**
 *
 * Code generated by @wfp/icon-build-helpers. DO NOT EDIT.
 * @wfp/icon-build-helpers is a fork of @carbon/icon-build-helpers
 */
'use strict';

var iconPropTypes = require('./iconPropTypes-dc77abf6.js');
var React = require('react');
require('@carbon/icon-helpers');
require('prop-types');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var React__default = /*#__PURE__*/_interopDefaultLegacy(React);

var _mask, _g, _mask2, _g2;

var _excluded = ["children", "size"];
var SustainableProcurementPositive = /*#__PURE__*/React__default['default'].forwardRef(function SustainableProcurementPositive(_ref, ref) {
  var children = _ref.children,
      _ref$size = _ref.size,
      size = _ref$size === void 0 ? 16 : _ref$size,
      rest = iconPropTypes._objectWithoutProperties(_ref, _excluded);

  if (size === "glyph" || size === "glyph" || size === "glyphpx") {
    return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
      width: size,
      height: size,
      ref: ref,
      xmlns: "http://www.w3.org/2000/svg",
      fill: "currentColor",
      viewBox: "0 0 35 28"
    }, rest), _mask || (_mask = /*#__PURE__*/React__default['default'].createElement("mask", {
      id: "a",
      width: "35",
      height: "28",
      x: "0",
      y: "0",
      maskUnits: "userSpaceOnUse"
    }, /*#__PURE__*/React__default['default'].createElement("path", {
      "fill-rule": "evenodd",
      d: "M0 0.382996H34.179V28H0V0.382996Z",
      "clip-rule": "evenodd"
    }))), _g || (_g = /*#__PURE__*/React__default['default'].createElement("g", {
      mask: "url(#a)"
    }, /*#__PURE__*/React__default['default'].createElement("path", {
      d: "M34.179 21.591C34.179 25.131 31.31 28 27.771 28H13.758C13.003 28 12.277 27.701 11.743 27.167L0.899032 16.579C-0.155968 15.525 -0.326968 13.816 0.621032 12.669C1.71103 11.345 3.66903 11.281 4.85003 12.456L14.527 21.876C14.791 22.14 15.289 22.304 15.667 22.304H22.075C22.858 22.304 23.499 21.663 23.499 20.879C23.499 20.488 23.342 20.132 23.079 19.875C22.823 19.612 22.466 19.455 22.075 19.455H18.159C16.785 19.455 15.667 18.337 15.667 16.963C15.667 16.279 15.944 15.653 16.4 15.205C16.848 14.749 17.475 14.471 18.159 14.471H27.771C31.31 14.471 34.179 17.34 34.179 20.879V21.591ZM8.54603 0.382996H9.43503C13.859 0.382996 17.446 3.97 17.446 8.394V12.132H16.555C12.131 12.132 8.54603 8.546 8.54603 4.122V0.382996ZM18.514 5.983C18.514 2.891 21.021 0.382996 24.114 0.382996H25.634V3.684C25.634 6.777 23.127 9.284 20.035 9.284H18.514V5.983Z",
      "clip-rule": "evenodd"
    }))), children);
  }

  return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
    width: size,
    height: size,
    ref: ref,
    xmlns: "http://www.w3.org/2000/svg",
    fill: "currentColor",
    viewBox: "0 0 35 28"
  }, rest), _mask2 || (_mask2 = /*#__PURE__*/React__default['default'].createElement("mask", {
    id: "a",
    width: "35",
    height: "28",
    x: "0",
    y: "0",
    maskUnits: "userSpaceOnUse"
  }, /*#__PURE__*/React__default['default'].createElement("path", {
    "fill-rule": "evenodd",
    d: "M0 0.382996H34.179V28H0V0.382996Z",
    "clip-rule": "evenodd"
  }))), _g2 || (_g2 = /*#__PURE__*/React__default['default'].createElement("g", {
    mask: "url(#a)"
  }, /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M34.179 21.591C34.179 25.131 31.31 28 27.771 28H13.758C13.003 28 12.277 27.701 11.743 27.167L0.899032 16.579C-0.155968 15.525 -0.326968 13.816 0.621032 12.669C1.71103 11.345 3.66903 11.281 4.85003 12.456L14.527 21.876C14.791 22.14 15.289 22.304 15.667 22.304H22.075C22.858 22.304 23.499 21.663 23.499 20.879C23.499 20.488 23.342 20.132 23.079 19.875C22.823 19.612 22.466 19.455 22.075 19.455H18.159C16.785 19.455 15.667 18.337 15.667 16.963C15.667 16.279 15.944 15.653 16.4 15.205C16.848 14.749 17.475 14.471 18.159 14.471H27.771C31.31 14.471 34.179 17.34 34.179 20.879V21.591ZM8.54603 0.382996H9.43503C13.859 0.382996 17.446 3.97 17.446 8.394V12.132H16.555C12.131 12.132 8.54603 8.546 8.54603 4.122V0.382996ZM18.514 5.983C18.514 2.891 21.021 0.382996 24.114 0.382996H25.634V3.684C25.634 6.777 23.127 9.284 20.035 9.284H18.514V5.983Z",
    "clip-rule": "evenodd"
  }))), children);
});
SustainableProcurementPositive.propTypes = iconPropTypes.iconPropTypes;

module.exports = SustainableProcurementPositive;
