/**
 *
 * Code generated by @wfp/icon-build-helpers. DO NOT EDIT.
 * @wfp/icon-build-helpers is a fork of @carbon/icon-build-helpers
 */
'use strict';

var iconPropTypes = require('./iconPropTypes-dc77abf6.js');
var React = require('react');
require('@carbon/icon-helpers');
require('prop-types');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var React__default = /*#__PURE__*/_interopDefaultLegacy(React);

var _mask, _g, _mask2, _g2;

var _excluded = ["children", "size"];
var SustaninableProcurementNegative = /*#__PURE__*/React__default['default'].forwardRef(function SustaninableProcurementNegative(_ref, ref) {
  var children = _ref.children,
      _ref$size = _ref.size,
      size = _ref$size === void 0 ? 16 : _ref$size,
      rest = iconPropTypes._objectWithoutProperties(_ref, _excluded);

  if (size === "glyph" || size === "glyph" || size === "glyphpx") {
    return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
      width: size,
      height: size,
      ref: ref,
      xmlns: "http://www.w3.org/2000/svg",
      fill: "currentColor",
      viewBox: "0 0 56 56"
    }, rest), _mask || (_mask = /*#__PURE__*/React__default['default'].createElement("mask", {
      id: "a",
      style: "mask-type:alpha",
      width: "56",
      height: "56",
      x: "0",
      y: "0",
      maskUnits: "userSpaceOnUse"
    }, /*#__PURE__*/React__default['default'].createElement("path", {
      "fill-rule": "evenodd",
      d: "M0 0H56V56H0V0Z",
      "clip-rule": "evenodd"
    }))), _g || (_g = /*#__PURE__*/React__default['default'].createElement("g", {
      mask: "url(#a)"
    }, /*#__PURE__*/React__default['default'].createElement("path", {
      d: "M43.8947 33.2634C43.8947 36.7937 41.0642 39.6556 37.5718 39.6556H23.7479C23.003 39.6556 22.2858 39.3573 21.7589 38.8246L11.0605 28.2628C10.0206 27.2115 9.85194 25.5067 10.7862 24.3635C11.8616 23.0428 13.7933 22.979 14.9594 24.1501L24.5056 33.5467C24.766 33.8101 25.2573 33.9737 25.6302 33.9737H31.9522C32.7247 33.9737 33.3571 33.3343 33.3571 32.5532C33.3571 32.1622 33.2032 31.8071 32.9427 31.5517C32.6902 31.2893 32.339 31.1317 31.9522 31.1317H28.0888C26.7332 31.1317 25.6302 30.0175 25.6302 28.6459C25.6302 27.9646 25.9035 27.3391 26.3534 26.8923C26.7964 26.4374 27.415 26.1601 28.0888 26.1601H37.5718C41.0642 26.1601 43.8947 29.022 43.8947 32.5532V33.2634ZM18.6048 12.1079H19.4829C23.8465 12.1079 27.3854 15.6851 27.3854 20.0981V23.8269H26.5073C22.1427 23.8269 18.6048 20.2497 18.6048 15.8367V12.1079ZM28.44 17.6941C28.44 14.6087 30.9124 12.1079 33.9638 12.1079H35.4644V15.3998C35.4644 18.4851 32.9911 20.9859 29.9396 20.9859H28.44V17.6941ZM53.6667 0H2.33325C1.04972 0 0 1.06137 0 2.35914V53.6409C0 54.9386 1.04972 56 2.33325 56H53.6667C54.9503 56 56 54.9386 56 53.6409V2.35914C56 1.06137 54.9503 0 53.6667 0Z",
      "clip-rule": "evenodd"
    }))), children);
  }

  return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
    width: size,
    height: size,
    ref: ref,
    xmlns: "http://www.w3.org/2000/svg",
    fill: "currentColor",
    viewBox: "0 0 56 56"
  }, rest), _mask2 || (_mask2 = /*#__PURE__*/React__default['default'].createElement("mask", {
    id: "a",
    style: "mask-type:alpha",
    width: "56",
    height: "56",
    x: "0",
    y: "0",
    maskUnits: "userSpaceOnUse"
  }, /*#__PURE__*/React__default['default'].createElement("path", {
    "fill-rule": "evenodd",
    d: "M0 0H56V56H0V0Z",
    "clip-rule": "evenodd"
  }))), _g2 || (_g2 = /*#__PURE__*/React__default['default'].createElement("g", {
    mask: "url(#a)"
  }, /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M43.8947 33.2634C43.8947 36.7937 41.0642 39.6556 37.5718 39.6556H23.7479C23.003 39.6556 22.2858 39.3573 21.7589 38.8246L11.0605 28.2628C10.0206 27.2115 9.85194 25.5067 10.7862 24.3635C11.8616 23.0428 13.7933 22.979 14.9594 24.1501L24.5056 33.5467C24.766 33.8101 25.2573 33.9737 25.6302 33.9737H31.9522C32.7247 33.9737 33.3571 33.3343 33.3571 32.5532C33.3571 32.1622 33.2032 31.8071 32.9427 31.5517C32.6902 31.2893 32.339 31.1317 31.9522 31.1317H28.0888C26.7332 31.1317 25.6302 30.0175 25.6302 28.6459C25.6302 27.9646 25.9035 27.3391 26.3534 26.8923C26.7964 26.4374 27.415 26.1601 28.0888 26.1601H37.5718C41.0642 26.1601 43.8947 29.022 43.8947 32.5532V33.2634ZM18.6048 12.1079H19.4829C23.8465 12.1079 27.3854 15.6851 27.3854 20.0981V23.8269H26.5073C22.1427 23.8269 18.6048 20.2497 18.6048 15.8367V12.1079ZM28.44 17.6941C28.44 14.6087 30.9124 12.1079 33.9638 12.1079H35.4644V15.3998C35.4644 18.4851 32.9911 20.9859 29.9396 20.9859H28.44V17.6941ZM53.6667 0H2.33325C1.04972 0 0 1.06137 0 2.35914V53.6409C0 54.9386 1.04972 56 2.33325 56H53.6667C54.9503 56 56 54.9386 56 53.6409V2.35914C56 1.06137 54.9503 0 53.6667 0Z",
    "clip-rule": "evenodd"
  }))), children);
});
SustaninableProcurementNegative.propTypes = iconPropTypes.iconPropTypes;

module.exports = SustaninableProcurementNegative;
