/**
 *
 * Code generated by @wfp/icon-build-helpers. DO NOT EDIT.
 * @wfp/icon-build-helpers is a fork of @carbon/icon-build-helpers
 */
'use strict';

var iconPropTypes = require('./iconPropTypes-dc77abf6.js');
var React = require('react');
require('@carbon/icon-helpers');
require('prop-types');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var React__default = /*#__PURE__*/_interopDefaultLegacy(React);

var _mask, _g, _mask2, _g2;

var _excluded = ["children", "size"];
var VoucherPositive = /*#__PURE__*/React__default['default'].forwardRef(function VoucherPositive(_ref, ref) {
  var children = _ref.children,
      _ref$size = _ref.size,
      size = _ref$size === void 0 ? 16 : _ref$size,
      rest = iconPropTypes._objectWithoutProperties(_ref, _excluded);

  if (size === "glyph" || size === "glyph" || size === "glyphpx") {
    return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
      width: size,
      height: size,
      ref: ref,
      xmlns: "http://www.w3.org/2000/svg",
      fill: "currentColor",
      viewBox: "0 0 44 22"
    }, rest), _mask || (_mask = /*#__PURE__*/React__default['default'].createElement("mask", {
      id: "a",
      style: "mask-type:alpha",
      width: "44",
      height: "22",
      x: "0",
      y: "0",
      maskUnits: "userSpaceOnUse"
    }, /*#__PURE__*/React__default['default'].createElement("path", {
      "fill-rule": "evenodd",
      d: "M0.0599976 0.039978H43.988V22H0.0599976V0.039978Z",
      "clip-rule": "evenodd"
    }))), _g || (_g = /*#__PURE__*/React__default['default'].createElement("g", {
      mask: "url(#a)"
    }, /*#__PURE__*/React__default['default'].createElement("path", {
      d: "M32.991 5.72398H21.114C20.629 5.72398 20.234 5.32998 20.234 4.84498C20.234 4.35898 20.629 3.96498 21.114 3.96498H32.991C33.478 3.96498 33.871 4.35898 33.871 4.84498C33.871 5.32998 33.478 5.72398 32.991 5.72398ZM32.991 11.883H21.114C20.629 11.883 20.234 11.489 20.234 11.003C20.234 10.517 20.629 10.123 21.114 10.123H32.991C33.478 10.123 33.871 10.517 33.871 11.003C33.871 11.489 33.478 11.883 32.991 11.883ZM32.991 17.601H21.114C20.629 17.601 20.234 17.207 20.234 16.721C20.234 16.236 20.629 15.842 21.114 15.842H32.991C33.478 15.842 33.871 16.236 33.871 16.721C33.871 17.207 33.478 17.601 32.991 17.601ZM14.076 12.763C14.076 13.248 13.683 13.642 13.196 13.642C12.711 13.642 12.316 13.248 12.316 12.763V8.80398C12.316 8.31798 12.711 7.92398 13.196 7.92398C13.683 7.92398 14.076 8.31798 14.076 8.80398V12.763ZM43.988 6.24398V1.10498C43.988 0.498981 43.495 0.00598145 42.889 0.00598145H14.082L14.11 3.95898C14.113 4.44498 13.723 4.84098 13.236 4.84498C13.234 4.84498 13.232 4.84498 13.23 4.84498C12.747 4.84498 12.354 4.45498 12.35 3.97098L12.323 0.00598145H1.1C0.493 0.00598145 0 0.498981 0 1.10498V6.24398C2.26 6.65798 3.978 8.63398 3.978 11.003C3.978 13.372 2.26 15.348 0 15.762V20.9C0 21.507 0.493 22 1.1 22H12.316V17.601C12.316 17.115 12.711 16.721 13.196 16.721C13.683 16.721 14.076 17.115 14.076 17.601V22H42.889C43.495 22 43.988 21.507 43.988 20.9V15.762C41.729 15.348 40.01 13.372 40.01 11.003C40.01 8.63398 41.729 6.65798 43.988 6.24398Z",
      "clip-rule": "evenodd"
    }))), children);
  }

  return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
    width: size,
    height: size,
    ref: ref,
    xmlns: "http://www.w3.org/2000/svg",
    fill: "currentColor",
    viewBox: "0 0 44 22"
  }, rest), _mask2 || (_mask2 = /*#__PURE__*/React__default['default'].createElement("mask", {
    id: "a",
    style: "mask-type:alpha",
    width: "44",
    height: "22",
    x: "0",
    y: "0",
    maskUnits: "userSpaceOnUse"
  }, /*#__PURE__*/React__default['default'].createElement("path", {
    "fill-rule": "evenodd",
    d: "M0.0599976 0.039978H43.988V22H0.0599976V0.039978Z",
    "clip-rule": "evenodd"
  }))), _g2 || (_g2 = /*#__PURE__*/React__default['default'].createElement("g", {
    mask: "url(#a)"
  }, /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M32.991 5.72398H21.114C20.629 5.72398 20.234 5.32998 20.234 4.84498C20.234 4.35898 20.629 3.96498 21.114 3.96498H32.991C33.478 3.96498 33.871 4.35898 33.871 4.84498C33.871 5.32998 33.478 5.72398 32.991 5.72398ZM32.991 11.883H21.114C20.629 11.883 20.234 11.489 20.234 11.003C20.234 10.517 20.629 10.123 21.114 10.123H32.991C33.478 10.123 33.871 10.517 33.871 11.003C33.871 11.489 33.478 11.883 32.991 11.883ZM32.991 17.601H21.114C20.629 17.601 20.234 17.207 20.234 16.721C20.234 16.236 20.629 15.842 21.114 15.842H32.991C33.478 15.842 33.871 16.236 33.871 16.721C33.871 17.207 33.478 17.601 32.991 17.601ZM14.076 12.763C14.076 13.248 13.683 13.642 13.196 13.642C12.711 13.642 12.316 13.248 12.316 12.763V8.80398C12.316 8.31798 12.711 7.92398 13.196 7.92398C13.683 7.92398 14.076 8.31798 14.076 8.80398V12.763ZM43.988 6.24398V1.10498C43.988 0.498981 43.495 0.00598145 42.889 0.00598145H14.082L14.11 3.95898C14.113 4.44498 13.723 4.84098 13.236 4.84498C13.234 4.84498 13.232 4.84498 13.23 4.84498C12.747 4.84498 12.354 4.45498 12.35 3.97098L12.323 0.00598145H1.1C0.493 0.00598145 0 0.498981 0 1.10498V6.24398C2.26 6.65798 3.978 8.63398 3.978 11.003C3.978 13.372 2.26 15.348 0 15.762V20.9C0 21.507 0.493 22 1.1 22H12.316V17.601C12.316 17.115 12.711 16.721 13.196 16.721C13.683 16.721 14.076 17.115 14.076 17.601V22H42.889C43.495 22 43.988 21.507 43.988 20.9V15.762C41.729 15.348 40.01 13.372 40.01 11.003C40.01 8.63398 41.729 6.65798 43.988 6.24398Z",
    "clip-rule": "evenodd"
  }))), children);
});
VoucherPositive.propTypes = iconPropTypes.iconPropTypes;

module.exports = VoucherPositive;
