/**
 *
 * Code generated by @wfp/icon-build-helpers. DO NOT EDIT.
 * @wfp/icon-build-helpers is a fork of @carbon/icon-build-helpers
 */
'use strict';

var iconPropTypes = require('./iconPropTypes-dc77abf6.js');
var React = require('react');
require('@carbon/icon-helpers');
require('prop-types');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var React__default = /*#__PURE__*/_interopDefaultLegacy(React);

var _mask, _g, _path, _mask2, _g2, _path2;

var _excluded = ["children", "size"];
var WarehousePositive = /*#__PURE__*/React__default['default'].forwardRef(function WarehousePositive(_ref, ref) {
  var children = _ref.children,
      _ref$size = _ref.size,
      size = _ref$size === void 0 ? 16 : _ref$size,
      rest = iconPropTypes._objectWithoutProperties(_ref, _excluded);

  if (size === "glyph" || size === "glyph" || size === "glyphpx") {
    return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
      width: size,
      height: size,
      ref: ref,
      xmlns: "http://www.w3.org/2000/svg",
      fill: "currentColor",
      viewBox: "0 0 34 35"
    }, rest), _mask || (_mask = /*#__PURE__*/React__default['default'].createElement("mask", {
      id: "a",
      style: "mask-type:alpha",
      width: "34",
      height: "35",
      x: "0",
      y: "0",
      maskUnits: "userSpaceOnUse"
    }, /*#__PURE__*/React__default['default'].createElement("path", {
      "fill-rule": "evenodd",
      d: "M0.0600586 0.717529H33.1571V34.94H0.0600586V0.717529Z",
      "clip-rule": "evenodd"
    }))), _g || (_g = /*#__PURE__*/React__default['default'].createElement("g", {
      mask: "url(#a)"
    }, /*#__PURE__*/React__default['default'].createElement("path", {
      d: "M30.347 32.19H2.81V10.736L16.578 3.62603L30.347 10.739V32.19ZM32.419 8.70003L17.9 1.14503C17.118 0.575029 16.047 0.575029 15.254 1.14503L1.035 8.49203L0.736 8.70003C0.269 9.12303 0 9.72903 0 10.363V35H33.158V10.363C33.158 9.73203 32.888 9.12603 32.419 8.70003Z",
      "clip-rule": "evenodd"
    }))), _path || (_path = /*#__PURE__*/React__default['default'].createElement("path", {
      d: "M5.40295 12.199V28.649C5.40295 29.161 5.82195 29.58 6.33395 29.58H26.824C27.335 29.58 27.755 29.161 27.755 28.649V12.199C27.755 11.687 27.335 11.268 26.824 11.268H6.33395C5.82195 11.268 5.40295 11.687 5.40295 12.199Z",
      "clip-rule": "evenodd"
    })), children);
  }

  return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
    width: size,
    height: size,
    ref: ref,
    xmlns: "http://www.w3.org/2000/svg",
    fill: "currentColor",
    viewBox: "0 0 34 35"
  }, rest), _mask2 || (_mask2 = /*#__PURE__*/React__default['default'].createElement("mask", {
    id: "a",
    style: "mask-type:alpha",
    width: "34",
    height: "35",
    x: "0",
    y: "0",
    maskUnits: "userSpaceOnUse"
  }, /*#__PURE__*/React__default['default'].createElement("path", {
    "fill-rule": "evenodd",
    d: "M0.0600586 0.717529H33.1571V34.94H0.0600586V0.717529Z",
    "clip-rule": "evenodd"
  }))), _g2 || (_g2 = /*#__PURE__*/React__default['default'].createElement("g", {
    mask: "url(#a)"
  }, /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M30.347 32.19H2.81V10.736L16.578 3.62603L30.347 10.739V32.19ZM32.419 8.70003L17.9 1.14503C17.118 0.575029 16.047 0.575029 15.254 1.14503L1.035 8.49203L0.736 8.70003C0.269 9.12303 0 9.72903 0 10.363V35H33.158V10.363C33.158 9.73203 32.888 9.12603 32.419 8.70003Z",
    "clip-rule": "evenodd"
  }))), _path2 || (_path2 = /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M5.40295 12.199V28.649C5.40295 29.161 5.82195 29.58 6.33395 29.58H26.824C27.335 29.58 27.755 29.161 27.755 28.649V12.199C27.755 11.687 27.335 11.268 26.824 11.268H6.33395C5.82195 11.268 5.40295 11.687 5.40295 12.199Z",
    "clip-rule": "evenodd"
  })), children);
});
WarehousePositive.propTypes = iconPropTypes.iconPropTypes;

module.exports = WarehousePositive;
