/**
 *
 * Code generated by @wfp/icon-build-helpers. DO NOT EDIT.
 * @wfp/icon-build-helpers is a fork of @carbon/icon-build-helpers
 */
'use strict';

var iconPropTypes = require('./iconPropTypes-dc77abf6.js');
var React = require('react');
require('@carbon/icon-helpers');
require('prop-types');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var React__default = /*#__PURE__*/_interopDefaultLegacy(React);

var _path, _mask, _g, _path2, _mask2, _g2;

var _excluded = ["children", "size"];
var WastePositive = /*#__PURE__*/React__default['default'].forwardRef(function WastePositive(_ref, ref) {
  var children = _ref.children,
      _ref$size = _ref.size,
      size = _ref$size === void 0 ? 16 : _ref$size,
      rest = iconPropTypes._objectWithoutProperties(_ref, _excluded);

  if (size === "glyph" || size === "glyph" || size === "glyphpx") {
    return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
      width: size,
      height: size,
      ref: ref,
      xmlns: "http://www.w3.org/2000/svg",
      fill: "currentColor",
      viewBox: "0 0 27 41"
    }, rest), _path || (_path = /*#__PURE__*/React__default['default'].createElement("path", {
      d: "M23.012 5.10001L20.083 8.02801C19.912 8.20001 19.912 8.47901 20.083 8.65101L21.405 9.97301C21.577 10.145 21.855 10.145 22.027 9.97301L23.66 8.34001L24.957 7.04401C25.128 6.87201 25.128 6.59301 24.957 6.42201L23.634 5.10001C23.462 4.92801 23.184 4.92801 23.012 5.10001Z",
      "clip-rule": "evenodd"
    })), _mask || (_mask = /*#__PURE__*/React__default['default'].createElement("mask", {
      id: "a",
      width: "27",
      height: "41",
      x: "0",
      y: "0",
      maskUnits: "userSpaceOnUse"
    }, /*#__PURE__*/React__default['default'].createElement("path", {
      "fill-rule": "evenodd",
      d: "M0.0600586 0.0380249H26.2881V40.94H0.0600586V0.0380249Z",
      "clip-rule": "evenodd"
    }))), _g || (_g = /*#__PURE__*/React__default['default'].createElement("g", {
      mask: "url(#a)"
    }, /*#__PURE__*/React__default['default'].createElement("path", {
      d: "M16.2101 7.55502C16.1151 7.40902 15.9191 7.36902 15.7741 7.46402L14.6531 8.19602C14.5071 8.29202 14.4661 8.48702 14.5621 8.63302L15.4661 10.017H15.4671L16.1851 11.116C16.2811 11.262 16.4761 11.302 16.6221 11.207L17.7421 10.475C17.8881 10.379 17.9281 10.184 17.8331 10.038L16.2101 7.55502Z",
      "clip-rule": "evenodd"
    }), /*#__PURE__*/React__default['default'].createElement("path", {
      d: "M20.669 36.394C20.669 36.816 20.324 37.161 19.902 37.161C19.48 37.161 19.134 36.816 19.134 36.394L20.146 16.432C20.146 16.01 20.492 15.665 20.913 15.665C21.336 15.665 21.681 16.01 21.681 16.432L20.669 36.394ZM15.54 36.394C15.54 36.816 15.194 37.161 14.772 37.161C14.35 37.161 14.004 36.816 14.004 36.394V16.432C14.004 16.01 14.35 15.665 14.772 15.665C15.194 15.665 15.54 16.01 15.54 16.432V36.394ZM9.64103 37.161C9.21803 37.161 8.87303 36.816 8.87303 36.394L7.86203 16.432C7.86203 16.01 8.20703 15.665 8.63003 15.665C9.05203 15.665 9.39803 16.01 9.39803 16.432L10.409 36.394C10.409 36.816 10.063 37.161 9.64103 37.161ZM25.52 11.826H4.21903L23.025 2.96298C23.791 2.60098 24.121 1.68698 23.759 0.918984C23.398 0.151984 22.483 -0.177016 21.715 0.184984L14.771 3.45798L14.444 2.76298C13.901 1.61198 12.529 1.11898 11.378 1.66198L8.60003 2.97098C7.45003 3.51298 6.95603 4.88598 7.49803 6.03598L7.82603 6.73098L0.881032 10.004C0.115032 10.365 -0.213968 11.28 0.147032 12.048C0.508032 12.815 1.42303 13.143 2.19103 12.782L3.41803 12.203C3.34103 12.323 3.25503 12.442 3.25503 12.594L6.06703 40.233C6.06703 40.654 6.41203 41 6.83403 41H22.709C23.131 41 23.477 40.654 23.477 40.233L26.288 12.594C26.288 12.171 25.943 11.826 25.52 11.826Z",
      "clip-rule": "evenodd"
    }))), children);
  }

  return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
    width: size,
    height: size,
    ref: ref,
    xmlns: "http://www.w3.org/2000/svg",
    fill: "currentColor",
    viewBox: "0 0 27 41"
  }, rest), _path2 || (_path2 = /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M23.012 5.10001L20.083 8.02801C19.912 8.20001 19.912 8.47901 20.083 8.65101L21.405 9.97301C21.577 10.145 21.855 10.145 22.027 9.97301L23.66 8.34001L24.957 7.04401C25.128 6.87201 25.128 6.59301 24.957 6.42201L23.634 5.10001C23.462 4.92801 23.184 4.92801 23.012 5.10001Z",
    "clip-rule": "evenodd"
  })), _mask2 || (_mask2 = /*#__PURE__*/React__default['default'].createElement("mask", {
    id: "a",
    width: "27",
    height: "41",
    x: "0",
    y: "0",
    maskUnits: "userSpaceOnUse"
  }, /*#__PURE__*/React__default['default'].createElement("path", {
    "fill-rule": "evenodd",
    d: "M0.0600586 0.0380249H26.2881V40.94H0.0600586V0.0380249Z",
    "clip-rule": "evenodd"
  }))), _g2 || (_g2 = /*#__PURE__*/React__default['default'].createElement("g", {
    mask: "url(#a)"
  }, /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M16.2101 7.55502C16.1151 7.40902 15.9191 7.36902 15.7741 7.46402L14.6531 8.19602C14.5071 8.29202 14.4661 8.48702 14.5621 8.63302L15.4661 10.017H15.4671L16.1851 11.116C16.2811 11.262 16.4761 11.302 16.6221 11.207L17.7421 10.475C17.8881 10.379 17.9281 10.184 17.8331 10.038L16.2101 7.55502Z",
    "clip-rule": "evenodd"
  }), /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M20.669 36.394C20.669 36.816 20.324 37.161 19.902 37.161C19.48 37.161 19.134 36.816 19.134 36.394L20.146 16.432C20.146 16.01 20.492 15.665 20.913 15.665C21.336 15.665 21.681 16.01 21.681 16.432L20.669 36.394ZM15.54 36.394C15.54 36.816 15.194 37.161 14.772 37.161C14.35 37.161 14.004 36.816 14.004 36.394V16.432C14.004 16.01 14.35 15.665 14.772 15.665C15.194 15.665 15.54 16.01 15.54 16.432V36.394ZM9.64103 37.161C9.21803 37.161 8.87303 36.816 8.87303 36.394L7.86203 16.432C7.86203 16.01 8.20703 15.665 8.63003 15.665C9.05203 15.665 9.39803 16.01 9.39803 16.432L10.409 36.394C10.409 36.816 10.063 37.161 9.64103 37.161ZM25.52 11.826H4.21903L23.025 2.96298C23.791 2.60098 24.121 1.68698 23.759 0.918984C23.398 0.151984 22.483 -0.177016 21.715 0.184984L14.771 3.45798L14.444 2.76298C13.901 1.61198 12.529 1.11898 11.378 1.66198L8.60003 2.97098C7.45003 3.51298 6.95603 4.88598 7.49803 6.03598L7.82603 6.73098L0.881032 10.004C0.115032 10.365 -0.213968 11.28 0.147032 12.048C0.508032 12.815 1.42303 13.143 2.19103 12.782L3.41803 12.203C3.34103 12.323 3.25503 12.442 3.25503 12.594L6.06703 40.233C6.06703 40.654 6.41203 41 6.83403 41H22.709C23.131 41 23.477 40.654 23.477 40.233L26.288 12.594C26.288 12.171 25.943 11.826 25.52 11.826Z",
    "clip-rule": "evenodd"
  }))), children);
});
WastePositive.propTypes = iconPropTypes.iconPropTypes;

module.exports = WastePositive;
