/**
 *
 * Code generated by @wfp/icon-build-helpers. DO NOT EDIT.
 * @wfp/icon-build-helpers is a fork of @carbon/icon-build-helpers
 */
'use strict';

var iconPropTypes = require('./iconPropTypes-dc77abf6.js');
var React = require('react');
require('@carbon/icon-helpers');
require('prop-types');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var React__default = /*#__PURE__*/_interopDefaultLegacy(React);

var _mask, _g, _path, _mask2, _g2, _path2;

var _excluded = ["children", "size"];
var WaterNegative = /*#__PURE__*/React__default['default'].forwardRef(function WaterNegative(_ref, ref) {
  var children = _ref.children,
      _ref$size = _ref.size,
      size = _ref$size === void 0 ? 16 : _ref$size,
      rest = iconPropTypes._objectWithoutProperties(_ref, _excluded);

  if (size === "glyph" || size === "glyph" || size === "glyphpx") {
    return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
      width: size,
      height: size,
      ref: ref,
      xmlns: "http://www.w3.org/2000/svg",
      fill: "currentColor",
      viewBox: "0 0 56 56"
    }, rest), _mask || (_mask = /*#__PURE__*/React__default['default'].createElement("mask", {
      id: "a",
      style: "mask-type:alpha",
      width: "56",
      height: "56",
      x: "0",
      y: "0",
      maskUnits: "userSpaceOnUse"
    }, /*#__PURE__*/React__default['default'].createElement("path", {
      "fill-rule": "evenodd",
      d: "M0 0H56V56H0V0Z",
      "clip-rule": "evenodd"
    }))), _g || (_g = /*#__PURE__*/React__default['default'].createElement("g", {
      mask: "url(#a)"
    }, /*#__PURE__*/React__default['default'].createElement("path", {
      d: "M27.9467 46.9116C20.651 46.9116 14.7385 40.7917 14.7385 33.2505C14.7385 26.4254 25.5612 12.0421 27.6123 9.37174C27.783 9.15129 28.1095 9.15129 28.2802 9.37174C30.3313 12.0421 41.153 26.4254 41.153 33.2505C41.153 40.7917 35.2405 46.9116 27.9467 46.9116ZM53.6667 0H2.33325C1.04972 0 0 1.06137 0 2.35914V53.6409C0 54.9386 1.04972 56 2.33325 56H53.6667C54.9503 56 56 54.9386 56 53.6409V2.35914C56 1.06137 54.9503 0 53.6667 0Z",
      "clip-rule": "evenodd"
    }))), _path || (_path = /*#__PURE__*/React__default['default'].createElement("path", {
      d: "M31.3109 41.6326C34.5127 41.6326 37.1132 38.6852 37.1132 35.057C37.1132 34.4145 36.5955 33.8967 35.952 33.8967C35.3104 33.8967 34.7927 34.4145 34.7927 35.057C34.7927 37.4011 33.2296 39.312 31.3109 39.312C30.6683 39.312 30.1506 39.8308 30.1506 40.4723C30.1506 41.1148 30.6683 41.6326 31.3109 41.6326Z",
      "clip-rule": "evenodd"
    })), children);
  }

  return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
    width: size,
    height: size,
    ref: ref,
    xmlns: "http://www.w3.org/2000/svg",
    fill: "currentColor",
    viewBox: "0 0 56 56"
  }, rest), _mask2 || (_mask2 = /*#__PURE__*/React__default['default'].createElement("mask", {
    id: "a",
    style: "mask-type:alpha",
    width: "56",
    height: "56",
    x: "0",
    y: "0",
    maskUnits: "userSpaceOnUse"
  }, /*#__PURE__*/React__default['default'].createElement("path", {
    "fill-rule": "evenodd",
    d: "M0 0H56V56H0V0Z",
    "clip-rule": "evenodd"
  }))), _g2 || (_g2 = /*#__PURE__*/React__default['default'].createElement("g", {
    mask: "url(#a)"
  }, /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M27.9467 46.9116C20.651 46.9116 14.7385 40.7917 14.7385 33.2505C14.7385 26.4254 25.5612 12.0421 27.6123 9.37174C27.783 9.15129 28.1095 9.15129 28.2802 9.37174C30.3313 12.0421 41.153 26.4254 41.153 33.2505C41.153 40.7917 35.2405 46.9116 27.9467 46.9116ZM53.6667 0H2.33325C1.04972 0 0 1.06137 0 2.35914V53.6409C0 54.9386 1.04972 56 2.33325 56H53.6667C54.9503 56 56 54.9386 56 53.6409V2.35914C56 1.06137 54.9503 0 53.6667 0Z",
    "clip-rule": "evenodd"
  }))), _path2 || (_path2 = /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M31.3109 41.6326C34.5127 41.6326 37.1132 38.6852 37.1132 35.057C37.1132 34.4145 36.5955 33.8967 35.952 33.8967C35.3104 33.8967 34.7927 34.4145 34.7927 35.057C34.7927 37.4011 33.2296 39.312 31.3109 39.312C30.6683 39.312 30.1506 39.8308 30.1506 40.4723C30.1506 41.1148 30.6683 41.6326 31.3109 41.6326Z",
    "clip-rule": "evenodd"
  })), children);
});
WaterNegative.propTypes = iconPropTypes.iconPropTypes;

module.exports = WaterNegative;
