/**
 *
 * Code generated by @wfp/icon-build-helpers. DO NOT EDIT.
 * @wfp/icon-build-helpers is a fork of @carbon/icon-build-helpers
 */
'use strict';

var iconPropTypes = require('./iconPropTypes-dc77abf6.js');
var React = require('react');
require('@carbon/icon-helpers');
require('prop-types');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var React__default = /*#__PURE__*/_interopDefaultLegacy(React);

var _mask, _g, _mask2, _g2;

var _excluded = ["children", "size"];
var WaterPositive = /*#__PURE__*/React__default['default'].forwardRef(function WaterPositive(_ref, ref) {
  var children = _ref.children,
      _ref$size = _ref.size,
      size = _ref$size === void 0 ? 16 : _ref$size,
      rest = iconPropTypes._objectWithoutProperties(_ref, _excluded);

  if (size === "glyph" || size === "glyph" || size === "glyphpx") {
    return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
      width: size,
      height: size,
      ref: ref,
      xmlns: "http://www.w3.org/2000/svg",
      fill: "currentColor",
      viewBox: "0 0 27 38"
    }, rest), _mask || (_mask = /*#__PURE__*/React__default['default'].createElement("mask", {
      id: "a",
      style: "mask-type:alpha",
      width: "27",
      height: "38",
      x: "0",
      y: "0",
      maskUnits: "userSpaceOnUse"
    }, /*#__PURE__*/React__default['default'].createElement("path", {
      "fill-rule": "evenodd",
      d: "M0 0H26.8568V38H0V0Z",
      "clip-rule": "evenodd"
    }))), _g || (_g = /*#__PURE__*/React__default['default'].createElement("g", {
      mask: "url(#a)"
    }, /*#__PURE__*/React__default['default'].createElement("path", {
      d: "M17.0205 32.4586C16.364 32.4586 15.8342 31.9277 15.8342 31.2713C15.8342 30.6138 16.364 30.0829 17.0205 30.0829C18.9839 30.0829 20.5834 28.1275 20.5834 25.7288C20.5834 25.0723 21.1132 24.5425 21.7707 24.5425C22.4282 24.5425 22.9591 25.0723 22.9591 25.7288C22.9591 29.4425 20.2979 32.4586 17.0205 32.4586ZM13.7984 0.165882C13.6244 -0.055294 13.2917 -0.055294 13.1177 0.165882C11.0276 2.8582 0 17.3533 0 24.2328C0 31.8332 6.02503 38 13.4586 38C20.8921 38 26.9171 31.8332 26.9171 24.2328C26.9171 17.3533 15.8885 2.8582 13.7984 0.165882Z",
      "clip-rule": "evenodd"
    }))), children);
  }

  return /*#__PURE__*/React__default['default'].createElement(iconPropTypes.Icon, iconPropTypes._objectSpread2({
    width: size,
    height: size,
    ref: ref,
    xmlns: "http://www.w3.org/2000/svg",
    fill: "currentColor",
    viewBox: "0 0 27 38"
  }, rest), _mask2 || (_mask2 = /*#__PURE__*/React__default['default'].createElement("mask", {
    id: "a",
    style: "mask-type:alpha",
    width: "27",
    height: "38",
    x: "0",
    y: "0",
    maskUnits: "userSpaceOnUse"
  }, /*#__PURE__*/React__default['default'].createElement("path", {
    "fill-rule": "evenodd",
    d: "M0 0H26.8568V38H0V0Z",
    "clip-rule": "evenodd"
  }))), _g2 || (_g2 = /*#__PURE__*/React__default['default'].createElement("g", {
    mask: "url(#a)"
  }, /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M17.0205 32.4586C16.364 32.4586 15.8342 31.9277 15.8342 31.2713C15.8342 30.6138 16.364 30.0829 17.0205 30.0829C18.9839 30.0829 20.5834 28.1275 20.5834 25.7288C20.5834 25.0723 21.1132 24.5425 21.7707 24.5425C22.4282 24.5425 22.9591 25.0723 22.9591 25.7288C22.9591 29.4425 20.2979 32.4586 17.0205 32.4586ZM13.7984 0.165882C13.6244 -0.055294 13.2917 -0.055294 13.1177 0.165882C11.0276 2.8582 0 17.3533 0 24.2328C0 31.8332 6.02503 38 13.4586 38C20.8921 38 26.9171 31.8332 26.9171 24.2328C26.9171 17.3533 15.8885 2.8582 13.7984 0.165882Z",
    "clip-rule": "evenodd"
  }))), children);
});
WaterPositive.propTypes = iconPropTypes.iconPropTypes;

module.exports = WaterPositive;
