/**
 * Copyright IBM Corp. 2016, 2020
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @carbon/icon-build-helpers. DO NOT EDIT.
 */
export { default as Workspace32 } from './workspace/32.js';
export { default as Workspace24 } from './workspace/24.js';
export { default as Workspace20 } from './workspace/20.js';
export { default as Workspace16 } from './workspace/16.js';
export { default as Arrows32 } from './arrows/32.js';
export { default as Arrows24 } from './arrows/24.js';
export { default as Arrows20 } from './arrows/20.js';
export { default as Arrows16 } from './arrows/16.js';
export { default as ArrowsGlyph } from './arrows/index.js';
