/**
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @un/icon-build-helpers. DO NOT EDIT.
 * @un/icon-build-helpers is a fork of @carbon/icon-build-helpers
 */
'use strict';

Object.defineProperty(exports, '__esModule', { value: true });

var Icon = require('./Icon-17378097.js');
var __generated___bucket0_js = require('./__generated__/bucket-0.js');
require('@carbon/icon-helpers');
require('prop-types');
require('react');



exports.Icon = Icon.Icon;
exports.AffectedPopulationNegative = __generated___bucket0_js.AffectedPopulationNegative;
exports.AffectedPopulationPositive = __generated___bucket0_js.AffectedPopulationPositive;
exports.AidsNegative = __generated___bucket0_js.AidsNegative;
exports.AidsPositive = __generated___bucket0_js.AidsPositive;
exports.AirportNegative = __generated___bucket0_js.AirportNegative;
exports.AirportPositive = __generated___bucket0_js.AirportPositive;
exports.BeneficiariesNegative = __generated___bucket0_js.BeneficiariesNegative;
exports.BeneficiarisPositive = __generated___bucket0_js.BeneficiarisPositive;
exports.BreastFeedingNegative = __generated___bucket0_js.BreastFeedingNegative;
exports.BreastFeedingPositive = __generated___bucket0_js.BreastFeedingPositive;
exports.CashBasedTransfersNegative = __generated___bucket0_js.CashBasedTransfersNegative;
exports.CashBasedTransfersPositive = __generated___bucket0_js.CashBasedTransfersPositive;
exports.CashNegative = __generated___bucket0_js.CashNegative;
exports.CashPositive = __generated___bucket0_js.CashPositive;
exports.ChildrenNegative = __generated___bucket0_js.ChildrenNegative;
exports.ChildrenPositive = __generated___bucket0_js.ChildrenPositive;
exports.CivilMilitaryCoordinationNegative = __generated___bucket0_js.CivilMilitaryCoordinationNegative;
exports.CivilMilitaryCoordinationPositive = __generated___bucket0_js.CivilMilitaryCoordinationPositive;
exports.ConflictNegative = __generated___bucket0_js.ConflictNegative;
exports.ConflictPositive = __generated___bucket0_js.ConflictPositive;
exports.DroneNegative = __generated___bucket0_js.DroneNegative;
exports.DronePositive = __generated___bucket0_js.DronePositive;
exports.DroughtNegative = __generated___bucket0_js.DroughtNegative;
exports.DroughtPositive = __generated___bucket0_js.DroughtPositive;
exports.EarthquakeNegative = __generated___bucket0_js.EarthquakeNegative;
exports.EarthquakePositive = __generated___bucket0_js.EarthquakePositive;
exports.EmailContactNegative = __generated___bucket0_js.EmailContactNegative;
exports.EmailContactPositive = __generated___bucket0_js.EmailContactPositive;
exports.EmergencyResponseNegative = __generated___bucket0_js.EmergencyResponseNegative;
exports.EmergencyResponsePositive = __generated___bucket0_js.EmergencyResponsePositive;
exports.EmergencyTelecommunicationsClusterNegative = __generated___bucket0_js.EmergencyTelecommunicationsClusterNegative;
exports.EmergencyTelecommunicationsClusterPositive = __generated___bucket0_js.EmergencyTelecommunicationsClusterPositive;
exports.EvacuationNegative = __generated___bucket0_js.EvacuationNegative;
exports.EvacuationPositive = __generated___bucket0_js.EvacuationPositive;
exports.EvaluationNegative = __generated___bucket0_js.EvaluationNegative;
exports.EvaluationPositive = __generated___bucket0_js.EvaluationPositive;
exports.FloodsNegative = __generated___bucket0_js.FloodsNegative;
exports.FloodsPositive = __generated___bucket0_js.FloodsPositive;
exports.FoodAssistanceForAssetsNegative = __generated___bucket0_js.FoodAssistanceForAssetsNegative;
exports.FoodDistributionNegative = __generated___bucket0_js.FoodDistributionNegative;
exports.FoodDistributionPositive = __generated___bucket0_js.FoodDistributionPositive;
exports.FoodForAssetsPositive = __generated___bucket0_js.FoodForAssetsPositive;
exports.FoodNegative = __generated___bucket0_js.FoodNegative;
exports.FoodPositive = __generated___bucket0_js.FoodPositive;
exports.FoodSecurityClusterNegative = __generated___bucket0_js.FoodSecurityClusterNegative;
exports.FoodSecurityClusterPositive = __generated___bucket0_js.FoodSecurityClusterPositive;
exports.GenderNegative = __generated___bucket0_js.GenderNegative;
exports.GenderPositive = __generated___bucket0_js.GenderPositive;
exports.GreenhouseGasEmissionsNegative = __generated___bucket0_js.GreenhouseGasEmissionsNegative;
exports.GreenhouseGasEmissionsPositive = __generated___bucket0_js.GreenhouseGasEmissionsPositive;
exports.InfantNegative = __generated___bucket0_js.InfantNegative;
exports.InfantPositive = __generated___bucket0_js.InfantPositive;
exports.LogisticsClusterNegative = __generated___bucket0_js.LogisticsClusterNegative;
exports.LogisticsClustersPositive = __generated___bucket0_js.LogisticsClustersPositive;
exports.MVamNegative = __generated___bucket0_js.MVamNegative;
exports.MVamPositive = __generated___bucket0_js.MVamPositive;
exports.MedicalEvacuationsNegative = __generated___bucket0_js.MedicalEvacuationsNegative;
exports.MedicalEvacuationsPositive = __generated___bucket0_js.MedicalEvacuationsPositive;
exports.MonitoringNegative = __generated___bucket0_js.MonitoringNegative;
exports.MonitoringPositive = __generated___bucket0_js.MonitoringPositive;
exports.MonsoonNegative = __generated___bucket0_js.MonsoonNegative;
exports.MonsoonPositive = __generated___bucket0_js.MonsoonPositive;
exports.NutritionClusterNegative = __generated___bucket0_js.NutritionClusterNegative;
exports.NutritionClusterPositive = __generated___bucket0_js.NutritionClusterPositive;
exports.P4pNegative = __generated___bucket0_js.P4pNegative;
exports.P4pPositive = __generated___bucket0_js.P4pPositive;
exports.ParnershipNegative = __generated___bucket0_js.ParnershipNegative;
exports.PartnershipPositive = __generated___bucket0_js.PartnershipPositive;
exports.PopulationDisplacementNegative = __generated___bucket0_js.PopulationDisplacementNegative;
exports.PopulationDisplacementPositive = __generated___bucket0_js.PopulationDisplacementPositive;
exports.PopulationReturnNegative = __generated___bucket0_js.PopulationReturnNegative;
exports.PopulationReturnPositive = __generated___bucket0_js.PopulationReturnPositive;
exports.PowerplantNegative = __generated___bucket0_js.PowerplantNegative;
exports.PowerplantPositive = __generated___bucket0_js.PowerplantPositive;
exports.PregnantNegative = __generated___bucket0_js.PregnantNegative;
exports.PregnantPositive = __generated___bucket0_js.PregnantPositive;
exports.ProcurementNegative = __generated___bucket0_js.ProcurementNegative;
exports.ProcurementPositive = __generated___bucket0_js.ProcurementPositive;
exports.ProtectionClusterNegative = __generated___bucket0_js.ProtectionClusterNegative;
exports.ProtectionClusterPositive = __generated___bucket0_js.ProtectionClusterPositive;
exports.PublicInformationNegative = __generated___bucket0_js.PublicInformationNegative;
exports.PublicInformationPositive = __generated___bucket0_js.PublicInformationPositive;
exports.RefugeeCampNegative = __generated___bucket0_js.RefugeeCampNegative;
exports.RefugeeCampPositive = __generated___bucket0_js.RefugeeCampPositive;
exports.ReliefGoodsNegative = __generated___bucket0_js.ReliefGoodsNegative;
exports.ReliefGoodsPositive = __generated___bucket0_js.ReliefGoodsPositive;
exports.ResourcingNegative = __generated___bucket0_js.ResourcingNegative;
exports.ResourcingPositive = __generated___bucket0_js.ResourcingPositive;
exports.SchoolFeedingNegative = __generated___bucket0_js.SchoolFeedingNegative;
exports.SchoolFeedingPositive = __generated___bucket0_js.SchoolFeedingPositive;
exports.SecurityNegative = __generated___bucket0_js.SecurityNegative;
exports.SecurityPositive = __generated___bucket0_js.SecurityPositive;
exports.ShipNegative = __generated___bucket0_js.ShipNegative;
exports.ShipPositive = __generated___bucket0_js.ShipPositive;
exports.SustainableProcurementPositive = __generated___bucket0_js.SustainableProcurementPositive;
exports.SustaninableProcurementNegative = __generated___bucket0_js.SustaninableProcurementNegative;
exports.TruckNegative = __generated___bucket0_js.TruckNegative;
exports.TruckPositive = __generated___bucket0_js.TruckPositive;
exports.VamNegative = __generated___bucket0_js.VamNegative;
exports.VamPositive = __generated___bucket0_js.VamPositive;
exports.VoucherNegative = __generated___bucket0_js.VoucherNegative;
exports.VoucherPositive = __generated___bucket0_js.VoucherPositive;
exports.WarehouseNegative = __generated___bucket0_js.WarehouseNegative;
exports.WarehousePositive = __generated___bucket0_js.WarehousePositive;
exports.WasteNegative = __generated___bucket0_js.WasteNegative;
exports.WastePositive = __generated___bucket0_js.WastePositive;
exports.WaterNegative = __generated___bucket0_js.WaterNegative;
exports.WaterPositive = __generated___bucket0_js.WaterPositive;
