/**
 *
 * Code generated by @un/icon-build-helpers. DO NOT EDIT.
 * @un/icon-build-helpers is a fork of @carbon/icon-build-helpers
 * 
 */
'use strict';

var index = {
  "elem": "svg",
  "attrs": {
    "xmlns": "http://www.w3.org/2000/svg",
    "fill": "currentColor",
    "viewBox": "0 0 628 506",
    "width": "628",
    "height": "506"
  },
  "content": [{
    "elem": "path",
    "attrs": {
      "fill": "#F6AA8A",
      "stroke": "#07074E",
      "stroke-width": "22",
      "d": "M451.832 29.5722C316.483 22.8814 126.643 460.892 429.825 475.879C727.592 490.599 614.904 24.3474 451.832 29.5722Z"
    }
  }, {
    "elem": "path",
    "attrs": {
      "stroke": "#07074E",
      "stroke-linecap": "round",
      "stroke-linejoin": "round",
      "stroke-width": "22",
      "d": "M469.932 114.992C484.829 130.823 495.093 142.802 506.746 163.303M526.285 195.061C538.45 217.398 556.259 272.015 551.99 321.917"
    }
  }, {
    "elem": "path",
    "attrs": {
      "fill": "#FAC695",
      "stroke": "#07074E",
      "stroke-width": "22",
      "d": "M194.958 12.3042C48.5734 12.3042 -132.943 495 194.957 495C517.002 495 370.619 -2.03016 194.958 12.3042Z"
    }
  }, {
    "elem": "path",
    "attrs": {
      "stroke": "#07074E",
      "stroke-linecap": "round",
      "stroke-linejoin": "round",
      "stroke-width": "22",
      "d": "M219.029 103.498C235.945 119.783 247.655 132.16 261.318 153.657M284.089 186.879C298.402 210.33 320.522 268.306 318.57 322.373"
    }
  }],
  "name": "eggs"
};

module.exports = index;
