/**
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @un/icon-build-helpers. DO NOT EDIT.
 * @un/icon-build-helpers is a fork of @carbon/icon-build-helpers
 */
'use strict';

var Icon = require('../Icon-17378097.js');
var React = require('react');
require('@carbon/icon-helpers');
require('prop-types');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var React__default = /*#__PURE__*/_interopDefaultLegacy(React);

var _mask, _g, _path;

var _excluded = ["children"];
var P4pPositive = /*#__PURE__*/React__default['default'].forwardRef(function P4pPositive(_ref, ref) {
  var children = _ref.children,
      rest = Icon._objectWithoutProperties(_ref, _excluded);

  return /*#__PURE__*/React__default['default'].createElement(Icon.Icon, Icon._extends({
    width: 40,
    height: 15,
    viewBox: "0 0 40 15",
    xmlns: "http://www.w3.org/2000/svg",
    fill: "currentColor",
    ref: ref
  }, rest), _mask || (_mask = /*#__PURE__*/React__default['default'].createElement("mask", {
    id: "a",
    width: "13",
    height: "15",
    x: "0",
    y: "0",
    maskUnits: "userSpaceOnUse"
  })), _g || (_g = /*#__PURE__*/React__default['default'].createElement("g", {
    mask: "url(#a)"
  })), _path || (_path = /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M19.89 8.94899H15.65L19.89 3.67799V8.94899zM23.476.403992H19.654L12.837 8.84999V11.608H19.89V15H23.476V11.608H25.461V8.94899H23.476V.403992zM35.285 6.13899C35.174 6.42699 35.001 6.67699 34.763 6.88799 34.48 7.12199 34.131 7.27799 33.72 7.35399 33.306 7.43499 32.779 7.47299 32.139 7.47299H31.064V3.11999H31.712C32.329 3.11999 32.826 3.12899 33.196 3.14499 33.567 3.16199 33.951 3.24699 34.34 3.40299 34.631 3.52099 34.892 3.72699 35.114 4.02299 35.334 4.31999 35.444 4.67099 35.444 5.08299 35.444 5.49899 35.394 5.85099 35.285 6.13899zM38.863 2.83799C38.552 2.23999 38.105 1.74599 37.518 1.35899 37.03 1.04099 36.467.801992 35.834.642992 35.197.482992 34.418.403992 33.49.403992H27.31V14.961H31.064V10.22H33.402C34.463 10.22 35.353 10.074 36.066 9.78099 36.777 9.48399 37.424 9.05399 38.006 8.47699 38.429 8.05499 38.758 7.52999 38.984 6.90999 39.214 6.28699 39.327 5.64999 39.327 4.99799 39.327 4.15799 39.172 3.43799 38.863 2.83799z",
    clipRule: "evenodd"
  })), children);
});

module.exports = P4pPositive;
