/**
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @un/icon-build-helpers. DO NOT EDIT.
 * @un/icon-build-helpers is a fork of @carbon/icon-build-helpers
 */
'use strict';

var Icon = require('../../Icon-17378097.js');
var React = require('react');
require('@carbon/icon-helpers');
require('prop-types');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var React__default = /*#__PURE__*/_interopDefaultLegacy(React);

var _rect, _path, _path2, _mask, _path3, _path4, _circle;

var _excluded = ["children"];
var IllustrationsNotebook_2 = /*#__PURE__*/React__default['default'].forwardRef(function IllustrationsNotebook_2(_ref, ref) {
  var children = _ref.children,
      rest = Icon._objectWithoutProperties(_ref, _excluded);

  return /*#__PURE__*/React__default['default'].createElement(Icon.Icon, Icon._extends({
    width: 535,
    height: 829,
    viewBox: "0 0 535 829",
    xmlns: "http://www.w3.org/2000/svg",
    fill: "currentColor",
    ref: ref
  }, rest), _rect || (_rect = /*#__PURE__*/React__default['default'].createElement("rect", {
    width: "523",
    height: "758",
    x: "6",
    y: "65",
    fill: "#ECC086",
    stroke: "#000",
    strokeLinejoin: "round",
    strokeWidth: "12",
    rx: "14"
  })), _path || (_path = /*#__PURE__*/React__default['default'].createElement("path", {
    fill: "#fff",
    stroke: "#000",
    strokeLinejoin: "round",
    strokeWidth: "12",
    d: "M37 105H499V783H37z"
  })), _path2 || (_path2 = /*#__PURE__*/React__default['default'].createElement("path", {
    stroke: "#000",
    strokeLinecap: "round",
    strokeLinejoin: "round",
    strokeWidth: "12",
    d: "M109 262L427 262M109 317L427 317M109 371L427 371M109 424L427 424M109 479L427 479M109 534L427 534M109 588L427 588M109 641L427 641"
  })), _mask || (_mask = /*#__PURE__*/React__default['default'].createElement("mask", {
    id: "a",
    fill: "#fff"
  })), _path3 || (_path3 = /*#__PURE__*/React__default['default'].createElement("path", {
    fill: "#C4C4C4",
    fillRule: "evenodd",
    d: "M267.5 0C248.998 0 234 14.9985 234 33.5V49H180C174.477 49 170 53.4772 170 59V112C170 117.523 174.477 122 180 122H355C360.523 122 365 117.523 365 112V59C365 53.4772 360.523 49 355 49H301V33.5C301 14.9985 286.002 0 267.5 0Z",
    clipRule: "evenodd"
  })), _path4 || (_path4 = /*#__PURE__*/React__default['default'].createElement("path", {
    fill: "#000",
    d: "M234 49V61H246V49H234ZM301 49H289V61H301V49ZM246 33.5C246 21.6259 255.626 12 267.5 12V-12C242.371 -12 222 8.37105 222 33.5H246ZM246 49V33.5H222V49H246ZM180 61H234V37H180V61ZM182 59C182 60.1046 181.105 61 180 61V37C167.85 37 158 46.8497 158 59H182ZM182 112V59H158V112H182ZM180 110C181.105 110 182 110.895 182 112H158C158 124.15 167.85 134 180 134V110ZM355 110H180V134H355V110ZM353 112C353 110.895 353.895 110 355 110V134C367.15 134 377 124.15 377 112H353ZM353 59V112H377V59H353ZM355 61C353.895 61 353 60.1046 353 59H377C377 46.8497 367.15 37 355 37V61ZM301 61H355V37H301V61ZM289 33.5V49H313V33.5H289ZM267.5 12C279.374 12 289 21.6259 289 33.5H313C313 8.37105 292.629 -12 267.5 -12V12Z",
    mask: "url(#a)"
  })), _circle || (_circle = /*#__PURE__*/React__default['default'].createElement("circle", {
    cx: "268",
    cy: "38",
    r: "11",
    fill: "#000"
  })), children);
});

module.exports = IllustrationsNotebook_2;
