/**
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @un/icon-build-helpers. DO NOT EDIT.
 * @un/icon-build-helpers is a fork of @carbon/icon-build-helpers
 */
'use strict';

var Icon = require('../Icon-17378097.js');
var React = require('react');
require('@carbon/icon-helpers');
require('prop-types');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var React__default = /*#__PURE__*/_interopDefaultLegacy(React);

var _mask, _g, _path;

var _excluded = ["children"];
var WasteNegative = /*#__PURE__*/React__default['default'].forwardRef(function WasteNegative(_ref, ref) {
  var children = _ref.children,
      rest = Icon._objectWithoutProperties(_ref, _excluded);

  return /*#__PURE__*/React__default['default'].createElement(Icon.Icon, Icon._extends({
    width: 56,
    height: 56,
    viewBox: "0 0 56 56",
    xmlns: "http://www.w3.org/2000/svg",
    fill: "currentColor",
    ref: ref
  }, rest), _mask || (_mask = /*#__PURE__*/React__default['default'].createElement("mask", {
    id: "a",
    width: "56",
    height: "56",
    x: "0",
    y: "0",
    maskUnits: "userSpaceOnUse"
  })), _g || (_g = /*#__PURE__*/React__default['default'].createElement("g", {
    mask: "url(#a)"
  })), _path || (_path = /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M21.756 24.069C21.333 24.069 20.988 24.414 20.988 24.837L22 44.798C22 45.22 22.344 45.566 22.767 45.566 23.189 45.566 23.535 45.22 23.535 44.798L22.524 24.837C22.524 24.414 22.178 24.069 21.756 24.069zM27.898 24.069C27.476 24.069 27.13 24.414 27.13 24.837V44.798C27.13 45.22 27.476 45.566 27.898 45.566 28.32 45.566 28.666 45.22 28.666 44.798V24.837C28.666 24.414 28.32 24.069 27.898 24.069zM34.04 24.069C33.618 24.069 33.272 24.414 33.272 24.837L32.26 44.798C32.26 45.22 32.606 45.566 33.028 45.566 33.45 45.566 33.795 45.22 33.795 44.798L34.807 24.837C34.807 24.414 34.462 24.069 34.04 24.069z",
    clipRule: "evenodd"
  })), children);
});

module.exports = WasteNegative;
