/**
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @un/icon-build-helpers. DO NOT EDIT.
 * @un/icon-build-helpers is a fork of @carbon/icon-build-helpers
 */
'use strict';

var Icon = require('../Icon-17378097.js');
var React = require('react');
require('@carbon/icon-helpers');
require('prop-types');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var React__default = /*#__PURE__*/_interopDefaultLegacy(React);

var _path, _mask, _g, _path2;

var _excluded = ["children"];
var ProcurementPositive = /*#__PURE__*/React__default['default'].forwardRef(function ProcurementPositive(_ref, ref) {
  var children = _ref.children,
      rest = Icon._objectWithoutProperties(_ref, _excluded);

  return /*#__PURE__*/React__default['default'].createElement(Icon.Icon, Icon._extends({
    width: 29,
    height: 39,
    viewBox: "0 0 29 39",
    xmlns: "http://www.w3.org/2000/svg",
    fill: "currentColor",
    ref: ref
  }, rest), _path || (_path = /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M13.608 9.36901L12.289 3.41501C12.126 2.68201 11.475 2.16101 10.724 2.16101H6.40098C5.88798 2.16101 5.50798 2.63501 5.61898 3.13501L7.20198 9.36901H13.608Z",
    clipRule: "evenodd"
  })), _mask || (_mask = /*#__PURE__*/React__default['default'].createElement("mask", {
    id: "a",
    width: "29",
    height: "29",
    x: "0",
    y: "10",
    maskUnits: "userSpaceOnUse"
  })), _g || (_g = /*#__PURE__*/React__default['default'].createElement("g", {
    mask: "url(#a)"
  })), _path2 || (_path2 = /*#__PURE__*/React__default['default'].createElement("path", {
    d: "M18.417 9.36902H21.617L23.206 1.50502C23.294 1.01602 22.918 0.559021 22.413 0.559021H20.018C19.142 0.559021 18.427 1.28802 18.414 2.16102C18.4 1.28802 17.696 0.559021 16.82 0.559021H14.417C13.913 0.559021 13.536 1.01602 13.625 1.50502L15.211 9.36902H18.417Z",
    clipRule: "evenodd"
  })), children);
});

module.exports = ProcurementPositive;
